### ISSUE TITLE
[editor]  readonly für alle ELemente einstellbar machen

### ISSUE THREAD

**Issue by jojohoch** [iqb-berlin/verona-modules-aspect#112]
Richard: Den read-only Schalter gibt es bereits für alle Eingabeelemente. Es beachten nur nicht alle Elemente diesen. Das ist Teil 1 des Tickets.
Teil 2 ist, dass die Elemente auch nicht auf andere Weise fokussiert und damit befüllbar sein sollen.

**Comment by rhenck** [comment]
Readonly elemente können bspw. via Tab taste angesteuert werden und damit ist unsere bisherige Lösung unzureichend. Muss geklärt werden, wie das technisch gelöst werden soll.
