### ISSUE TITLE
[common] #input sollte im text-field-componet entfernt werden

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/verona-modules-aspect#140]
Nutzlos und nicht ungefährlich, wenn mehrere input-Elemente dieselbe id haben

**Comment by mechtelm** [comment]
Ähm sehe gerade, dass onFocus und onBlur die ID verwenden ???

**Comment by jojohoch** [comment]
Die Reference wird benötigt für das virtuelle Keyboard
Da sie nur innerhalb des Temlates unique sein muss, ist die Verwendung aus meiner Sicht  ungefährlich.

**Comment by mechtelm** [comment]
Ok Angular scheint die ID nochmal umzuformen, so dass die ID tatsächlich nicht mehrfach vorkommt. Weiß nicht mehr, warum ich das gedacht hatte.
