### ISSUE TITLE
[player] Verona4: Übermittlung der Metadaten ändern

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/verona-modules-aspect#150]
Ab Version 4 gibt es im json+ld-Tag der Html geänderte Elemente. Das gesamte Objekt wird stringified in der Property `metadata` der `vopReadyNotification` geschickt. Aktuell wird das zwar im Testcenter nicht ausgewertet. Weil aber das Objekt eine Property `type` hat, wird aktuell der Nachrichtentyp `vopReadyNotification` überschrieben, wenn man die Metadaten auf Version 4 ändert (s. u.).

Siehe [betreffende Codezeile](https://github.com/iqb-berlin/verona-modules-aspect/blob/50298f718d9da3d203f714c4cdf48cbbbdb49a81/projects/player/src/app/services/verona-post.service.ts#L78).

Siehe [Verona-Spec Player](https://verona-interfaces.github.io/player/).

Siehe [Verona Metadaten-Spec](https://github.com/verona-interfaces/metadata/blob/master/verona-module-metadata.json).

```json
  {
    "$schema": "https://raw.githubusercontent.com/verona-interfaces/metadata/master/verona-module-metadata.json",
    "type": "player",
    "id": "iqb-player-aspect",
    "name": [
      {
        "value": "IQB-Player (Aspect)",
        "lang": "de"
      },
      {
        "value": "IQB-Player (Aspect)",
        "lang": "en"
      }
    ],
    "version": "1.13.0",
    "specVersion": "4.0",
    "description": [
      {
        "value": "Dieser Player wird vom IQB für komplexe Testaufgaben in der Kompetenzdiagnostik verwendet.",
        "lang": "de"
      }
    ],
    "maintainer": {
      "name": [
        {
          "value": "IQB - Institut zur Qualitätsentwicklung im Bildungswesen",
          "lang": "de"
        },
        {
          "value": "IQB - Institute for Educational Quality Improvement",
          "lang": "en"
        }
      ],
      "url": "https://www.iqb.hu-berlin.de",
      "email": "iqb-tbadev@hu-berlin.de"
    },
    "code": {
      "repositoryType": "git",
      "repositoryUrl": "https://github.com/iqb-berlin/verona-modules-aspect",
      "licenseType": "MIT",
      "licenseUrl": "https://opensource.org/licenses/MIT"
    }
  }
```

**Comment by jojohoch** [comment]
gibt aktuell noch probleme im studio
