### ISSUE TITLE
Bilderauswahl drop-list: Dateiexplorer öffnet 2x

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/verona-modules-aspect#161]

**Comment by tobhu1981** [comment]
Beim Klick auf "Bild laden" wird unter Frx der Datei-Explorer 2x geöffnet. Das Bild wird dann erst geladen, wenn dieses im zuletzt geöffneten Fenster ausgewählt wird. Unter Chr geht das 2. Fenster auf nachdem im ersten Fenster ein Bild gewählt und geladen wurde.

**Comment by jojohoch** [comment]
Fehler taucht nicht in FF auf, sondern in Chrome!
