### ISSUE TITLE
Editor v1.21: Elemente können nicht via DnD in bereits befüllte Zellen gelegt werden

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/verona-modules-aspect#166]
Geht bisher nur via Properties Panel. Am ehesten für Rahmen relevant.

**Comment by tobhu1981** [comment]
Bsph. sind zwei Spalten und eine Zeile im dynamischen Abschnitt angelegt. In der so entstandenen ersten Zelle ein Element und anschließend einen Rahmen daraufzulegen, ist kein Problem. Ich bekomme es aber nicht hin in der zweiten Zelle ein Element mit einem Rahmen anzulegen. Enthält die zweite Zelle ein Element und markiert man diese Zelle und klickt anschließend auf "Rahmen", landet der Rahmen immer in der ersten Zelle.

**Comment by rhenck** [comment]
Das lässt sich über manuelle Koordinatenangabe im Eigenschaftenfenster lösen. Via DnD geht das Übereinanderlegen nicht.

Dieses Problem ist exklusiv im bezug auf Rahmen Elemente. Alle anderen will man sowieso nicht übereinander. Man müsste also eine Sonderbehandlung für Rahmen im dynamischen Kontext einführen. -> Sehr viel Aufwand, wenig Ertrag. Machen wir in absehbarer Zeit nicht.

**Comment by rhenck** [comment]
Zu kompliziert für zu geringen Nutzen
