### ISSUE TITLE
Lückentext: Eingabefelder sollen Eingabehilfe anzeigen können

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/verona-modules-aspect#174]

**Comment by jojohoch** [comment]
Hierzu sind noch weiterer Informationen notwendig

**Comment by tobhu1981** [comment]
Die Anfrage kam vom IBBW und Martin hatte denen zugesagt, dass es diese Möglichkeit ab dem nächsten Release (1.27) geben würde. @Joachim: Soweit ich weiß wollen sie die Eingabehilfe in vollem Umfang, so wie auch bei einem Eingabefeld. Wenn ihr noch weitere Informationen benötigt, gebt Bescheid, dann kläre ich das mit dem IBBW.
