### ISSUE TITLE
Sanitizer Error bei Close Elementen

### ISSUE THREAD

**Issue by jojohoch** [iqb-berlin/verona-modules-aspect#197]
Beispiel wurde mit editor/1.26 erstellt. Muss umbenannt werden![https://app.zenhub.com/files/358306669/44551ae1-d64e-4423-8636-ad608a948ea5/download](https://app.zenhub.com/files/358306669/44551ae1-d64e-4423-8636-ad608a948ea5/download)

**Comment by rhenck** [comment]
Das mit der angehängten Datei klappt iwie nicht. Ich bekomme die nicht geladen.
