### ISSUE TITLE
GeoGebraIntegration implementieren

### ISSUE THREAD

**Issue by jojohoch** [iqb-berlin/verona-modules-aspect#198]
s. hier: https://wiki.geogebra.org/en/Reference:GeoGebra_Apps_Embedding

**Comment by jojohoch** [comment]
zur Orientierung? https://github.com/saunAAA/react-geogebra

**Comment by jojohoch** [comment]
Pfad zu Geogebra Dateien: 
R:\MatheSek1\700_TBA\23_Haupttest 2023\01_Probeumsetzung\03_GeoGebra

**Comment by rhenck** [comment]
Beispiel-HTML unter:
P:\TBA\04_Forschung\GeoGebra_VERA3_VERA8\VERA2023\M47013 - Schulweg

Korrespondierende Aufgabe:
https://www.iqb-teststudio.de/#/a/72/u/2359

**Comment by rhenck** [comment]
[https://app.zenhub.com/files/358306669/c7e271cc-c3ab-4d92-99f1-e0a91df1d7a7/download](https://app.zenhub.com/files/358306669/c7e271cc-c3ab-4d92-99f1-e0a91df1d7a7/download)

**Comment by rhenck** [comment]
Unklare Settings:
"enableShiftDragZoom"
"allowUpscale"
"capturingThreshold"
"customToolBar"

Hier wüsste ich gerne, was die Dinge zu bedeuten haben bzw. was ihr damit erreichen wollt.

**Comment by rhenck** [comment]
Ich habe mal geschaut, ob man auch komplette GeoGebra-Dateien (ggb) laden kann, funktioniert aber nicht so einfach. Dazu müsste man die Datei vorher irgendwo auf dem Server (Workspace?) hochladen und dann im Editor nur den Pfad hinterlegen. Ist konzeptionell etwas unklar, aber sicherlich ziemlich umständlich.
Dementsprechend bleibts erstmal bei base64, wie gehabt.

**Comment by rhenck** [comment]
https://blog.briebug.com/blog/angular-how-to-implement-drag-and-drop-in-a-material-tree

https://material.angular.io/components/tree/examples

**Comment by rhenck** [comment]
ggb-Dateiselbst als base64 encoden und schauen, ob es geht

**Comment by jojohoch** [comment]
Wird der Spinner getriggert?
