### ISSUE TITLE
Markierfunktion kaputt

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#199]
v1.26/v1.20
Die Markierfunktion markiert nichts. Auch die neue Funktionalität, dass die Buttons noch mal an der Mauszeigerposition auftauchen, funktioniert nicht (bei diesem Beispiel würde man es aber auch nicht wollen). https://www.iqb-teststudio.de/#/a/103/u/2860

**Comment by jojohoch** [comment]
Ich bin für diese Aufgabe wohl nicht freigeschaltet. Kann den Fehler also nicht reproduzieren.
ABER: Abschalten lässt sich die Funktionalität allerdings nicht!

**Comment by jojohoch** [comment]
Korrektur der Positionsberechnung, nach Änderung des Doms, um auf iPads die Positionierung von dynamischen Elementen mit festen Abmessungen zu gewährleisten
