### ISSUE TITLE
Presentation Complete von Audio/Video auch für Abschnitte

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/verona-modules-aspect#208]
solange ein Audio noch nicht fertig abgespielt ist, sollen Abschnitte ausgebendet sein können

**Comment by jojohoch** [comment]
Property activeAfterID für Section implementiert
Property activeAfterID wird playerseitig ausgewertet
TODO: Input Möglichkeit für Property in Editor implementieren
