### ISSUE TITLE
Neue Sonderzeichen nötig: Einfache Anführungszeichen (nicht doppelte)

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/verona-modules-aspect#209]
Wir benötigen für Deutschaufgaben zusätzlich die folgenden Zeichen (der angegebene Code ist zur Erzeugung dieser Zeichen in Word):
Einzelnes Anführungszeichen unten: ALT + 0130, zum kopieren:  ‚
Einzelnes Anführungszeichen oben: ALT + 0145 sowie ALT + 0146, zum kopieren: ‘
Das sind Sonderzeichen, die im Deutschen Anwendung finden und im Gegensatz zu einem einfachen (englischen) Hochkomma "Serifenschlenker" (oder wie man das nennen mag) haben

**Comment by rhenck** [comment]
Für oben haben wir das doch schon oder ist das wieder was anderes?

**Comment by PaulineKohrt** [comment]
nee, das ist ein Anderes. Das was wir schon haben hat eine andere Ausrichtung und ist für Englisch (rechts im Screenshot) ) das was wir wollen ist für Deutsch (links im Screenshot)
![grafik](https://user-images.githubusercontent.com/78726636/161948237-24008a2b-0d51-42d0-8b7a-44e03dbd3b07.png)

**Comment by rhenck** [comment]
Ihr macht mich fertig... :D

**Comment by jkoelm** [comment]
https://typefacts.com/artikel/tastaturkuerzel
