### ISSUE TITLE
Obergrenze bei Zeitverzögerung für Aufforderungstext Audio?

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#211]
Ein Audio_2 soll 10 Minuten nachdem das vorherige Audio_1 fertig durchgelaufen ist einen Aufforderungstext anzeigen. Dazu haben wir für Audio_2 eingestellt, dass es erst nach Audio_1 abspielbar ist und eine Verzögerung für den Aufforderungstext von 600000 ms. Dass Audio_2 erst abspielbar wird, nachdem Audio_1 gelaufen ist, funktioniert. Der Aufforderungstext kommt aber deutlich früher, schon nach ca. 3,5 Minuten.

Bei Audio_3, das nach Audio_2 abspielbar wird und 1,5 Minuten nach Ablauf von Audio_2 auffordern soll, klappt es problemlos.

Ein anderes Audio_4, bei dem Autostart mit einer großen Verögerung von 16,5 Minuten eingestellt wurde, läuft auch zum richtigen Zeitpunkt.

Wo könnte der Fehler liegen?

https://www.iqb-teststudio.de/#/a/34/u/2986

**Comment by jojohoch** [comment]
war ein bug
