### ISSUE TITLE
likert-Element gibt statische Position und Dimensionierung im dynamischen Layout

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#213]
siehe Teilaufgabe 5 hier: https://www.iqb-teststudio.de/#/a/12/u/2811

Der ganze Abschnitt ist dynamisch, das Textelement in Zeile 1 weiß das, das likert-Element in Zeile 2 weiß das nicht.

**Comment by rhenck** [comment]
ja ist bekannt und bereits behoben. Likert hat einige Probleme.

**Comment by jkoelm** [comment]
Ist auch in v1.28/v1.22 noch so
