### ISSUE TITLE
Safari zeigt Seiteninhalte nicht an

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#216]
Wir haben die Rückmeldung bekommen, dass im Safari-Browser das Testcenter die Seiteninhalte komplett nicht anzeigt (siehe Bild). Informationen zur Version: macOS 11.15.7 (ist wohl nicht die aktuellste; Safari-Version konnte die Person nicht finden, aber ist vielleicht auch an macOs gebunden?)

 ![grafik.png](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/b27c33ba-533b-4492-9ced-127d7d45c3ae)

**Comment by jkoelm** [comment]
Scheint nicht generell für Safari zu gelten - auf den IQB Tablets funktioniert es

**Comment by jojohoch** [comment]
Das liegt an veralteten iOS-Versionen und damit verbunden an veralteten Safari Versionen. Insgesamt sollten wir stärker darauf achten, dass zu Fehlermeldungen immer Browserinfos  mit Versionsnummer gehören, außerdem ist es hilfreiuch  die Plattform, das Betriebssystem und seine Version zu kennen.

**Comment by rhenck** [comment]
Mal auf einem echten Mac (nicht IPad) testen. (Die Regel, dass wir nur die beiden aktuellen Versionen unterstützen gilt auch hier)

**Comment by jojohoch** [comment]
Auf macOs ist es wohlmöglich auch neuere Safari Versionen zu installieren. Jedoch stellt sich die Frage, ob auf beschriebenen Mac jemals Safari geupdated wurde, denn das Betriebssystem wurde es offensichtlich nicht.
