### ISSUE TITLE
Löschen von dynamischen Abschnitten

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#217]
v1.27/v1.21
Hat keine Priorität, aber wäre schön, wenn das irgendwann geändert wird.

Echte (leere) dynamische Abschnitte lassen sich nur sehr unkomfortabel löschen, wenn darunter noch ein anderer Abschnitt liegt. Das liegt daran, dass die pinken Knöpfe für die Abschnittseinstellungen nicht im Fokus bleiben, wenn darunter die pinken Knöpfe des nächsten Abschnitts liegen. Das ist nicht neu, aber bisher konnte man es lösen, indem man dem Abschnitt eine größere Höhe gegeben hat. Zu den Einstellungen, ob der Abschnitt dynamisch ist oder nicht, gelangt man nun aber gar nicht mehr. Momentan müsste man extra ein ausreichend großes Elemente in den Abschnitt packen, um ihn löschen zu können.

Vielleicht könnten die pinken Knöpfe des aktiven/ausgewählten Abschnitts im Vordergrund bleiben?

![dyn.Abschnitt_löschen.gif](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/f970bb57-425d-40e7-9bb9-932303204a20)

**Comment by rhenck** [comment]
Ist bereits gelöst: Das Abschnittsmenu wird nur noch für den ausgewählten Abschnitt eingeblendet.
