### ISSUE TITLE
DOM Struktur verwirrend und aufgebläht

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/verona-modules-aspect#218]
- ElementSplitter ist kein guter Name. Es ist völlig unklar was da geteilt werden soll
- Elemente sind in mehrfachen 'inline-container'n verpackt, die (zumindest scheinbar) keinen Sinn ergeben
Die Ordnung scheint zu sein: aspect-element-splitter -> inline-container -> inline-container -> aspect-element-input-group
Mindestens 2 davon würde ich versuchen zu kürzen.

**Comment by jojohoch** [comment]
- ElementSplitter zu ElementGroupSelection umbenannt
- Elemente können statisch, dynamisch und dynamisch mit festen Abmessungen sein. Die Darstellung von dynamischen Elemenen mit festen Abmessungen muss beim iPad über die Verschachtelung (s. player & editor) von divs mit speziellen Klassen (fixed-size-content-wrapper, fixed-size-content) erfolgen. Sind die Element statisch, wird diesen divs im editor und player  die Klasse inline-container zugewiesen. (Alternativ  zu dieser Konstruktion könnten unterschiedliche Templates genutzt werden. Dies würde zwar den Code des Doms übersichtlicher, den der jeweiligen Editor- und Player-Templates aber komplexer machen)
