### ISSUE TITLE
DropList fix reviewn

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/verona-modules-aspect#219]
https://github.com/iqb-berlin/verona-modules-aspect/commit/9b7854616d162a18e73ad995024c2cbb121e0549

**Comment by jojohoch** [comment]
Statt der Verwendung eines globalen form styles wird nun die Klasse ".inline-container" genutzt, um dem Form-Element einer Droplist die display-Eigenschaft "inline" zuzuweisen .
