### ISSUE TITLE
Abmeldung im Hintergrund & Speicherverweigerung bei paraller Anmeldung in 2 verschiedneen Browsern 

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/verona-modules-aspect#220]
1. in Chrome und Firefox mit dem gleichen Account angemeldet
2. in beiden Browsern die gleiche Studie geöffnet 
3. in Firefox Änderung an einer Unit vorgenommen
3. in Chrome lediglich im Editor eine andere Unit angeschaut (nichts geändert)
4. in Firefox lässt sich Änderung nicht speichern, obwohl das sonst ausgegraute Speichersymbol schwarz war, also es gab Änderungen die speicherbar hätten sein müssen
Lösung: 
Hab dann das Studio in Chrome geschlossen und nochmal in Firefox geöffnet, dort hatte er mich im Hintergrund abgemeldet (bin auf die Startseite statt auf die Studie des Lesezeichens gekommen), ich hab mich also wieder angemeldet und dann konnte ich in dem anderen Tab in Firefox meine Änderung speichern

**Comment by rhenck** [comment]
Das gehört eigentlich ins Teststudio nicht zu Aspekt. Aber wir könnens vorläufig hier lassen, damit das nicht in Vergessenheit gerät.
