### ISSUE TITLE
Fehlermeldung "Loaded outdated unit definition" verbessern

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/verona-modules-aspect#222]
![outdated.PNG](https://images.zenhubusercontent.com/62165c0e00c895796c09833e/5268e344-e09e-4e35-b0a0-4341aa846a3f)

Gestern mit Editor v 1.27 und player v 1.21 angelegte Unit wurde auf v 1.28 und 1.23 umgestellt und jedes mal beim Laden des Editor erscheint die Meldung. Was bedeutet sie?

**Comment by rhenck** [comment]
Das bedeutet, dass die Unit nicht mit aktuellen Version erstellt wurde und Dinge korrigiert wurden. Grundsätzlich also nicht weiter schlimm.
Sollte allerdings nach einmaligem Laden und Abspeichern verschwinden, weil dann alles wie gewünscht gespeichert wird.

Insofern ist das ein Bug, wenn es auch nach dem SPeichern passiert, ansonsten erwartetes Verhalten.

**Comment by rhenck** [comment]
Wenn euch die Meldung zu sehr verwirrt, kann ich die aber auch wieder ausbauen. Dachte das wäre ganz nett informiert zu werden.

**Comment by PaulineKohrt** [comment]
Nee, ist super. Nicht wieder ausbauen. Wollte nur sichergehen, dass es auch tatsächlich das bedeutet was ich dachte dass es das vielleicht tut ;)

**Comment by PaulineKohrt** [comment]
> Insofern ist das ein Bug, wenn es auch nach dem SPeichern passiert, ansonsten erwartetes Verhalten.

ja, es war auch nach dem Speichern noch einmal da, aber irgendwann auch nicht mehr...

**Comment by rhenck** [comment]
- Übersetzen
- Besserer, weniger alarmistischer Text
