### ISSUE TITLE
kurze Abschnitte löschen erschwert 

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/verona-modules-aspect#223]
![abschnitt löschen.gif](https://images.zenhubusercontent.com/62165c0e00c895796c09833e/2a979ded-5646-4238-acdc-b6dc1f8994b4)

Editor 1.28
siehe gif

**Comment by rhenck** [comment]
Ist etwas tricky zu lösen. Ich habe es nun 'gelöst', indem ich einfach permanent das Abschnittsmenu des ausgewählten Abschnitt anzeige. Kein Ein- und Ausblenden mehr.

**Comment by rhenck** [comment]
Ich packe das mal vorübergehend auf 'Klärung', falls ihr Mittwoch noch Einwände äußern wollt.
