### ISSUE TITLE
Stylingeigenschaften ändern bei der Beschriftung der MCs (Optionsfelder)

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/verona-modules-aspect#224]
Editor 1.28
Die einzelnen Zeilenoptionen können nun schon verändert werden (fett, kursiv usw.) - das ist super! 
Wir hätten das auch sehr gern für die Beschriftung (Einleitungssatz) :)

**Comment by PaulineKohrt** [comment]
und eigentlich gern auch für die Ablegelistenoptionen ;)

**Comment by PaulineKohrt** [comment]
Als Ergänzung: Hier wäre auch wichtig, dass die Zeilenhöhe des Gesamtelements auch auf die Beschriftung angewendet wird, sonst passiert u. a. das hier 

![grafik](https://user-images.githubusercontent.com/78726636/176480723-8caf4e63-461a-4869-8310-3ccd88e14756.png)

**Comment by jojohoch** [comment]
Da MCs Inputelemente sind, verfügen sie über ein Label, wie alle anderen Inputelemente auch. Wenn es Label nun ein HTML Element ist, gilt das für alle anderen Inputs auch, was technisch z.B. für Textfields und Textareas nicht möglich ist. Es müsste daher ein Umbau des Datenmodels erfolgen, was aufwändig, fehleranfällig und schwer abzuschätzen ist.
