### ISSUE TITLE
komische Auto-Vervollständigung im Texteditor 

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/verona-modules-aspect#226]
Editor 1.28
Wenn man 3. eingibt, wird es zu einem eingerücktem (als Liste formatierte) römischen III. 

![grafik.png](https://images.zenhubusercontent.com/62165c0e00c895796c09833e/731bb9ba-cd6c-4d15-8511-196966cef0de)

**Comment by rhenck** [comment]
Es wird alles derartige deaktiviert. Falls es Probleme gibt, greifen wir das nochmal auf.
