### ISSUE TITLE
Dynamsche DropLists werden auf iPad nicht immer angezeigt 

### ISSUE THREAD

**Issue by jojohoch** [iqb-berlin/verona-modules-aspect#230]

**Comment by jojohoch** [comment]
Welche iOS/Safari - Version? 
Bug lässt sich nicht reproduzieren

**Comment by tobhu1981** [comment]
Das Problem tritt wohl in Version 14.8 auf.

**Comment by tobhu1981** [comment]
Laut Aussage von Martin (https://github.com/iqb-berlin/iqb-berlin.github.io/wiki/2-Testcenter) sollen wir beim iPad die letzten beiden Hauptversionen unterstützen, also die 14 und 15. Heißt für mich, wir müssten früher oder später eine fehlerfreie Anzeige auch in der vom IBBW verwendeten Version 14.8 hinbekommen. Oder?

**Comment by tobhu1981** [comment]
Player: 1.27.0
iPad mit IOS: 15.3.1

Habe da keine Probleme mehr entdeckt.
