### ISSUE TITLE
abgerundete Ecken beim Hervorheben potenzieller Ablegelisten

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#231]
Ist in v1.28/v1.22 verloren gegangen, hätten wir aber gerne wieder. Selber Grad an Rundung wie bei den Elementen und Listen.

**Comment by rhenck** [comment]
Kann ich nicht reproduzieren. Erbitte weitere Informationen. :)

**Comment by jkoelm** [comment]
Ich kann es gerade auch nicht mehr reproduzieren, entschuldige^^
