### ISSUE TITLE
Beschriftung Optionsfelder Zeilenhöhe

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#233]
Die Einstellmöglichkeit der Zeilenhöhe bei Optionsfeldern ist in v1.28/v1.22 nicht mehr gegeben. Im Prinzip würde es uns reichen, wenn der Teil "Beschriftung" per default auf eine Zeilenhöhe von 135 gesetzt wird. Dann bräuchten wir keine Einstellbarkeit.

**Comment by rhenck** [comment]
Das nehmen wir doch nicht einfach so hin... ;)
Wenn ihr bei anderen Elementen auch Felder vermisst, sagt bescheid.
