### ISSUE TITLE
Knopf: Aktion: Aktionsparameter ohne Einträge

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/verona-modules-aspect#240]
TH: Bei Auswahl Aktion: **Unitnavigation** erscheint ein Untermenu für den Aktionsparameter. Wird als Aktion **Seitennavigation** gewählt, erscheint das Untermenu auch allerdings ohne wählbare Einträge.

**Comment by rhenck** [comment]
Da erscheinen erst Dinge, wenn es mehr als 1 Seite gibt. Ist das vielleicht schon das Problem? Wenn ja bitte mehr Details.

**Comment by rhenck** [comment]
Ungeachtet dessen. ob das tatsächlich hier das Problem ist, habe ich mal ein Tooltip angebaut, der darauf hinweist, dass dort nur Seiten erscheinen, die valide Ziele sind. Das lindert hoffentlich zukünftig Irritationen ob der leeren Liste.

**Comment by tobhu1981** [comment]
Ich hatte 2 Seite angelegt, aber die Liste war leer.  Ich kriegs aber nicht mehr reproduziert. Tooltip kann aber sicherlich nicht schaden. Dann können wir das Ticket schließen.

**Comment by tobhu1981** [comment]
Ja vielleicht war das damals Tatsache so.

**Comment by rhenck** [comment]
Dann mache ich mal zu.
