### ISSUE TITLE
Knopf: Bild laden: Ansicht bei sichtbarer Liste für die Aktionsparameter fehlerhaft

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/verona-modules-aspect#241]
TH: Wurde eine Aktion gewählt und ist die Liste für die Aktionsparmeter eingeblendet, verschiebt sich beim Bild laden die Ansicht komisch (siehe GIF).
https://box.hu-berlin.de/f/dfa30866dfb94d379cb5/

**Comment by rhenck** [comment]
Hab das ganze Buttonpanel mal überarbeitet. Sieght nun besser aus und hat das beschriebene komische Verhalten nicht mehr.
