### ISSUE TITLE
Sichtbar nach ID: Fokus erster Abschnitt 

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#242]
Wir haben eine Aufgabe angelegt, die das neue Feature in mehreren Stufen nutzt. Wenn man nun an einem Instruktionsabschnitt hängt, in dem das Audio läuft, kriegt man gar nicht richtig mit, dass darunter nach Ablauf Aufgaben auftauchen. Wäre es ggf. möglich, den neu sichtbar werdenden Abschnitt automatisch in den Fokus scrollen, wenn er auftaucht?

siehe hier: https://www.iqb-teststudio.de/#/a/98/u/3061

**Comment by jkoelm** [comment]
Funktioniert an sich, aber der Abschnitt sollte noch ein bisschen weiter nach oben rutschen. Momentan ist es so, dass er gerade so am unteren Rand erscheint. Ginge es, dass der Beginn des neu angezeigten Abschnitts ungefähr mittig auf den Bildschirm geschoben wird?

**Comment by jojohoch** [comment]
Die Beispielaufgabe hat als letztes Änderungsdatum den 26.04.2022 17:07. In meinem Quellcode kann ich shen, dass ich am 28.4.2022 hier Änderungen vorgenommen und außerdem dass das angebene Scroll-Ziel "center" ist. Ist das Ergebnis auch mit einem neueren Editor/Player nicht zufriedenstellend?

**Comment by jkoelm** [comment]
Wir hatten es uns (mit dem aktuellen Player) hier angeschaut: https://www.iqb-teststudio.de/#/a/141/u/4086 und da war das Ergebnis, dass es ruhig noch etwas höher rutschen könnte.

**Comment by jojohoch** [comment]
Es handelte sich hierbei v.a. um ein Firefox Problem.
Nun wird das neue Element nicht mehr vis in die Mitte des Bildschirms gescrollt, sondern etwas weiter - bis zum oberen Drittel.
