### ISSUE TITLE
Rahmenelement merkt sich seine Einstellungen nicht

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#243]
Ein in v1.29/v1.23 neu erstelltes Rahmenelement merkt sich nicht, wenn man Kantenradius, Kantenstärke, Kantenstil etc. einstellt.

**Comment by rhenck** [comment]
Kann ich für 1.29 bestätigen. In spätestens 1.31 klappt das bei mir.
