### ISSUE TITLE
Abschnitte, die erst nach abgespielten Audio sichtbar werden, beim zurückgehen auf Unit nur teilweise sichtbar

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/verona-modules-aspect#245]
Es ist kompliziert... 
Die Unit (https://www.iqb-teststudio.de/#/a/98/u/3061) hat u.a. im ersten Abschnitt ein Audio und erst nach dem vollständig gespielten Audio, werden die nächsten 9 Abschnitte sichtbar. Das funktioniert auch so. Aber nicht, wenn ich in einem fertig angelegten Test im Testcenter die Aufgabe einmal komplett geladen habe (alle Audios gespielt und alle Abschnitte waren sichtbar), dann zur nächsten Aufgabe gehe und dann zu dieser Aufgabe zurück gehe, dann werden nur 1,5 der vormals 9 "gesperrten" aber ja bereits sichtbar gewordenen Abschnitte angezeigt.
Aber: in der Unit haben wir auch eine versteckte Audiodatei (alle Anzeigeelemente sind ausgeblendet) die per Autostart losläuft. Evtl. ist da auch der Haken.

Hier der Test im Testcenter:
Logins als Testtaker:  r:\Deutsch\TBA\23_Haupttest 2023\1_Probeumsetzung\03_TBA-Pilotierung2022\1_Testcenter\Logins\2023-04-21_LoginsTBAinternV8Deu_Testtaker_Zossen2Verlängert.xml; 
Aufgabe in Testheft 04, Aufgabe 1 (Krabat) nach den Beispielen (Audio ist mehr als 6 Minuten lang - Geduld gefragt), 
Freigabe gesperrte Teile durch "Platzhalter Freigabewort"

**Comment by jojohoch** [comment]
Die gespeicherte Zustand dieser Aufgabe warf beim Laden der DropList einen Fehler, der vermulich dazu führt, dass die Aufgabe unvollständig dargestellt wird.

**Comment by jkoelm** [comment]
Das ursprüngliche Problem tritt nicht mehr auf. Dafür ist es jetzt so, dass 
1) nach dem Abspielen des Audios, 
2) dem kompletten Runterscrollen inkl. Eingabe von Antworten, 
3) dem Weiterklicken auf die nächste Aufgabe und
4) dem Zurückklicken auf die erste Aufgabe
nicht wie eigentlich erwartet die Items angezeigt werden (und das Audio nicht mehr abspielbar ist), sondern das Audio steht auf 3 Sekunden vor Ende und muss noch mal gestartet werden, damit die Items auftauchen. Die Antworten sind aber gespeichert.

Hier liegen Login-Daten: P:\TBA\02_Organisation\01_StuMis\04_Gemeinsamer Arbeitsordner\2_Aspect_Review_Testcenter\Logins.xml
