### ISSUE TITLE
Tablet: Android 10 mit Chrome 100: "alles ist schlimm"

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/verona-modules-aspect#249]
einen der Logins nutzen: "R:\VERA3\TBA-Deutsch\14_TBA-Pilotierung Lesen 2022\04_Testcenter\03_Logins\2022-04-27_Logins TBAintern.xml"

am Tablet angesehen ("no name") mit Android Version 10 und Chrome 100.0.4896.127

**Comment by jkoelm** [comment]
Anscheinend allgemeines Chrome-Problem, nicht nur am Tablet: 
Zeilen werden rechts abgeschnitten.
https://www.iqb-teststudio.de/#/a/98/u/2958
