### ISSUE TITLE
Maximalbreite von Elementen (v.a. dringend für MC am Tablet)

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/verona-modules-aspect#255]
aus Trello übernommen, ist jetzt recht wichtig für Pilotierung in Grundschulen am Tablet ab 25.5.

PK, JK: 22.12.2021
Es ist etwas ungünstig, dass bei Ankreuz-Aufgaben eine Antwortoption auch ausgewählt wird, wenn man rechts neben die Antwort klickt. Wenn man beim Scrollen einmal auf die weiße Fläche nach der Antwortoption geklickt hat, könnten auch Antworten ungewollt geändert werden. 
--> Mit einer Maximalbreite können wir das umgehen

FF, 16.02.
Nagut 

![grafik.png](https://images.zenhubusercontent.com/62165c0e00c895796c09833e/e441ea69-1478-4741-b80b-f7027fe628a5)

**Comment by rhenck** [comment]
Grundproblem: Elemente sind so breit wie sie können, nicht wie sie müssen.

**Comment by rhenck** [comment]
Kann ich hierfür auch ein Beispiel haben, wo das nützlich/nötig ist? Mir fehlt gerade ein Anwendungsfall, auch um eine mögliche Lösung zu testen. Das mit den Checkboxen ist m.E. nicht mehr der Fall, die kann man nur noch durch anklicken des Textes aktivieren.

**Comment by rhenck** [comment]
> 

z.B. für Ablegelisten

**Comment by rhenck** [comment]
Sanitizen!
