### ISSUE TITLE
[iPad] PresentationProgress wird nicht immer korrekt übermittelt

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/verona-modules-aspect#256]
**Betrifft:**
Aspect-Player 1.24.0 auf iPad 9 mit iOs 15 (und TC 12.1.6@12.4.0 sowie 12.1.5@12.2.3)

**Testdaten**:
Am Besten Aufgabe DSZfeedback (darf ich hier vermutlich nicht anhängen).

**Beschreibung**:
Bei manchen Units, die größer sind als der Viewport tritt manchmal ( ca 1/3 bis 1/2 aller Fälle  bei mir) das Problem auf, dass der presentationProgress nicht richtig vermeldet wird. Wenn ich ganz nach unten scrolle müsste eigentlich eine weitere vopStateChangedNotification auftauchen und presentationProgress=complete melden, das passiert aber einfach nicht. Macht man in irgendeinem Feld eine Eingabe, oder dreht man das iPad, wird auf einmal ein presentationProgress=complete vermeldet.

Dies hat dazu geführt, dass die Teilnehmer in der Studie oft nicht weiter navigieren konnten, da die navigation nur bei vollständig betrachteten Aufgaben erlaubt war.

Dieses ist ein Folgeticket vom [Testcenter Ticket #387](https://github.com/iqb-berlin/testcenter-frontend/issues/387). Die Tatsache, dass man weiter kam, wenn man eine Eingabe gemacht hat führte dazu, das zunächst eine Vermischung von presentationProgress und responseProgress vermutet wurde, doch nach Debugging mit dem iPad konnte die Erklärung im Aspect-Player gefunden werden wie oben beschrieben.

**Comment by tobhu1981** [comment]
Player: 1.27.0
IQB-Testcenter Version 13.0.0-alpha (auf Testserver)
iPad mit IOS: 15.3.1

Weiterblättern war nach vollständiger Anzeigen (Scrollen ans Ende etc.) der Aufgabe jederzeit möglich. Habe es mehrfach mit unterschiedlichen Aufgaben getestet (mit iPad Drehungen etc.). Ich denke also das Ticket kann geschlossen werden.
