### ISSUE TITLE
Items verschwinden wenn man einmal zurück geht und wieder auf Unit vorklickt

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/verona-modules-aspect#258]
In Testcenterstudie (nur Navigation des Testcenters benutzt) am Tablet (iOS15) 
bei einer Unit bestehend aus 2 Seiten verwindet die nicht festgestellte Seite wenn man zurück auf diese Unit geht (es wurde keines der Items angeklickt) - egal was man versucht, neu laden, vor- und zurückgehen, ausloggen und wieder einloggen, die Seite bleibt verschwunden

betroffene Unit: https://www.iqb-teststudio.de/#/a/119/u/2990

Wir glauben das Problem gab es schon mal, wir haben es aber nicht wiedergefunden, sorry

**Comment by PaulineKohrt** [comment]
ja, nur diese Unit war betroffen; beim ersten Laden der Unit war die Seite da, geht man dann vor auf die nächste Unit (es ist kein Presentation Complete im Booklet eingestellt) und wieder zurück, ist die Seite verschwunden; ist sowohl am iPad als auch in Firefox am PC aufgetreten

**Comment by jojohoch** [comment]
Das Problem besteht darin, dass ein Bild der Seite nicht geladen werden kann und daher einen Fehler im Code verursacht. Dies lässt sich in der Konsole im FF erkennen.
Da das Faultier zu sehen ist muss es sich entweder um den Blätter Button am Ender der Seite, oder aber um das eingebettete Bild im Text handeln. Ich vermute letzteres

**Comment by PaulineKohrt** [comment]
Ich habe beide Bilder ausgetauscht, die Unit neu hochgeladen und es nochmal versucht. Die Seite verwindet dennoch. UND: Beide Bilder sind auch in der anderen Unit im Testheft im Einsatz und verschwinden nicht.
Hier die andere Unit: https://www.iqb-teststudio.de/#/a/119/u/2988

**Comment by jojohoch** [comment]
imgSrcValue ist der Name der Variablen die den Fehler verursacht. Sie wird von der Droplist verwendet. Die Droplists in dieser Unit verwenden aber keine Bilder. Was bedeuten würde, dass prinzipiell alle Aufgaben mit Droplisten (ohne Bilder) Probleme haben müssten

**Comment by jojohoch** [comment]
Das ist tatsächlich ein Droplist Problem in den Versionen 1.30/1.24. Die letzten noch nicht veröffentlichten Änderungen haben das Problem bereits behoben.

**Comment by jojohoch** [comment]
Ich könnte in der Versionsverwaltung bis zu der Stelle zurückgehen, an der Release 1.30.0/1.24.0 erstellt wurde. Dann könnte ich auf diesem Stand den Bug fixen und einen Patch 1.30.1/1.24.1 releasen. Das funktioniert für das Studio - ob das aber auch fürs Testcenter funktioniert?
