### ISSUE TITLE
Element-Toolbox: neue Gruppierung

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/verona-modules-aspect#267]
die beiden Tools Lückentext und Wort korrigieren unter "Verbundelemente" können gern einfach mit in die Gruppe "Eingabe" wandern, denn für den Anwender ist es egal dass es noch die Spezialnutzungen von Drag&Drop-Lücken innerhalb des Lückentextes gibt, in erster Linie ist das ein Eingabeformat

**Comment by rhenck** [comment]
hier mal ein Feedback von Semiha bzgl. der Gruppierung der Elemente im Aspect-Editor.

    Die Idee mit den Gruppen finde ich gut & die Elemente sind da aus meiner Sicht übersichtlich eingeteilt. Drei der Gruppen sind automatisch geöffnet & die restlichen nicht. Ist das Absicht, um die am häufigsten verwendeten Elemente direkt zu sehen? Ein Problem wäre, wenn nicht so klar wird, dass der Rest sich auch aufklappen lässt. Für ein voreingestelltes Zuklappen würde sprechen, dass man dann von vornherein versteht (/verstehen muss), dass man alles aufklappen kann, um an Elemente zu kommen & dementsprechend wird ggf. klarer, dass es die Gruppen gibt & sich alle aufklappen lassen.
    Den Begriff "Verbundelemente" finde ich nicht so klar, vielleicht könnte man sich einen anderen Namen überlegen. Mir fällt auf die Schnelle nichts ein, denn "Orthografie" (o. Ä.) passt ja nicht ganz, wenn auch Sprachgebrauchsaufgaben einen Lückentext haben können und das vom Sinn her auch nicht so zu den anderen Gruppennamen passt (die sind ja nicht nach Kompetenzbereichen benannt). Vielleicht passen die beiden Elemente in dieser Kategorie aber auch zur Gruppe "Eingabe", was denkst du? Man gibt ja zur Lösung jeweils etwas ein. 
    "Sonstige" finde ich als Bezeichnung nicht schlecht, aber noch besser könnte "Format" o. Ä. passen. Oder kommt man dann durcheinander, weil man denkt, dass dort das Format von Elementen angepasst wird?
    Die Gruppennamen "Medium" "Eingabe" und "Auswahl" sind super.
    Ggf. könnte man das Element Ablegeliste auch in "Auswahl" verschieben, da man auch da die richtige Lösung auswählt & in einen anderen Kasten schiebt. So hätte man dann auch eine Kategorie ("(Zu)Ordnung") weniger. 
    Gut finde ich auch, dass es nicht mehr zwei Seiten mit Elementen gibt, sondern die Kategorien ein- und ausklappbar sind.
