### ISSUE TITLE
Mathematik: Bereiche Einfärben 

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#269]
Für diese Art von Aufgaben benötigen wir eine Lösung. Mit GeoGebra kann man es nicht umsetzen.

https://www.iqb-teststudio.de/#/a/97/u/2884
https://www.iqb-teststudio.de/#/a/97/u/2879
https://www.iqb-teststudio.de/#/a/97/u/2883

**Comment by jojohoch** [comment]
zu lösen über Klicks

**Comment by PaulineKohrt** [comment]
Diese Aufgabe mit den Kugeln einfärben (https://www.iqb-teststudio.de/#/a/97/u/2884) ist jetzt für den Haupttest 2023 ausgewählt und muss im Januar also abgegeben werden. Hab daher die Dringlichkeit etwas hoch gedreht...

**Comment by jojohoch** [comment]
Variante 1 (Kugeln) kann mit der neuen Komponente Bildbereiche umgesetzt werden.

Vriante 2 bzw. 3  muss gesondert umgesetzt werden

**Comment by jkoelm** [comment]
Die zweite wird sich doch auch gut damit lösen lassen, oder? Dann ohne die "Krücke" mit dem Eintragen.

**Comment by jojohoch** [comment]
Richtig. Variante 2 lässt sich auch lösen

**Comment by jojohoch** [comment]
Variante 3 lässt sich nun auch lösen. Es gibt nun auch dreieckige Hotspots

**Comment by jkoelm** [comment]
Ist super geworden!
