### ISSUE TITLE
Benennung der ersten Spalte in CMCs

### ISSUE THREAD

**Issue by jojohoch** [iqb-berlin/verona-modules-aspect#272]
Vermutlich ist die Einführung einer weiteren Label-Eigenschaft für dieses Element notwendig
JK, PK 7.2.22

uns fehlt die Erweiterung, die erste Spalte (mit den Antwortoptionen) zu benennen
manchmal nur ein Wort, manchmal ein ganzer Satz

FF, 16.2.
Beschriftung einführen wie bei MC - 10px Abstand zur Tabelle
Beschriftung2 einführen - als (erste) Spaltenüberschrift

**Comment by rhenck** [comment]
Achtung: 2 labels
