### ISSUE TITLE
Komplexe Optionsfelder mit Flex-Layouting erweitern

### ISSUE THREAD

**Issue by jojohoch** [iqb-berlin/verona-modules-aspect#273]
JK 7.2.22: Wir bräuchten das Feature auch als z. B. 4er Block unter- und nebeneinander, also z. B. zwei oder drei Bilder nebeneinander, zwei Bilder untereinander und alles der gleichen MC-Gruppe zugehörig.

FF 16.2.
Flex mit Mindestanzahl

**Comment by rhenck** [comment]
- Feste Anzahl je Zeile
- großer Abstand zwischen den Zeilen
