### ISSUE TITLE
Lückentext: Inputfeld Zeilenhöhe dynamisch ermitteln

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/verona-modules-aspect#276]

**Comment by tobhu1981** [comment]
TH: Derzeitigt hat das Inputfeld in Lückentexten eine statische Standardhöhe von 25Pxl. Sollen Buchstaben wie "j", "g" etc. nicht abgeschnitten werden, muss die Höhe auf 30Pxl erhöht werden. Besser wäre doch vielleicht eine dynamisch ermittelte Höhe: Einlesen der aktuellen Zeilenhöhe + 3Pxl für den Rand.

**Comment by rhenck** [comment]
Ist das noch aktuell? Falls ja, bräuchte mal ein Beispiel, wo irgendwas abgeschnitten ist. Ist mir gerade nicht klar, wo das Problem ist und wie die Lösung aussähe.

**Comment by rhenck** [comment]
Default auf 30
