### ISSUE TITLE
LikertRow beginnt bei der Vorbelegung mit index 1

### ISSUE THREAD

**Issue by jojohoch** [iqb-berlin/verona-modules-aspect#279]
sollte wie andere Index Elemente auch mit index 0 beginnen

**Comment by rhenck** [comment]
Bitte nochmal testen. Sollte hiermit:
c3a80aa51dcffb3b6ed8465860228c1e38d57ad2
gelöst gewesen sein.

**Comment by jkoelm** [comment]
Beginnt jetzt theoretisch mit Index 0, aber Beschriftung ist etwas kryptisch
https://www.iqb-studio.de/#/a/7/217/editor
![grafik.png](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/8c970d36-a915-4e10-89f6-bf2197c1533f)
