### ISSUE TITLE
Eingabehilfen "Ziffern & Operatoren & '='" bei Eingabebereich: Funktionserweiterung

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/verona-modules-aspect#282]
man braucht im Zahlenfeld (Eingabehilfe) noch ein Enter um Rechnungen sinnvoll darzustellen
im Eingabebereich bei der Eingabehilfe "Ziffern & Basisoperatoren", "Ziffern & Operatoren & '='"  Enter-Zeichen (button?) hinzufügen

**Comment by jojohoch** [comment]
Die Eingabehilfe dient doch lediglich dazu, die Rechnung aufzuschreiben. Sie führt die Rechnung nicht aus! Wofür wird dann ein Enter benötigt?

**Comment by PaulineKohrt** [comment]
um einen Zeilenumbruch zu erzeugen und dann stellengerecht in der nächsten Zeile eine weitere Rechnung aufzuschreiben (z. B. beim schriftlichen Addieren, Subtrahieren usw.)

**Comment by jojohoch** [comment]
Ist aber dann kein Rechenzeichen - wie die anderen Zeichen
Ließe sich nur bei Textareas umsetzen lassen.  (sollte dort aber bereits jetzt (mit Tastatur) machbar sein)
Um Stellengerecht aufzuschreiben, würde man auch noch die Eingabe von Leerzeichen benötigen.
Zur Formulierung des Ergebnisses würde man außerdem noch den Strich benötigen.

Erscheint mir eher die einfachste Version des geplanten "Formeleditors" zu sein

**Comment by PaulineKohrt** [comment]
um am Tablet ohne eine Tastatur auszukommen, ist es tatsächlich die einfache Version des Formeleditors, aber ohne Enter nicht wirklich einsetzbar. Über Leerzeichen hatten wir auch schon nachgedacht, fanden das aber doch verzichtbar (denn alles was verwendet wird, muss auch instruiert werden und je weniger instruiert werden muss, desto besser)
