### ISSUE TITLE
Fehler beim Duplizieren von MC Elementen

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#283]
v1.32/v1.25

Beim Duplizieren von MC Elementen scheint irgendwas mit der internen ID-Vergabe (?) nicht zu funktionieren. Ändert man im duplizierten Element was an einer Option, ändert es sich auch im Ursprungselement. Das ist sowohl beim Duplizieren des einzelnen Elements als auch beim Kopieren des gesamten Abschnitts der Fall.

https://www.iqb-teststudio.de/#/a/34/u/3588

Edit: Nach dem Speichern scheint sich die Kopplung aufzuheben und man kann die Optionen der MC-Elemente wieder getrennt bearbeiten.

**Comment by rhenck** [comment]
Bezieht sich nur auf die Variante mit Bild

**Comment by jkoelm** [comment]
Nein, ist auch bei der Textvariante so.
