### ISSUE TITLE
Ablegeliste: Markierung, wenn das Element schon mindestens einmal benutzt wurde

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#284]
aus Trello:

JK, PK: 10.12.2021
"Drag & Drop mit Zurücklegen" --> Elemente  mehrmals benutzen
Es sollte visuell sichtbar sein, dass man ein bestimmtes Element bereits genutzt hat, aber es sollte prinzipiell mehrmals benutzbar sein

FF, 16.2.
Markierung, dass Element schon mindestens einmal abgelegt wurde
[limitiertes wiederverwenden wird nicht implementiert (kein Zähler)]

Kommentar:
Das Kopierend er Elemente läuft, wir hätten aber noch gerne wie oben beschrieben eine Markierung, wenn das Element schon mindestens einmal benutzt wurde.

**Comment by rhenck** [comment]
Warum ist das nicht auf low prio?!

**Comment by jkoelm** [comment]
Weil es nicht low prio ist. ;)

**Comment by PaulineKohrt** [comment]
finden wir inhaltlich nun nicht mehr sinnvoll, Karte kann weg
