### ISSUE TITLE
Scrollbare Seiten benötigen visuellen Hinweis, dass durch Scrollen weitere Inhalte zu sehen sind

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/verona-modules-aspect#289]
Problem bei einer zweiseitig angelegten Aufgabe (links Text und Seite festgestellt):
Falls (1) der Lesetext sehr kurz ist und (2) auf der rechten Seite gescrollt werden muss, dann muss zusätzlichen ein Scrollbalken für die linke Seite (Mitte) erzeugen werden (derzeitiger Work-around: leeren Abschnitt unter den Text setzen). Erzeugt man diesen Scrollbalken nicht, ist nicht zweifelsfrei ersichtlich, dass es zwei Seiten der Aufgabe gibt und die Maus/der Cursor auf der rechten Seite sein muss, damit man scrollen kann. Dies betrifft hauptsächlich die Darstellung am PC / Laptop, am Tablet ist dies weniger relevant. 
Der work-around ist nicht ganz sauber, da durch verschiedene Monitorgrößen die Ansicht auch bzgl. des Scrollbalkens verändert, z. B. extrem viel white-space an kleinen Bildschirmen vs. noch kein Scrollbalken an großen Bildschirmen 

Habt ihr eine Idee für eine andere Lösung?

z. B. hier
https://www.iqb-teststudio.de/#/a/17/u/2039

**Comment by PaulineKohrt** [comment]
![grafik](https://user-images.githubusercontent.com/78726636/182628909-795db2af-5ed3-4290-ac18-efbd7a30f306.png)

**Comment by jkoelm** [comment]
Ist schon ziemlich cool! Wir hätten noch ein paar optische Verbesserungsvorschläge. Momentan sitzt der graue Pfeil ganz rechts am Rand und wird dort leicht übersehen. Könnte man ihn auch in der Mitte platzieren? Zudem wäre es schön, wenn nicht nur der Pfeil selbst eine kleine Transparenz mitbringt, sondern auch die ganze gedachte Zeile, in der er sitzt. Zuletzt wären wir dafür, statt der grauen Farbe vom Farbton her eher in die Richtung des grünen Navigationspfeils oben zu gehen, vielleicht ein bisschen blasser.

**Comment by jojohoch** [comment]
Eine gedachte hat das Problem, dass sie eventuell editierbare Flächen überdeckt
Farbe - kein Problem

**Comment by PaulineKohrt** [comment]
lieber den Pfeil nicht grün machen, eher dezent grau bleiben 
Funktion als Button kann bleiben

**Comment by jojohoch** [comment]
Button nun zentriert am Ende der Seite
