### ISSUE TITLE
Stylingeigenschaften für CMC (Optionentabelle (Likert)) - Beschriftung und Optionen

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/verona-modules-aspect#290]
wie Titel sagt, wir müssen bei den CMC-Optionen/beschriftungen tw. Kurivsetzungen oder Fettdruck vornehmen können, daher benötigen wir Texteditor mit Stylineigenschaften (bei MC - Optionsfelder geht das schon in den Optionen, nicht jedoch in der Beschriftung, dazu gibt's nen anderes Ticket #224 schon)

**Comment by rhenck** [comment]
Für die Spalten (bei uns als Optionen bezeichnet) geht das schon.

Das wird nur noch für die Zeilen benötigt.
