### ISSUE TITLE
Element "Linie"

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#291]
Wir hätten gerne ein Element "Linie", bei der man die gleichen Eigenschaften wie beim Rahmen einstellen kann.

(Momentan müssen wir den Rahmen in eine 1 px große Spalte oder Zeile im Grid zwingen, um das gewünschte Resultat zu erreichen, und das ist relativ umständlich)

**Comment by rhenck** [comment]
Rahmen-Element mit ausblendbaren Borders

**Comment by jkoelm** [comment]
v1.33.2/v1.26.2

Funktioniert noch nicht wie es soll.
Ich habe 3 textfelder angelegt. In Spalte 1 Zeile 1 habe ich einen Rahmen darüber gelegt und die Haken bei allen bis auf die untere Kante entfernt. In der Vorschau wird der ganze Rahmen gezeigt, im Editor sind die Haken danach wieder gesetzt.
Das gleich passiert, wenn ich den Rahmen in eine leere Grid-Zelle lege und die entsprechenden Haken entferne.
https://www.iqb-studio.de/#/a/7/16/preview

**Comment by jkoelm** [comment]
Die Beschriftung der Häkchen für oben und unten ist vertauscht, sonst funktioniert es gut.
