### ISSUE TITLE
Ablegeliste Lückentext Elemente kopieren

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#292]
v1.32/v1.25
Momentan funktioniert die Einstellung "Elemente kopieren" (für Mehrfachverwendung der Elemente einer Ablegeliste) nicht, wenn man Elemente aus einer normalen Ablegeliste in einen Lückentext legt.

**Comment by jkoelm** [comment]
Ergänzung: Auch wenn die Startliste in einem Lückentext sitzt, lassen sich die Elemente nicht kopieren.

**Comment by rhenck** [comment]
Sollte sich mit dem Rework erledigt haben. Nochmal in der nächsten Version überprüfen, bitte.
