### ISSUE TITLE
Leerzeile im Lückentext löscht Aufgabe

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#293]
v1.32/v1.25

Fügt man eine Leerzeile in einen Lückentext, wird die Aufgabe gelöscht.

https://www.iqb-teststudio.de/#/a/34/u/3682

**Comment by rhenck** [comment]
Ich meine dieses Problem bereits in einer früheren Version gelöst zu haben und kann es auch gerade nicht mehr reproduzieren.

Die Beispielaufgabe darf ich nicht sehen. Bitte wenigstens mal sagen, wie der Arbeitsbereich heisst, damit ich mich selbst freischalten kann.
Alternativ können wir einen gemeinsamen Bereich schaffen, wo ihr problematische Aufgaben ablegt.

**Comment by jkoelm** [comment]
Das Beispiel liegt im TBA-Probierbereich. Ich dachte, darauf hättet ihr Zugriff.
