### ISSUE TITLE
Ablegelisten im Lückentext -- dynamische Breite

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#296]
Für Ablegelisten im Lückentext wäre es praktisch, wenn sich die Breite dem Inhalt anpassen würde, den man in das Feld packt. Dann könnte man beispielsweise bei dieser Aufgabe zu Beginn eine bestimmte (Mindest-)Breite einstellen (bei allen die gleiche, um keine Antworten vorzugeben) und wenn man einen längeren oder kürzeren Satz reinpackt, wird die Ablegeliste so lang/breit wie sie muss (inkl. Umbruch).

https://www.iqb-teststudio.de/#/a/128/u/3695

**Comment by PaulineKohrt** [comment]
hier ein Beispiel für was wir das brauchen: https://www.iqb-studio.de/#/a/31/203/preview

**Comment by PaulineKohrt** [comment]
dies wäre so eine Sache auf die wir derzeit warten ;)

**Comment by rhenck** [comment]
Beispielaufgabe kann ich nicht aufrufen. Berechtigung?

**Comment by PaulineKohrt** [comment]
Hab euch nun dafür freigegeben

**Comment by rhenck** [comment]
Das funktioniert meinem Testen nach. Keine Ahnung wie lange schon... :)
