### ISSUE TITLE
Player sendet zu häufig seine Änderungen

### ISSUE THREAD

**Issue by jojohoch** [iqb-berlin/verona-modules-aspect#299]
Aufgaben mit vielen Elementen führen zu einer Belastung des Traffics

**Comment by tobhu1981** [comment]
es sind nun deutlich weniger Serveranfragen bei Aufgaben mit Lückentexten. Es läuft alles flüssiger und auch schnelles Scrollen führt trotzdem zu presentation complete und man kann weiterblättert. Du meintest mal, dass du eine vorgefertigte Funktion verwendest um bzgl. presentation complete zu prüfen. Dazu noch eine Frage: Es scheint jetzt so flüssig zu laufen, dass selbst wenn ich den Vertikalschieber in einer langen Aufgabe mit einmal von oben nach unten schiebe presentation complete gemeldet wird. Für meine alten Augen :-) wäre das aber zu schnell, um tatsächlich noch die Inhalte zu sehen. Mein Hirn würde hier nicht presentation complete melden. Da bin ich mir aber nicht sicher, ob das jetzt noch ein Problem ist oder nicht. Sowiet ich dich verstanden habe, kannst du da eh wenig einfluss nehmen.
