### ISSUE TITLE
Validierungen und Default Values

### ISSUE THREAD

**Issue by jojohoch** [iqb-berlin/verona-modules-aspect#3]
ElementModel sollte um **Validierungsproperties** erweitert werden:

- Textfeld: required, minLength, maxLength (evtl. pattern)
  -  mehrzeilig: evtl. minLines, maxLines
- Dropdown: required
- Checkbox: required, requiredTrue
- Optionsfeld: required

Zusätzlich sollte es zu jeder Validierung eine entsprechende Message geben. 
z.B. requiredMessage: "Der Wert muss angegeben werden".

ElementModel sollte um **Default Values** erweitert werden:

- Textfeld: beliebiger String
- Dropdown: Value der Option oder Index der Selection
- Checkbox: True oder False
- Optionsfeld:  Value der Option

Es könnte eine allgemeine Einstellung geben mit der entschieden wird, ob Validierungen bereits beim Betreten der Seite oder erst nach Verlassen des Elements angezeigt werden

**Comment by rhenck** [comment]
> Zusätzlich sollte es zu jeder Validierung eine entsprechende Message geben.
> z.B. requiredMessage: "Der Wert muss angegeben werden".

Ist sowas nicht Sache des Players? Weiß nicht, ob es sinnvoll ist, sowas schon vorher festzulegen.

**Comment by rhenck** [comment]
Checkboxbelegung im Urzustand müssen wir noch mit Martin und weiteren klären. Das ist Geschmackssache.
