### ISSUE TITLE
DnD: Vorschaubox überlappt Zielfeld

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#303]
v1.32/1.25
Die graue Vorschaubox bei den DnD Elementen überlappt das Zielfeld. Das sieht ziemlich hässlich aus.

**Comment by jkoelm** [comment]
v1.33/v1.26

Es scheint so zu sein, dass die Vorschaubox nun irgendwie zu hoch ist. Wenn man ein Element in die Liste ziehen will, erscheint vor dem eigentlichen Ablegen ein Scrollbalken innerhalb der Ablegeliste.
![grafik](https://user-images.githubusercontent.com/71453936/189853948-76444350-2a8c-4b1e-926e-574890c8eec1.png)

**Comment by jkoelm** [comment]
https://www.iqb-studio.de/#/a/4/6/editor

**Comment by jkoelm** [comment]
Das oben beschriebene Problem mit den Scrollbalken ist behoben, allerdings bringt die neue Version auch wieder ein paar Schwierigkeiten mit, diesmal bei "horizontal dynamisch" eingestellten einzeiligen Ablegelisten, wo die Elemente beim Rausnehmen oder  Zurücklegen eines anderen Elements auf eine wilde Wanderung gehen (siehe Screenshots)
![grafik.png](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/da571abc-8a41-491b-8570-fac4d344e6ee)
![grafik.png](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/9c03b1e0-a652-4b8d-8f8a-987073b0f377)

https://www.iqb-studio.de/#/a/7/336/preview

**Comment by jojohoch** [comment]
Nach einigen Stunden des erfolglosen Versuchs, die ganzen Pronbeme zu lösen, mache ich den Vorschlag das Stylen der Vorschau  abzuschalten. Auch dann sie die Ergebnisse nicht perfekt, aber vielleicht besser.
