### ISSUE TITLE
DnD: Verdrängen von Elementen

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#305]
Mit einem neuen Element sollte man ein bereits platziertes Element wieder zurück in die Anfangsliste schieben. Beim Mouseover wird bereits visualisiert, dass das vorher dort platzierte Element in die Ausgangsliste fliegt, aber erst bei Loslassen der Taste passiert das dann wirklich, oder eben nicht, wenn man das Element dann doch woanders hinzieht.

**Comment by rhenck** [comment]
"Mit einem neuen Element sollte man ein bereits platziertes Element wieder zurück in die Anfangsliste schieben."
Gleiches Problem, wie schon in anderen Tickets dazu: Ein Element weiß nicht wo es mal herkam.

Den Rest verstehe ich nicht.

**Comment by jojohoch** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Aspect-Module-62d7c6128090350020ba3e6d/issues/iqb-berlin/verona-modules-aspect/305?planning-poker) with Zenhub @rhenck
