### ISSUE TITLE
Hochgestellte Ziffern und Fettdruck schwer lesbar

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#306]
Die hochgestellte 3 sieht in Fettdruck sehr gequetscht aus und lässt sich schwer lesen.

**Comment by rhenck** [comment]
Finde ich nicht. :) Haste mal nen Beispiel?

**Comment by jkoelm** [comment]
Klar! :) https://www.iqb-teststudio.de/#/a/72/u/2320 (Sek I Mathematik: V8-23 Mathematik Probeumsetzung)

**Comment by rhenck** [comment]
Ihr habt das Hochstellen über Tastatureingabe verwendet. Ich habe immer über das Hochstellen via Editor-Knopf getestet. Deswegen die Diskrepanz.

**Comment by rhenck** [comment]
Eingabe von Hochstellung via Tastatur unterbinden.

-> superscript fontSize entfernen

**Comment by rhenck** [comment]
Das Unterbinden der Eingabe via Tastatur scheint nicht so einfach zu sein. Ich schätze mal das ist eh verzichtbar und daher spar ich mir die Mühe stundenlang zu versuchen, das hinzubekommen.
