### ISSUE TITLE
Optionentabelle: Fixierte Spaltenüberschrift

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#311]
Bei längeren CMC-Aufgaben scrollt man sich die Spaltenüberschriften weg. Es wäre schön, wenn die Spaltenüberschriften über der CMC kleben bleiben würden, ähnlich den Markierbuttons bei Lesetexten.

**Comment by PaulineKohrt** [comment]
Wenn das auch für Ablegelisten gehen würde, sodass die Startliste an einem Text hängt und schwebend mitwandert wenn man scrollt, wäre das super

**Comment by rhenck** [comment]
Habe grade mal versucht mir anzuschauen, wie die Markierbuttons bei Lesetexten funktionieren. SO richtig bekomme ich es nicht hin, die scrollen immer nur ein kleines Stück mit. habt ihr mal eine Beispielaufgabe für mich, wo man das mal in Aktion sehen kann?

**Comment by jojohoch** [comment]
Es gibt offensichtlich bei den Markierbuttons einen Bug: Die "Klebefunktion" funktioniert wie sie soll bei immer sichtbaren Seiten.

**Comment by jkoelm** [comment]
Hier z. B.: https://www.iqb-studio.de/#/a/54/2139/preview

**Comment by rhenck** [comment]
> Hier z. B.: https://www.iqb-studio.de/#/a/54/2139/preview

Danke. Hatte sich inzwischen allerdings erledigt. Wir hatten einen Bug, der verhindert hat, dass ich das am Text-Element nachvollziehen konnte. Der ist inzwischen behoben. Und das Feature ist für "Likert" bereits (vorläufig) fertig.

**Comment by jkoelm** [comment]
Funktioniert an sich, aber wir hätten für diese haftende Zeile gerne noch einen weißen Hintergrund. Vielleicht nicht als kompletten undurchsichtigen Riesenblock, sondern nach oben und unten hin leicht transparent?

**Comment by jkoelm** [comment]
besprochen in FF: man kann dem gesamten Element eine Hintergrundfarbe geben, das sollte uns erstmal reichen.
