### ISSUE TITLE
Concat-scroll-snap Modus benötigt visuellen Hinweis, wenn weitere Seiten vorhanden sind 

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#314]
Beim concat-scroll-snap Modus wäre es wichtig, dass visuell schon angedeutet wird, dass es unten weiter geht, beispielsweise könnte die erste Zeile der nachfolgenden Teilaufgabe / Seite unten etwas blass eingeblendet werden und/oder ein dynamischer Pfeil nach unten erscheint unten auf der Seite (der sollte dann im Zweifel auch weiter nach unten schicken, wenn man dort drauf klickt).

**Comment by jojohoch** [comment]
s. #289

**Comment by jojohoch** [comment]
Button nun zentriert am Ende der Seite
