### ISSUE TITLE
Funktionserweiterung Eingabefeld/Eingabebereich

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/verona-modules-aspect#320]
Icon einer kleinen Tastatur soll zu Beginn (wenn man das Feld noch nicht angeklickt hat) in leerem Eingabefeld/Eingabebereich sein, sodass klar ist, dass dort reingetippt werden muss. Position immer vorne links. Dies Icon sollte optional ein- und ausgestellt werden können. Und wenn man reinschreibt bzw. ggf. auch schon beim reintippen/klicken verschwindet das Icon.

**Comment by jojohoch** [comment]
Laut Material gehört ein solches Icon, das beschreibt wie das Feld befüllt werden soll, nicht nach vorne, sondern nach hinten: https://m2.material.io/components/text-fields#anatomy. So kenne ich es auch. Allerdings würde es dort bei Eingabefeldern mit dem optionalen "Knopf zum Leeren" kollidieren.
