### ISSUE TITLE
neues Studio: ID-Probleme der Elemente

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#333]
Bei im neuen Studio angelegten Elementen lässt sich die ID nicht ändern.
Die intern vergebene ID taucht außerdem nicht im Bereich Kodierung auf. Das funktioniert nur bei im alten Studio angelegten Elementen, ist aber sehr wichtig.
Beim Duplizieren von im alten Studio angelegten Elementen wird eine neue interne ID vergeben, die dann auch wieder nicht im Kodierungsreiter auf.

**Comment by jkoelm** [comment]
Kann jemand das Ticket bitte in das richtige Studio-Repository schieben?

**Comment by mechtelm** [comment]
Nee das war ein Aspect-Problem.
