### ISSUE TITLE
Ablegeliste: Vorbelegung nicht gemerkt

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#336]
Bei der Umstellung von Version 1.32/1.25 auf 1.33/1.26 geht bei Ablegelisten die Vorbelegung verloren
 ![grafik.png](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/601b3c60-0ae6-4068-8f4e-d8e49449ceee)

**Comment by rhenck** [comment]
Hier brauche ich auch mal die Aufgabe dazu. Kanns nicht selbst reproduzieren.

**Comment by jkoelm** [comment]
https://www.iqb-teststudio.de/#/a/34/u/3889
