### ISSUE TITLE
falsche Eingabehilfe angezeigt

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#345]
v1.33/v1.26

Bei den mathematischen Eingabehilfen kommen immer nur die Ziffern, auch wenn man Ziffern und Operatoren einstellt. 
https://www.iqb-teststudio.de/#/a/73/u/3869

**Comment by jojohoch** [comment]
![Screenshot from 2022-10-05 10-13-14](https://user-images.githubusercontent.com/25353300/194013146-dd80e302-5769-48e6-85ed-e6091beed932.png)

lässt sich nicht reproduzieren
