### ISSUE TITLE
Alternative zur Zeilennummerierung 

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#347]
Hatten wir schon ein paar mal andiskutiert, jetzt brauchen wir es definitiv. Es geht um eine Alternative zur Zeilennummerierung in Lesetexten, um in einem Item auf einzelne Abschnitte innerhalb des Lesetextes verweisen zu können. Bisherige Ideen waren, das statt über Zeilennummern durch Hyperlinks oder Hervorhebungen abzubilden.

**Comment by jojohoch** [comment]
Wie wollen wir das konkret umsetzen?

**Comment by PaulineKohrt** [comment]
z.B. Im Splitscreen von Deutschaufgaben mit links Lesetext und rechts Items wir in einem Item nach einer Textstelle im Lesetext (ehemals mit Verweis auf die Zeilen 2-5) gefragt. Und statt auf die Zeilennummern zu verweisen, wird im Lesetext die entsprechende Stelle farblich hervorgehoben wenn man im Item auf den Verweis klickt. Dafür müsste man im Item eine Art Link einfügen können, der auf bestimmte Zeichen (von Zeichen xx bis Zeichen yy) im Text verweist - oder so ähnlich ;)

**Comment by jkoelm** [comment]
Vielleicht auch schon bei Mouseover über diesen "Link"? Farbe sollte sich von den Farben zum Markieren unterscheiden.

**Comment by PaulineKohrt** [comment]
Habe auch zuerst an Mouseover gedacht, aber je nachdem wie lang der Text ist und wohin der gerade gescrollt ist - sieht man das ja dann gar nicht

**Comment by PaulineKohrt** [comment]
FF: der Knopf wird in seiner Funktion erweitert, sodass er Textteile hervorhebt (oder das der vorhandene Text grau wird). Bestehende Markierungen können kurzzeitig aufgehoben werden, sollen aber danach wieder sichtbar sein. Die hervorzuhebende Textstelle kann durch "Anker/Marker" (Anfang/Ende) festgelegt werden.

**Comment by rhenck** [comment]
War erwartbar, dass das Anliegen kommt. Vermutlich fehlte die Zeit.

**Comment by jojohoch** [comment]
Hierfür brauchen wir eine Priorisierung.
