### ISSUE TITLE
Formeleditor aka Textfeld mit Mathe

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#351]
Für zwei Anwendungszwecke:
1. als Eingabehilfe für Schüler*innen
2. zum Anlegen der Aufgaben 

Für 2. bräuchten wir nur einen kleinen Teil der unten aufgeführten Zeichen (eigentlich fehlen uns nur wenige Sonderzeichen und vor allem die Möglichkeit, Brüche untereinander zu schreiben), daher wäre noch mal zu überlegen, ob ein Formeleditor für beide Anwendungszwecke genutzt wird, oder ob das getrennte Sachen sind.

Funktionsumfang (Liste mit Unicode und LaTeX): [https://app.zenhub.com/files/358306669/909be190-98c4-4f3d-87e6-e0643ac76e44/download](https://app.zenhub.com/files/358306669/909be190-98c4-4f3d-87e6-e0643ac76e44/download)

https://de.wikipedia.org/wiki/Liste_mathematischer_Symbole
Vielleicht relevant?: https://de.wikipedia.org/wiki/Mathematical_Markup_Language

Zur Inspiration die Anordnung in GeoGebra:
![Eingabehilfe_Geogebra1.png](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/de6d68ae-b0c8-436f-8061-6ad6bbda9305)
[![Eingabehilfe_Geogebra2.png](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/bd60ccb1-de98-4e53-830f-0a5a52ab4e72)
![Eingabehilfe_Geogebra3.png](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/fc3d125d-2575-40d3-a308-0c5f816b23a1)
![Eingabehilfe_Geogebra4.png](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/9ce431c3-b8d0-4438-bba9-3a0376adb455)

**Comment by rhenck** [comment]
Hierzu müssen wir uns mal unterhalten, wie das mit der Eingabe genau laufen soll.
Möglichkeiten:
- Knopfleiste mit Menus
- Mathlive Tastatur in Keypad zwingen (dazu ist, wider Erwarten, viel CSS-'Hacking' nötig)
- Mathlive-Tastatur as is (unten am Rand)

**Comment by jkoelm** [comment]
Die Mathlive-Tastatur überdeckt das Eingabefeld

**Comment by jkoelm** [comment]
Ich hab noch nicht verstanden, wie das Feature den zweiten Anwendungsfall (s. o.) abdecken kann (insb. Bruchdarstellung).

**Comment by jojohoch** [comment]
Kombi aus tiptap und Mathlive oder leichtgewichtiger? contenteditable div mit math live oder eigenem formeldesigner

**Comment by jkoelm** [comment]
Bereich, 2 Zeilen voreingestellt: wenn ich nach einer Zeile Enter drücke, landet der Cursor unterhalb des Feldes (auch wenn die Zeile zu lang wird ohne Enter drücken, also der automatische Umbruch)

**Comment by jkoelm** [comment]
Aspect Beta 2.1
Im Formel-Bereich kann man die Zahlen der eingeblendeten Tastatur nicht benutzen, über denen am Anfang das Feld zur Eingabe liegt - auch nicht, wenn man das Feld zur Eingabe verschiebt. Es funktionieren nur 7, 4, 1, 0, und der ganz unterste Rand der 2 und 3.

**Comment by jkoelm** [comment]
Aspect Beta 2.1
- Bei der eingeblendeten Tastatur im Reiter ABC verschieben sich beim Drücken der Hochstelltaste die Zeilen.
- Die Pfeiltasten auf der eingeblendeten Tastatur haben keine Funktion
- Wäre es möglich, einen Automatismus der Anpassung der Schriftgröße so zu programmieren, dass man bei der Eingabe eines Doppelbruches nicht auf Schriftgröße "6" (oder so...) runterfällt? Es wird sehr klein sobald man einen Doppelbruch eingibt.

**Comment by rhenck** [comment]
"Die Pfeiltasten auf der eingeblendeten Tastatur haben keine Funktion"

Die hatten noch nie eine Funktion oder? Ich nehme an, dann können die weg.

**Comment by rhenck** [comment]
"Bei der eingeblendeten Tastatur im Reiter ABC verschieben sich beim Drücken der Hochstelltaste die Zeilen."

Kann ich nicht reproduzieren

**Comment by rhenck** [comment]
Mach mal bitte aus den letzten beiden von mir kommentierten Sachen ggf. eigene Tickets. Der Rest hier ist nämlich erledigt.

**Comment by jkoelm** [comment]
Habe die beiden Sachen als separate Tickets angelegt.
