### ISSUE TITLE
iPad: Audio: Lautstärke lässt sich nicht regeln

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/verona-modules-aspect#356]
iPad mit IOS 15.3.1
Aufgabe mit Audio in Playerversion 1.27.0

---
Die Lautstärke lässt sich auf dem iPad nicht einstellen. Der Balken springt hin und her und verbleibt nicht dort wo man es haben möchte.

Hier ein Video: https://box.hu-berlin.de/f/84777e6bd89e4fa1892f/

**Comment by jkoelm** [comment]
Aspect 2.0 Beta 3
Der Schieberegler lässt sich zwar bedienen, das hat aber keinen Effekt auf die Lautstärke des Audios.

**Comment by jojohoch** [comment]
uups

**Comment by jkoelm** [comment]
Safari Browser, iPad 9. Generation, Softwareversion 15.4.1

**Comment by jojohoch** [comment]
"On iOS devices, the audio level is always under the user’s physical control. The volume property is not settable in JavaScript. Reading the volume property always returns 1."

https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html#//apple_ref/doc/uid/TP40009523-CH5-SW10
