### ISSUE TITLE
IDs der Eingabefelder im Lückentext

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#361]
Wenn man im Lückentext ein Eingabefeld hinter ein Aufzählungszeichen setzt und das Lückentextelement dann dupliziert und einmal in die Vorschau geht, kommt danach im Editor die Fehlermeldung "Doppelte IDs gefunden: text-field-simple_2" aber man kann dann nichts mehr speichern, z. B. wenn man einen neuen Abschnitt anlegt, bleibt der "speichern"-Button deaktiviert/grau.
https://www.iqb-studio.de/#/a/7/692/editor

**Comment by rhenck** [comment]
Ich habe damals überlegt, ob ich die Option für Listen und die ganzen anderen Spezialformatierungen drin lasse oder sicherheitshalber rausnehme, als ich den Lückentext-Editor-Dialog angepasst habe. Ich wollte nicht dafür garantieren, dass sowas, wie das hier beschriebene, geht. Ich dachte ihr könnt verantwortungsvoll damit umgehen, aber scheinbar nicht! :D Lösung: Listen in Lückentexten werden wie geplant entfernt.
