### ISSUE TITLE
GeoGebra Aufgabe ist sehr langsam

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/verona-modules-aspect#362]
Aufgabe:
https://www.iqb-studio.de/#/a/39/375/preview

**Comment by jojohoch** [comment]
Da wir den gesamtem Zutand einer Geogebra-Datei bei jeder Änderung festhalten ist der Player bei dieser Aufgabe überfordert.
Auffällig ist, dass der Kreis performanter ist als die anderen Elenente.

**Comment by jojohoch** [comment]
Das Problem bestand darin, dass während des Ziehens von Elementen, permanent der gesamte Zustand der Datei ausgelesen und dem Player mitgeteilt wurde. Jetzt passiert das nur noch am Ende einer Aktion.

**Comment by jojohoch** [comment]
Außerdem wird während des Ladens eine Animation angezeigt
