### ISSUE TITLE
Aufgabenelemente werden nicht gespeichert

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/verona-modules-aspect#364]
:information_source: Dieses Ticket wurde anfangs im Studio angelegt, nach der Antwort von Martin wurde es dann hierher verschoben.

Bei allen verfügbaren Version kleiner als  **editor/1.33.0+player/1.26.0** funktioniert machmal das Speichern nicht. Sprich man fügt ein Element hinzu, aber der Speicherbutton wird nicht aktiv. Vielleicht hat es was mit deinem letzten Umbau zu tun? Ab **editor/1.33.0+player/1.26.0** scheint es dann wieder zu funktionieren.

**Comment by rhenck** [comment]
Sind wir uns einig, dass wir an den alten Versionen nicht rumpatchen oder bestehst du darauf?

**Comment by mechtelm** [comment]
Ja ich bestehe darauf, dass wir an alten Versionen nicht rumpatchen. Wenn ein Problem mit einer neuen Minor gelöst wurde, dann wurde es gelöst. So gesehen sollten wir Units prinzipiell nur mit den aktuellsten Versionen prüfen, sobald es Probleme zu geben scheint.

**Comment by rhenck** [comment]
Klare Ansage. Ich mache zu.
