### ISSUE TITLE
Eurozeichen als Eingabehilfe

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/verona-modules-aspect#365]
Mathe Grundschule benötigt ein €-Zeichen als Eingabehilfe, da es auf der Tastatur sowohl am PC als auch am Tablet zu schwer zu finden ist.

**Comment by jojohoch** [comment]
Eine Eingabehilfe mit nur einem Zeichen? 
Oder wollt ihr "€" als zusätzliches Zeichen bei den Eingabehilfen mit Zahlen?

**Comment by jojohoch** [comment]
Die alten Eingabehilfen bleiben bestehen, denn sie haben ja ihre Daseinsberechtigung und sind layoutet.
Zusätzlich gibt es die Möglichkeit eines Benutzerdefinierten Sets, bei dem die einzelnen Buchstaben eingegeben werden können
