### ISSUE TITLE
Verhalten und Meldungen bei Minimallänge und Maximallänge von Eingabefeldern verfeinern 

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/verona-modules-aspect#366]
Derzeit kann man ja einstellen, dass in einem Eingabefeld eine bestimmte Anzahl von Zeichen reindürfen. Wenn man drüber oder drunter kommt, gibt es eine Warnmeldung, die man auch anpassen kann. 
Diese Warnmeldung kann man aber nicht löschen, sodass beispielsweise nur das Feld rot umrandet wird wenn man zu viele oder zu wenig Zeichen eingibt und es keine Rückmeldung dazu gibt was falsch ist - ist das ein Bug oder gewollt so?

Eine andere Sache diesbezüglich... wenn man eine Maximallänge von 1 einstellt und man trotzdem mehr Zeichen eingibt, erscheint derzeit die Warnmeldung - die vom Layout her - da sie viel Text hat, je nach Größe des Eingabefeldes gar nicht angezeigt werden kann. (z.B. bei dieser verrückten Verwendung von Eingabefeldern: https://www.iqb-studio.de/#/a/45/747/preview
Unser Vorschlag wäre nun, dass man optional zur Warnmeldung einfach mit einer neuen Eingabe die alte überschreibt. 

ODER: Für diese Rechenkästchen finden wir eine andere Lösung, sodass Schüler*innen stellengerecht schreiben untereinander  schreiben können

![grafik.png](https://images.zenhubusercontent.com/62165c0e00c895796c09833e/75338906-1af4-4ee2-9ebf-6321566def31)

**Comment by jojohoch** [comment]
Das die Warnmeldungen nicht ausgeschaltet werden können, war ein Bug. Bei 'leeren' Warnmeldungen erscheint nun nur der rote Rahmen, d. h. es entstehen keine Scrollbalken.

Die Beschreibung/Wunsch des Überschreibens von Warnmeldungen müsste genauer gefasst werden.

**Comment by jojohoch** [comment]
Ist das Anlegen solcher Aufgaben nicht deutlich aufwendiger als das Anlegen von Aufgaben mit mehreren zusammengehörigen Checkboxes - für die es den expliziten Featurewunsch gibt? Sollte es daher nicht vielmehr einen höher priorisierten Featurewunsch hierfür geben?

**Comment by PaulineKohrt** [comment]
FF: Überschreibmodus für Textfelder bei Erreichen der Maximalanzahl --> eher verworfen, da besser, dass man einfach keine weiteren Zeichen eingeben kann bei Erreichen der Maximallänge und man muss löschen um etwas neues einzutragen
