### ISSUE TITLE
Rückgängig im TextEditor wieder anschalten

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/verona-modules-aspect#369]

**Comment by jkoelm** [comment]
Funktioniert nicht in 1.35.0/1.38.0

**Comment by rhenck** [comment]
Hm ich bin mir sicher, dass es zwischendurch mal funktioniert hat, aber bekomme es auch nicht mehr hin. Ich packe mal eine Erweiterung dazu, die das können sollte. Hat hoffentlich keine unerwünschten Nebeneffekte.
