### ISSUE TITLE
Überarbeitung wann change/touched events generiert werden

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/verona-modules-aspect#372]
Eingabeelemente könnten ihren Wert erst melden, wenn die Eingabe abgeschlossen ist, also z.B. wenn das Feld den Fokus verliert. Damit hätte man potentiell weit weniger "valueChanged" events und daraus folgende API calls.

Hierzu ist zu überlegen, inwieweit das Einfluss auf die Validierung, "isTouched"-Marker und Auswertungsmöglichkeiten (Logging) hat.

**Comment by mechtelm** [comment]
Sehr schwierig: Wenn ein längerer Text geschrieben wurde und dann - aus welchen Gründen auch immer - ein Reload der Seite ausgelöst wird, ist die Antwort verloren. Besser: Changes buffern.

**Comment by jojohoch** [comment]
Imanente Annahmen überprüfen:
wann und unter welchen Bedingungen  wird focuslost ausgeführt?
Changes-Buffer ist bereits implementiert, allerdings mit kleiner Zeit

**Comment by rhenck** [comment]
Begeben uns nicht ohne Not in potentielle Schwierigkeiten -> zu
