### ISSUE TITLE
Erweiterung von "sichtbar nach"

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#373]
Wir bräuchten zum Anlegen der Deutsch Sek I Zuhören Aufgaben noch eine Featureerweiterung. Je nachdem, was einfacher wäre
entweder
- Abschnitt sichtbar nach Audio + einstellbare Verzögerung
oder
- Abschnitt sichtbar nach anderem Element (z. B. Eingabefeld mit regular expression-Verifizierung)

**Comment by jkoelm** [comment]
https://www.iqb-studio.de/#/a/35/928/preview
Arbeitsbereich VERA DeS: 2023 Haupttest

**Comment by jojohoch** [comment]
Variante 1

**Comment by jkoelm** [comment]
Der verzögert auftauchende Abschnitt rutscht nicht in den Fokus - könnt ihr das noch umsetzen?

**Comment by jojohoch** [comment]
guck ich mir an, warum das nicht funktioniert. ist nämlich umgesetzt

**Comment by jkoelm** [comment]
Funktioniert in 1.35.2 und 1.28.2 noch nicht

**Comment by jojohoch** [comment]
Stimmt. Zu früh verschoben. Kommt erst beim nächtsten Release.

**Comment by jkoelm** [comment]
Es gibt Probleme im Testcenter: Alle Abschnitte die **direkt** nach einer Audiodatei angezeigt werden sollen, werden auch dann noch angezeigt, wenn man auf der nächsten Unit war uns wieder zurück geht (so soll es sein). Aber: Alle Abschnitte die **verzögert** (z. B. nach 90 Sekunden nach Audio) gezeigt werden sollen, erhalten erneut diese Verzögerung, erscheinen dann also z. B. 90 Sekunden nach Wiederaufrufen der Seite. Sie sollten aber beim Zurückgehen sofort sichtbar sein, wenn sie vorher schon sichtbar waren.

**Comment by jojohoch** [comment]
Oha. Stimmt. Das ist ein komplexes Problem, da keine Information abgespeichert wird, aus der sich  da gewünschte Ergebnis herleiten lässt

**Comment by jkoelm** [comment]
1.36/1.29
Beim Wechseln zwischen units funktioniert jetzt alles wie es soll.
