### ISSUE TITLE
geschützte Leerzeichen in Antwortmöglichkeiten bei MC-Aufgaben

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/verona-modules-aspect#374]
geschützte Leerzeichen in Antwortmöglichkeiten bei MC-Aufgaben (Optionsfelder) führen zu Fehlermeldungen und Aufgaben lassen sich dann nicht ins Testcenter laden

wir haben leider kein Beispiel, weil wir es beheben mussten um die Aufgabe (im Center) abgeben zu können

**Comment by rhenck** [comment]
Also die Beschreibung ist schon arg dünn... Wo und wann kamen denn Fehlermeldungen? Was sagten die aus?

**Comment by helfjama** [comment]
Die Fehlermeldung kam beim Hochladen der xml-Datei einer Aufgabe mit MC-Elementen, bei der geschützte Leerzeichen in den Antwortmöglichkeiten verwendet wurden. Das Testcenter mochte anscheinend den html-code 'nbsp' nicht, der direkt in der xml auftaucht wenn er in den Antwortmöglichkeiten verwendet wird.
Ich habe hier mal eine neue Aufgabe mit geschützten Leerzeichen in den Antwortmöglichkeiten angelegt: https://www.iqb-studio.de/#/a/58/1347/editor.
Beim Hochladen ins Testcenter habe ich wieder denselben Fehler bekommen: 
![grafik](https://user-images.githubusercontent.com/78479216/203495953-335de797-505a-45f4-bd34-ef6f4713578e.png)
Ist die Beschreibung so ausreichend? Ansonsten zoome mich gerne einfach an

**Comment by jojohoch** [comment]
Es wird nun lediglich der TextContent von Labels der Variables übermittelt

**Comment by PaulineKohrt** [comment]
Bedeutet dies, wir haben nun keine Möglichkeiten mehr Text in MC-Optionen einzurücken (z.B. um stellengerechtes Schreiben von Termen in MC-Optionen zu ermöglichen). Das wäre für uns keine gute Lösung.

**Comment by jojohoch** [comment]
Nein - im Player und Editor bleibt alles wie gehabt. Sonst brächten wir ja gar keinen Richtext-Editor.  Lediglich für Autocoder und Schemer geht die Information über HTML-Sonderzeichen verloren. Hier braucht man die Beschriftungstexte ja lediglich zur Zuordnung.

**Comment by PaulineKohrt** [comment]
okay, super :)
