### ISSUE TITLE
Element kopieren in Ablegelisten mit Bildern funktioniert nicht

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/verona-modules-aspect#375]
Leider scheint es so, als würde "Elemente kopieren" nicht funktionieren, wenn es sich um Bilder handelt. Man kann die Bilder zwar mehrmals entnehmen, aber scheinbar lassen sie sich nur jeweils einmal in eine Liste legen (erscheinen dort also nur einmal und lassen sich also kein zweites mal reinlegen).

Hier ein Beispiel (an dem bauen wir jetzt noch etwas rum, daher hoffe ich es ist noch repräsentativ für diesen Fehler wenn ihr euch das anschaut):  
https://www.iqb-studio.de/#/a/45/958/preview
(VERA MaP: 2023 Haupttest - Unit MV19823)

**Comment by jkoelm** [comment]
Ist doch kein Bug. Man würde an anderer Stelle ja erwarten, dass es sich so verhält.
