### ISSUE TITLE
Behandlung von invaliden Elementreferenzen

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/verona-modules-aspect#377]
Aktuell werden derartige Fehler schweigend ignoriert. Aber es wäre vllt nicht schlecht, wenn man als Benutzerin wenigstens gewarnt wird, wenn da was nicht iO ist. Man könnte auch weiter gehen und versuchen das vor vorherein zu unterbinden oder automatisch zu reparieren (alles invalide rausschmeißen oder so).

Das gilt für:
- verbundene Ablegelisten
- Abschnitte und Medienelementen (Abspielstatus) ("Sichtbarkeit nach")
- Buttons mit Seitenverweisen
- Audios (die abhängig voneinander sind)

**Comment by jojohoch** [comment]
Maßnahmen:
- Referenzen nur als SelectBoxen
- Beim Löschen von Elementen oder Id-Änderungen - Referenzen überprüfen
- Nachfragen wie gefundene Probleme gelöst werden sollen 

alte Aufgaben sanitizen!
