### ISSUE TITLE
Rahmenlinien der Eingabefelder und Eingabebereiche dunkler machen

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#380]
Die graue Umrandung von Eingabefeldern und Eingabebereichen ist sehr hell, an einigen Bildschirmen quasi unsichtbar. Wir hätten gerne ein etwas dunkleres Grau dafür: #cccccc

**Comment by jkoelm** [comment]
Wir hätten die Änderung gerne vor der Haupttestabgabe. Wenn es aber zu viel Zeit kosten sollte, würden wir die Priorität zugunsten anderer Tickets noch mal verändern.

**Comment by jojohoch** [comment]
Warum?  Wissen wir es besser als die Designer bei Google?

**Comment by jkoelm** [comment]
Ist ja nicht so, dass die exakt eine Farbe festgelegt hätten, die dann für jeden Anwendungszweck optimal ist. Zur Outline: ![grafik.png](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/f90dae4e-3c3b-4836-818b-0b51d635a84f)
https://m3.material.io/styles/color/the-color-system/color-roles

Unser aktueller Kontrast: ![grafik.png](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/aeb4c523-af8c-4f83-b816-9617ed7bdf54)
