### ISSUE TITLE
GeoGebra "propertiesPanel.custumToolbar"-Anzeige wird nicht gespeichert

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/verona-modules-aspect#384]
Wenn man mit z.B. 1|2|3|4 bei propertiesPanel.custumToolbar gewisse Werkzeuge auswählt, die das eingefügte GeoGebra-Element haben soll, wird dies zwar so umgesetzt, aber nicht angezeigt wenn man in der Vorschau war und zurück zum Editor geht oder gespeichert hat und später daran nur etwas verändern will (man muss also beim überarbeiten wissen, welche Nummern vergeben wurden um diese dann so + Veränderung einzugeben
siehe z.B. hier https://www.iqb-studio.de/#/a/68/2147/preview

Und gibt es irgendwo eine Liste wo wir die Nummern der dazugehörigen Werkzeuge finden können? Hier stimmt die Reihenfolge schonmal nicht: https://wiki.geogebra.org/de/Werkzeuge_der_Grafik-Ansicht

**Comment by rhenck** [comment]
Die Anzeige von "propertiesPanel.custumToolbar" ist schonmal ein Bug. Da fehlt die Übersetzung. Kam dir das nicht komisch vor? ;) Falls noch mehr solche Bezeichner zu sehen sind, bitte als Bug melden.

**Comment by jojohoch** [comment]
Ist das noch aktuell?

**Comment by PaulineKohrt** [comment]
ja
