### ISSUE TITLE
[editor] Anders als bei Elementen wird die 'width' von Seiten als string gespeichert

### ISSUE THREAD

**Issue by jojohoch** [iqb-berlin/verona-modules-aspect#39]
... zumindest nachdem der Default-Wert geändert wurde

**Comment by rhenck** [comment]
Ja das ist das gleiche Problem, wie mit den Elementdimensionen, die plötzlich Strings sind, wenn man die über das Properties-Panel ändert. Die blöden Nummernfelder geben Strings zurück und keine Zahlen. Ich kümmer mich drum.
