### ISSUE TITLE
Ablegelisten Kosmetik

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#405]
1. Beim Anfassen und Ziehen bekommt ein Element ein "Verboten"-Zeichen, das war bei den "alten" Ablegelisten nicht so und es soll auch jetzt nicht erscheinen.

2. Beim Anfassen und Ziehen gibt es ein graues Kästchen vor dem Text der Option, das soll auch nicht so sein.

Beides kann man hier im gif gut sehen: https://www.iqb-studio.de/#/a/39/495/preview

**Comment by rhenck** [comment]
Tritt beides nur unter Windows auf.

**Comment by rhenck** [comment]
Das Verboten-Zeichen taucht allerdings korrekterweise nur auf, wenn sich iwo befindet, wo man nichts ablegen darf. Trotzdem weg damit ja?

**Comment by jkoelm** [comment]
Ja, trotzdem weg, weil man sonst denkt, man darf das Element gar nicht anfassen und wegziehen

**Comment by rhenck** [comment]
Das mit dem Verboten-Zeichen und der Box ist beides Standardverhalten unter Windows und ist nicht unsere Progammierung entstanden. Wir können versuchen dagegen zu arbeiten. Aber auch hier nochmal der Hinweis, dass das vielleicht keine so gute Idee ist, eventuell gewohntes Verhalten zu beseitigen.

**Comment by rhenck** [comment]
Also hierfür gibt es leider keine richtige Lösung, das machen die Browser selbst und die lassen sich da nicht reinreden. Ich habe einen schlimmen Hack gefunden, den ich wirklich lieber unterlassen würde.

Ansonsten bliebe noch, dass wir das ganze aktuelle DragAndDropZeug wegwerfen und das selbst (am Browser-DragAndDrop vorbei) programmieren oder wir wieder zurück zu der alten Lösung gehen. Ich denke mal, das will niemand.

Bleibt also nur der Hack oder Akzeptanz des aktuellen Verhaltens (wir könnten noch an der Position von dem DragImage schrauben, damit es nicht überlappt, aber weg bekommen wir den Kasten nicht). Ich nehme an ihr besteht auf den Hack?
