### ISSUE TITLE
Drag&Drop am Tablet nicht bearbeitbar 

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/verona-modules-aspect#418]
ab Version Editor 35/Player 28 kann man D&D Aufgaben nicht mehr am Tablet bearbeiten: Die Vorbelegungen der Ablegelisten lassen sich gar nicht anfassen und ziehen. Manchmal ploppt noch die Hervorhebung (Rahmen um die Listen die verknüpft sind um anzuzeigen wo abgelegt werden kann) auf, bevor alles "einfriert" 

Lässt sich auch bei neu angelegten Aufgaben replizieren, z.B. hier: https://www.iqb-studio.de/#/a/58/3964/preview

**Comment by jojohoch** [comment]
Welche Version Safari bzw. iOS Version ist auf dem iPad installiert?

**Comment by PaulineKohrt** [comment]
Folgende Tablets wurden genutzt: Browser Safari am IPad (9. generation) mit iOS 15.5 & Browser Chrome am iPad Pro mit iOS 16.2.
