### ISSUE TITLE
Spaltenüberschrift CMC nicht mehr zentriert

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#419]
Bei der Umstellung von 1.36.2/1.29.3 auf 1.37.0-beta/1.30.0-beta verändern sich die Spaltenüberschriften von CMC/Optionentabellen. Wir hätten es gerne weiterhin zentriert wie in der 1.36.2/1.29.3.

vorher: ![grafik.png](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/8a14b619-a9c9-4067-a439-407244fd4ae9)

nachher: ![grafik.png](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/f35f212a-b5ea-4e7e-a7e9-a296c398caa1)

**Comment by jojohoch** [comment]
Defekter Player. Cache muss vor Release gelöscht werden!

**Comment by jojohoch** [comment]
Defekter Player. Cache muss vor Release gelöscht werden!
