### ISSUE TITLE
Optionentabelle mit Bild: Bilder skalieren

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#420]
Bei der Umstellung von 1.36.2/1.29.3 auf 1.37.0-beta/1.30.0-beta verändern sich die Spaltenüberschriften von CMC/Optionentabellen. Wir hätten es gerne weiterhin wie in der 1.36.2/1.29.3.

voher: ![grafik.png](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/c7987d15-bd07-4169-8ca3-e4605bb80984)

nachher: ![grafik.png](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/15946878-87f4-416a-8142-2d452cf9de86)

https://www.iqb-studio.de/#/a/7/2059/preview

**Comment by jojohoch** [comment]
Defekter Player. Cache muss vor Release gelöscht werden!
