### ISSUE TITLE
Drag-Image bei Bildern zu groß

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#423]
Bei der Umstellung auf 1.37.0-beta/1.30.0-beta verändern sich DnD mit Bild.
Vorher sind die Bilder immer exakt so groß, wie man sie reingegeben hat. Jetzt werden sie riesig beim Ziehen, so dass man sie nur sehr schlecht in die Zielfelder navigieren kann. Wir hätten es gerne wieder wie in der 1.33.3/1.26.3. 

https://www.iqb-studio.de/#/a/31/195/preview

**Comment by jojohoch** [comment]
Dieser Bug ist zum Teil auf den defekten Player zurückzuführen.
Allerdings dürfen die Drag-Images kein Padding haben.

**Comment by rhenck** [comment]
Kann ich nicht Reproduzieren. Brauche mehr Infos, was hier das Problem ist.
