### ISSUE TITLE
Markierstifte sind weiß statt schwarz

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#425]
1.37.1/1.30/1

Die Markierstifte und der Radiergummi sinf weiß, wir hätten sie gerne wieder schwarz so wie vorher.

![grafik.png](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/9b871050-6566-442b-a961-ed2fdbafd5f1)

**Comment by jojohoch** [comment]
Vermutlich defekter Build.
