### ISSUE TITLE
Eingabefelder werden riesig

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#426]
Mit der Umstellung auf die 1.37.1/1.30.1 werden normale einzeilige Eingabefelder viel zu groß. Der Cursor sitzt weit unten.

vorher:
![grafik.png](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/b4072916-fd0f-40fa-bf79-408f8fd003d1)

nachher:
![grafik.png](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/d3e9ee1f-8d48-4342-b560-757eba12b0e6)

zum Angucken: https://www.iqb-studio.de/#/a/7/4517/preview  (Ist noch nicht auf die neue Version umgestellt, sieht also erstmal normal aus.)

**Comment by jojohoch** [comment]
Vermutlich defekter Build.
