### ISSUE TITLE
Editor schneidet Buttonleiste links ab

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#427]
1.37.1/1.30.1

Im Editor wird die linke pinke Buttonleiste mit Abschnittsoptionen abgeschnitten.

![grafik.png](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/41a14de8-05c8-46f7-bbc9-13a6c6c7940c)

**Comment by jojohoch** [comment]
Vermutlich defekter Build.
