### ISSUE TITLE
Editor Elemente und Eigenschaften nicht fixiert -- unten nur noch whitespace

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#428]
1.37.1/1.30.1

Bei etwas längeren Aufgaben, wenn man in der Mitte weiter nach unten scrollt, bleiben die Inhalte der Leisten links (Elemente) und rechts (Eigenschaften) einfach oben und kommen nicht mit, so dass man zur Änderung von Eigenschaften immer ganz aufwendig hoch und runter scrollen muss.

zum Angucken, ab TA 4 kann sind die Eigenschaften/Elemente weg: https://www.iqb-studio.de/#/a/35/4515/editor

**Comment by jojohoch** [comment]
Vermutlich defekter Build.
