### ISSUE TITLE
Verdrängen bei DnD

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#429]
1.37.1/1.30.1

Wenn ein Element von einem anderen verdrängt wird, liegen kurzzeitig beide Elemente in der Liste, auch wenn nur eins reinpasst. Dadurch springt alles andere wild hoch und runter (im Beispiel unten die Textzeilen links. Es wäre echt toll, wenn das noch irgendwie anders ginge.

![DnD_Verdrängen.gif](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/7ad2823e-54db-4d9d-aa2f-794aa1c9ccdc)

**Comment by jojohoch** [comment]
könnte ich den Link zu der Aufgabe bekommen?

**Comment by jkoelm** [comment]
klar, sorry
https://www.iqb-studio.de/#/a/35/3984/preview
