### ISSUE TITLE
Verdrängen ohne kopieren - Elemente verschwinden

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#431]
1.37.4/1.30.4

Bei Ablegelisten, bei denen Optionen verdrängt werden können sollen, gehen die verdrängten Elemente nicht zurück in ihre Startliste, sondern verschwinden komplett. Hier z. B. https://www.iqb-studio.de/#/a/45/594/preview

**Comment by jkoelm** [comment]
Haben wir irgendwie hingekriegt... Teilweise hilft neu anlegen, manchmal wollen sie aber auch ein neues value-label bekommen - keine Ahnung. Jetzt gerade weigert sich eine andere Aufgaben, die kopierten Elemente zurückzunehmen. Kriegen wir nicht hin.

**Comment by jojohoch** [comment]
Ist das gelöst?

**Comment by jkoelm** [comment]
Wir sind nicht ganz sicher. In einer ganz neu angelegten Aufgabe tritt es nicht mehr auf. Aber bei einer Aufgabe, die von einer älteren Version auf die neue umgestellt wurde schon. Wir wissen nur nicht mehr, was die ursprüngliche Version dieser Aufgabe war. Kurzum: wir versuchen noch, das zu replizieren bzw. für euch replizierbar zu machen.

**Comment by jkoelm** [comment]
Wir finden nicht raus, welche wilde Versions- bzw. Umstellungshistory dafür nötig ist, daher schließe ich das Ticket.
