### ISSUE TITLE
Elemente kopieren mehr als einmal in nicht beschränkte Zielliste

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#432]
Unterschied zwischen 1.36/2/1.29.3 und 1.37.4/1.30.4

Hier zum Angucken: https://www.iqb-studio.de/#/a/35/784/preview

Achtung! Aufgabe ist **noch nicht in der 1.37/1.30 gespeichert**, sondern noch auf der 1.36/1.29 -- zum Nachvollziehen muss umgestellt werden.

Fehler in der 1.37.4/1.30.4: Wenn die Elemente der Startliste kopiert werden und das Zielfeld nicht auf ein Element beschränkt ist, kann man das gleiche Element beliebig oft in die Zielliste einfügen. Es sollte aber nur einmal dort abgelegt werden dürfen.

**Comment by PaulineKohrt** [comment]
Problem wurde bereits noch vor der Haupttestabgabe behoben
