### ISSUE TITLE
Ablegelisten im Lückentext mit "Verdrängen erlauben"

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#433]
1.37.4/1.30.4

Ablegelisten im Lückentext, für die das Häkchen bei "Verdrängen erlauben" gesetzt ist, verhalten sich anders als Ablegelisten im Lückentext, bei denen das nicht der Fall ist (über das Verdrängen hinaus).

1. Der Text sitzt linksbündig statt zentriert.
2. Wenn ein Element darin liegt und ich ein neues aus der Startliste nehme, flutscht das liegende Element ein Stück nach unten raus und der ganze Text springt wild.

Hier z. B. https://www.iqb-studio.de/#/a/35/477/preview

**Comment by PaulineKohrt** [comment]
ist mittlerweile gelöst
