### ISSUE TITLE
DnD: Rekursives Verdrängen funktioniert nicht

### ISSUE THREAD

**Issue by jojohoch** [iqb-berlin/verona-modules-aspect#438]
Führt zu potientiellen Fehlern:

Ideen:
1. Implenetieren
2. Frühzeitiger Abbruch

Szenario muss nachgestellt werden. Ticketbeschreibung ist theoretischer Natur

**Comment by helfjama** [comment]
Rekursives Verdrängen führt zu Bug: Wenn etwas rekursiv verdrängt werden sollte wird das Feld nicht anwählbar, man kann es also nicht mehr verdrängen
