### ISSUE TITLE
DnD - woanders ablegen nach überfliegen einer Liste nicht möglich

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#440]
1.38/1.31

Wenn ich mit einem angefassten Element auf dem Weg zu einer Zielliste über eine andere Zielliste gehe, wird diese als Ablege-Vorankündigung grau, gibt diesen Status aber nicht mehr ab, wenn ich zur nächsten Zielliste gehen. Egal wo ich loslasse, landet das Element dann in der zuerst berührten Zielliste.
Ergänzung: Tritt anscheinend nur auf, wenn die Startliste ein Lückentext mit DnD Elementen ist.

https://www.iqb-studio.de/#/a/102/6211/preview

![DnD-Bug.gif](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/668eddde-d06f-4c35-87ae-fc8fdcb90f58)

**Comment by jkoelm** [comment]
Ja, ist noch aktuell: https://www.iqb-studio.de/#/a/58/19861/preview

**Comment by rhenck** [comment]
Hm ja bei der Aufgabe kann ich das auch feststellen. Kann ich auch bei näherer Betrachtung gerade nicht erklären. Es funktioniert z.B. deutlich besser, wenn man bereits ein Element unten ablegt hat...
In unserem aktuellen Entwicklungsstand, kann ich das Problem jedenfalls nicht feststellen. Ich schlage deshalb vor, dass ihr das in der kommenden Beta nochmal testet. Vllt müssen wir da nix weiter tun.

**Comment by jkoelm** [comment]
ok

**Comment by jkoelm** [comment]
Beta 2.0: Problem besteht weiterhin: https://www.iqb-studio.de/#/a/58/19861/editor
