### ISSUE TITLE
Play-Button wird beim Mouseover nur auf der linken Seite hervorgehoben

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#441]
Die Hervorhebung des Play-Buttons beim Mouseover hört an der Spitze des Dreiecks auf. Sie sollte aber auf der rechten Seite genauso viel über das Dreieck hinausgehen wie auf der linken Seite vom Dreieck.

![grafik.png](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/dccae860-46b8-49f6-8e11-9b1dead596f8)

https://www.iqb-studio.de/#/a/7/8232/preview

**Comment by jojohoch** [comment]
Nach Angular Update wird die Grid-Breite von 37px nicht mehr funktionieren

**Comment by jojohoch** [comment]
Doch natürlich. Durch die Änderungen der Playerleiste würde aber zukünftig der Wert von 37px zu einem reichteckigen Button mit abgeschnittenem Dreieck führen. Vermutlich wird dann ein Wert über  42 notwendig sein.

**Comment by jkoelm** [comment]
Ah, ok, alles klar. Ich hatte kurz Sorge. ;)
