### ISSUE TITLE
grauer Pfeil-Button als Hinweis auf weiteren Seiteninhalt unten erscheint tw. auch, wenn es nichts zu scrollen gibt

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#442]
Hier z. B. https://www.iqb-studio.de/#/a/102/6234/preview

**Comment by jojohoch** [comment]
Im genannten Beispiel kann ich den Bug weder in FF noch in Chrome reproduzieren, allerdings lokal an einer anderen Datei. Hoffe dass er durch meine Änderung behoben ist
