### ISSUE TITLE
"sichtbar nach" manchmal falscher Fokus

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#444]
"sichtbar nach" manchmal falscher Fokus, z. B. hier:
https://www.iqb-studio.de/#/a/7/8240/preview
Nach dem Abspielen des zweiten Audio kommt wieder der allererste Abschnitt in den Fokus, obwohl der eigentlich sichtbar nach audio_1 eingestellt ist.
(Fortschrittsbalken steuerbar und Verzögerungszeit auf 10/15/17 Sek gesetzt, abweichend von der Originalaufgabe, damit man nicht so lange warten muss)

**Comment by jkoelm** [comment]
Ist immer so, wenn in der unit ein zweites Audio liegt, von dem aber keine weitere Abschnittssichtbarkeit mehr abhängt. Hier sehr auffällig: https://www.iqb-studio.de/#/a/117/8956/editor
Zudem wird nach dem Abspielen eines der Audios in den Items (z. B. Teilaufgabe 3) alles darauf folgende (wenn TA 4 vorher schon sichtbar war, dann ab TA 5) nicht mehr richtig angezeigt.

**Comment by jojohoch** [comment]
Es handelt sich hier um einen Konfigurationsfehler, der sich aus der Migration nach 2.0.0 ergibt, den wir allerdings auch nicht beheben können.
Da nun das Scrollen (Einblenden mit Scroll-Animation) explizit gesetzt werden kann, darf es nur für den ersten Abschnitt gesetzt werden . Bei den anderen Absätzen müsst ihr den Haken entfernen.

**Comment by jkoelm** [comment]
Da gibt es einen kleinen Bug: Wenn ich den Haken rausnehme, wird das nicht gespeichert. Beim nächsten Öffnen ist er wieder gesetzt.

**Comment by jojohoch** [comment]
Das ist ein anderes Problem. Wie du siehst, hast du es geschafft beim zweiten ausgeblendeten Abschnitt das Häkchen zu entfernen.
Die Aufgabe lädt in Editor und Player aber langsam , was damit zusammenhängt, dass bei der ersten Seite im ersten Absatz der rechte Abstand in einer alten Version gelöscht wurde statt ihn auf "0" zu setzen und das nun zu Problemen und Folgeproblemen führt.  s. #523
