### ISSUE TITLE
Ablegelisten: Optionselemente bemerken ID-Änderung der Eltern nicht

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/verona-modules-aspect#445]
Und verschwinden, wenn sie verdrängt werden, weil da eine nicht existente ID drin steht.

**Comment by jkoelm** [comment]
Das war schon mal gelöst, aber in Aspect 2.0 taucht es wieder auf.

**Comment by jkoelm** [comment]
Ergänzung: Bei in der 2.0 neu angelegten Aufgaben kann man die ID ändern, ohne dass das Problem auftritt. Bei umgestellten Listen schon.

**Comment by jkoelm** [comment]
Weitere Ergänzung: Man muss die ID gar nicht umbenennen, es reicht schon, die Aufgabe auf die Version 2.0 umzustellen.

**Comment by helfjama** [comment]
Gerade nicht reproduzierbar, melden uns falls es nochmal auftritt.

**Comment by rhenck** [comment]
Kann zu?
