### ISSUE TITLE
Markierknöpfe überlagern Hervorgehobenes im Text 

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#446]
Am Tablet (nicht am PC) überlagern die Markierböppel die durch einen Knopf-Link hervorgehobene Stelle im Text, wenn die Hervorhebung automatisch gescrollt wird, d.h. der Text wird zu weit hochgescrollt

**Comment by jojohoch** [comment]
Die Markierböppel überlagern in der neuen Version auf PC und iPad immer den Text - egal ob markiert oder hervorgehoben. Das erscheint mir auch das erwartetete Verhalten zu sein. Vielleicht versteh ich die Beschreibung aber auch nicht.

**Comment by jojohoch** [comment]
Kann ich weder in der Version 1.31.0 noch in 2.0.0-beta.3  reproduzieren.
Vielleicht sit es von der iPad/Browser Version abhängig? Hast du hierzu Informationen?

**Comment by jkoelm** [comment]
Tritt auf in Version 1.31 im Safari Browser, iPad 9. Generation, Softwareversion 15.4.1
bei dieser Aufgabe z. B.: https://www.iqb-studio.de/#/a/143/13440/preview

**Comment by rhenck** [comment]
Kann zu?
