### ISSUE TITLE
Änderungen der IDs für Optionsfelder im Lückentext nicht speicherbar

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#450]
Beim Ändern der IDs der Optionsfelder im Lückentext gibt es ein Problem: Die Aufgabe lässt sich nicht mehr speichern, der Speichern-Button bleibt ausgegraut. Auch wenn man danach andere Sachen ändert, bleibt der Button grau. z. B. hier: https://www.iqb-studio.de/#/a/111/8952/editor

**Comment by rhenck** [comment]
Das hat nix mit IDs zu tun - keine der Eigenschaften lässt sich ändern. Die Aufgabe scheint kaputt zu sein. Es gibt Fehler auf der Konsole.
Kann ich mit einer neuen Aufgabe nicht reproduzieren.
Ist das eine ältere Aufgabe? Gab evtl. Schäden beim Versionen springen.

**Comment by jkoelm** [comment]
Wir glauben inzwischen, dass es wohl an den Aufzählungszeichen liegt.

**Comment by helfjama** [comment]
JH: Unsere Vermutung: Wenn Aufzählungszeichen in Lückentexten in Kombination mit Optionsfeldern verwendet werden, verschwindet der Speichern-Button.
Sobald diese Aufzählungszeichen wieder entfernt werden, scheint es wieder zu funktionieren.
Lückentext ohne Aufzählung scheint unproblematisch zu sein. Außerdem: Lückentext mit Aufzählung aber ohne Optionsfelder scheint auch zu funktionieren.

Max hat hier: https://iqb-studio.de/#/a/58/23812/editor beispielsweise mal eine Aufgabe dazu angelegt, ihr könnt gerne damit herumexperimentieren.
