### ISSUE TITLE
defaults anpassen

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#452]
- Abstand unter CMC (Optionentabelle): 35 px
- Abstand unter MC mit Bildern: 0 px

**Comment by jkoelm** [comment]
2.0.0 Beta: Bei Optionentabelle mit Bild sind noch 40 px nach unten drin, die sollen raus.

**Comment by rhenck** [comment]
> 2.0.0 Beta: Bei Optionentabelle mit Bild sind noch 40 px nach unten drin, die sollen raus.

Meinst "Optionsfelder" mit Bild oder?

**Comment by jkoelm** [comment]
ja, sorry
