### ISSUE TITLE
"Bild-in-Bild"-PopUp bei Videos verhindern?

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#454]
(je nachdem wie kompliziert)

**Comment by rhenck** [comment]
Könnt ihr hier bitte mal schreiben, wie das nachzustellen ist? In Firefox bekomme ich den Knopf zusehen mit dem ich den Modus aktivieren kann, aber das wird ncht erzwungen, wenn ich nach unten wegscrolle..

**Comment by rhenck** [comment]
Weitere Browser prüfen
