### ISSUE TITLE
multiline textfields

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#456]
Wir hätten gerne einzeilige Eingabefelder, die sich erweitern, wenn man mehr schreibt --> 8. Multi-line text field 
https://m3.material.io/components/text-fields/guidelines#caf14aa9-26ce-48cc-9076-3a383a9ad679
https://m3.material.io/components/text-fields/specs#93411619-a459-4bb7-8a5c-74cd531d3bc5

[Falls das nicht geht, muss dieses Problem irgendwie gelöst werden: die Zeichen sind früher beschränkt, als man visuell sehen kann, bei mir zumindest, auch bei ZO A Aufg. 33; AS: ich kann bei beiden mehr eingeben als mir gleichzeitig angezeigt wird]

**Comment by jojohoch** [comment]
contenteditable div prüfen

**Comment by jkoelm** [comment]
Super! Gibt es das auch für text-field, also im Ausgangspunkt einzeilige Eingabefelder?

**Comment by jojohoch** [comment]
Nee, das ist ein Widerspruch in sich: einzeilige Textfelder können nicht mehrzeilig sein
