### ISSUE TITLE
neue Schriftart (statt Roboto)?

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#457]
wahrscheinlich Noto Sans

**Comment by jkoelm** [comment]
Könnt ihr mal bitte prüfen, ob Nunito Sans (regular 400) technisch in Frage kommt? Gestalterisch hätte die alles, was wir möchten. Open Font License hat sie wohl auch. Anders als alle anderen Schriften, die wir ausprobiert haben, weigert sie sich aber, sich in ein pdf einbetten zu lassen, daher wäre eine Prüfung sinnvoll.
https://fonts.google.com/specimen/Nunito+Sans

**Comment by jkoelm** [comment]
Die Kanten der Buchstaben oben sind teilweise etwas angeschnitten. Hatten wir für Roboto was an den Zeilenabständen o. ä. manipuliert?
Hier z. B. beim "B" und beim "E":
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVdFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d8f93338eee279f5ec0ede052615820b4db31cb7/grafik.png)

**Comment by rhenck** [comment]
Kann ich nicht reproduzieren. Mehr Infos bitte.

**Comment by jkoelm** [comment]
Ist noch ein Problem - müssen Infos nachliefern

**Comment by rhenck** [comment]
Warum ist das Ticket zurückgestellt? Scheint mir erledigt zu sein oder sind die Kanten weiterhin ein Problem?
