### ISSUE TITLE
Verbundelement Rechenkästchen verkabeln

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#459]
Lösung für schriftliche Rechenverfahren // evtl. Skriptbaustein ggb?

[noch in Abstimmung]

**Comment by jkoelm** [comment]
Hier die Konkretisierung der Anforderungen:
[20230925_Schriftliche Rechenverfahren.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamZTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b4146ab71165072175d35fe10f34c4e422c9e139/20230925_Schriftliche%20Rechenverfahren.pdf)

**Comment by jkoelm** [comment]
Aspect Beta 2.1 (Firefox 118.0.1 (64-Bit))
Allgemein:
- Schrift in den kleinen Zeilen soll noch ein bisschen kleiner
- Rechenkästchenlinien sollen etwas schwächer sein (grau statt schwarz), die dicken Linien sollen aber schwarz bleiben

Subtraktion: 
- dieses Zeichen hier nutzen: −
- wenn man in die kleinen Felder oberhalb der Zahlen etwas einträgt, erscheint der Wert auch im jeweils anderen Feld
- die erste Zahl und die Zahlen in den zwei kleinen Reihen oben sollen durchstreichbar sein durch Doppelklick

Multiplikation:
- dieses Zeichen hier nutzen: •
- Nachdem eine Zeile hinzugefügt wurde, soll neben dem Plus-Button ein Button mit Mülltonne erscheinen, der die zuletzt hinzugefügte Zeile löscht. Bei nur noch einer übrigen Zeile soll es keine Mülltonn geben

**Comment by jkoelm** [comment]
Noch drei Anmerkungen: 
- Bei der Multiplikation müssen in der ersten Spalte auch Rechenzeichen eingetragen werden können (+, -, *, :), nicht nur Ziffern.
- Es müssten bei allen Formaten auch leere Kästchen eingefügt werden können, auch mitten in der Zahl, also wenn ich einen dreistelligen Summanden habe, müsste ich auch die mittlere Ziffer freilassen können, damit sie von Schüler*innen ergänzt werden kann - solche Aufgaben gibt es auch.
- überhaupt gar nicht kritisch, definitiv nur nice to have: zwischen den Feldern mit Pfeiltasten navigieren können.

**Comment by rhenck** [comment]
> Noch drei Anmerkungen:
> 
>     * Bei der Multiplikation müssen in der ersten Spalte auch Rechenzeichen eingetragen werden können (+, -, *, :), nicht nur Ziffern.
> 
>     * Es müssten bei allen Formaten auch leere Kästchen eingefügt werden können, auch mitten in der Zahl, also wenn ich einen dreistelligen Summanden habe, müsste ich auch die mittlere Ziffer freilassen können, damit sie von Schüler*innen ergänzt werden kann - solche Aufgaben gibt es auch.
> 
>     * überhaupt gar nicht kritisch, definitiv nur nice to have: zwischen den Feldern mit Pfeiltasten navigieren können.

"Anmerkungen".. Du meinst umfangreiche Feature-Requests, von denen vorher nie die Rede war. Müssen wir sehen, ob wir davon noch irgendwas in diesem Jahr schaffen.
