### ISSUE TITLE
Eingabehilfen Tablet/PC

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#461]
Wenn Eingabehilfen für ein Eingabefeld geschaltet sind, sollen sie sich am Tablet an die IQB-Tastatur hängen. Bei der gleichen Aufgabe am Laptop/Desktop sollen sie jedoch wie gehabt als Eingabhilfe aufploppen.

**Comment by jkoelm** [comment]
Aspect 2.0 Beta 3
Funktioniert bei mir nicht. Beim Tippen in das Eingabefeld öffnen sich die IQB-Tastatur und zusätzlich die Eingabehilfe Französische Sonderzeichen (schwebend).

iPad 9. Generation, Softwareversion 15.4.1

**Comment by jojohoch** [comment]
Vielleicht Bedienfehler - oder Probleme beim Überführen einer alten Aufgabe?

**Comment by jkoelm** [comment]
Aufgabe ist neu angelegt in Beta 3. Bedienfehler kann ich nicht ausschließen. ;)

**Comment by jkoelm** [comment]
aaah!! Bedienfehler! sorry :)
