### ISSUE TITLE
BiSta Lesen: Magnetisches Scrollen und Hypertext

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#464]
Hier haben wir noch keine Idee, aber es hat sich herausgestellt, dass unsere Umsetzung für die Anforderung von Hypertextstrukturen (Knöpfe, die wie ein Link aussehen und auf eine andere Seite derselben Unit verweisen im Lückentext) leider nicht funktionieren, wenn magnetisches Scrollen eingestellt ist. Beides ist aber gewollt.

Kann man evtl. rechts und links auf ein Set an Seiten fixieren? dann wäre links fixiert der Text und die Seiten, wo die Links hinführen und rechts wären alle Items auf Einzelseiten?

**Comment by jojohoch** [comment]
Lösung: Erweiterung der Möglichkeit Secttions ein- und Auszublenden. "Hyperlink-Seiten" könnten dann unterschiedliche Sections in einer Seite sein - verleichbar mit einem Material Akkordion.
