### ISSUE TITLE
BiSta Zuhören: Audio in Drag and Drop

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#465]
Bei den neu entwickelten Zuhöraufgaben sollen auch die Items abspielbar sein, um Zuhörkompetenzen ohne die Vermischung mit Lesekompetenzen abbilden zu können. Einige Formate sind okay umsetzbar, aber bei Drag and Drop wäre es gut, wenn man ein Audio-Element mit in die Option packen könnte (Play-Button vor dem Wort), damit man sich das auch nach der Zuordnung noch anhören kann.

https://www.iqb-studio.de/#/a/117/8956/preview

**Comment by jkoelm** [comment]
in FF besprochen am 07.03. -- wenn man Variante "Audio und Text" (als 3. Art verschiebbares Element) im Design streng fixiert, ist es wahrscheinlich machbar

**Comment by jojohoch** [comment]
Neues (Options-)Element: "Vorlesbarer Text"
