### ISSUE TITLE
Tablet: nicht mehr nach oben scrollbar nach Tippen in Eingabefeld (nach unten schon)

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#470]
Tablet: tippt man in ein Eingabefeld, kann man nicht mehr nach oben scrollen (nach unten jedoch schon). Gilt für zweiseitig (inkl. Lesetext) und einseitig (Video hier: "P:\TBA\02_Organisation\01_StuMis\04_Gemeinsamer Arbeitsordner\Tabletaufnahme Scrollen mit Textfeld.MOV")

**Comment by jojohoch** [comment]
nicht reproduzierbar

**Comment by helfjama** [comment]
Hatten wir auch seit langem nicht mehr.
