### ISSUE TITLE
BiSta Mathe: Einfärbetool: Zwei mal drücken -- zweite Farbe

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#473]
Wir hätten gerne für das Einfärbetool die Möglichkeit, dass beim ersten Mal drücken eine Farbe kommt, beim zweiten Mal drücken eine andere Farbe und beim dritten Mal drücken geht die Einfärbung wieder weg.

**Comment by jojohoch** [comment]
Wirft das bisherige Konzept mit dem verbundenenen Datenmodell über Bord, bei dem wir festgelegt haben, dass es nur zwei Zustände, mit einer vordefinierten Füllfarbe gibt.
 
Sind in Zukunft weitere Zustände denkbar? 
- weitere Farben
- andere Formen
- Positionsänderungen
- Texte in Abhängigkeit vom Zustand

**Comment by jkoelm** [comment]
https://www.iqb-studio.de/#/a/12/2196/preview
