### ISSUE TITLE
Optinentabellen-Spaltenüberschriften "wandern mit" 

### ISSUE THREAD

**Issue by PaulineKohrt** [iqb-berlin/verona-modules-aspect#475]
bei besonders vielen Zeilen kann man die Spaltenüberschriften irgendwann nicht mehr sehen und es wäre gut, wenn die Spaltenüberschriften (ähnlich wie die Markierstifte) auch noch angezeigt werden, wenn man sie sich eigentlich außer Sicht gescrollt hab - sie also mitwandern

**Comment by jkoelm** [comment]
Das Ticket gibt es schon (#311), daher hier schließen.
