### ISSUE TITLE
neues Element: allgemeiner Fragezeichen-Knopf

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/verona-modules-aspect#481]
- Als extra Element - nein: Erweiterung des ButtonElements #512 
- als Tooltip-Element - nein: Erweiterung des ButtonElements #512
- für normales Textelement (mit Lückentext-Tech) #513
- überlegen, ob Lückentext überhaupt noch gebraucht wird 
- Markieren soll weiterhin möglich sein #513
- Fußnotentext unter Texten sind davon unabhängig
- prüfen, ob das einfach ein erweiteres Button-Element ist (drückbar für Tablet) #512

**Comment by jojohoch** [comment]
Dem Buttonelement fehlt:
Bei Lückentext Breite einstellen.
Lückentext:
    vertical-align: super;
    font-size: smaller;
Tooltip als Action oder zusätzlich?
