### ISSUE TITLE
Fehlverhalten im Testcenter bei einseitigen Units im Snap Scroll Modus ("magnetisches Scrollen")

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#498]
Die Aufgaben für die Primarstufe haben ganz unten immer einen "Hier geht's weiter"-Button zur nächsten Unit. Außerdem gibt es als Hinweis, dass unten noch was kommt, ja diesen mittigen grauen Pfeil nach unten. Im Testcenter ist es nun so: Wenn ich ganz nach unten gescrollt habe, so dass der graue Pfeil verschwindet, und dann auf den "Weiter"-Button drücke, rutscht der Fokus ein ganzes Stück nach oben, so als hätte ich nach oben gescrollt. Wenn ich nicht ganz runter scrolle, so dass der graue Pfeil noch angezeigt wird, läuft alles wie es soll und ich gelange über den Weiter-Button zur nächsten Unit. Daher die Vermutung, dass es irgendeinen Konflikt mit den beiden Buttons gibt. Im Studio kann man es nicht reproduzieren. Zugangsdaten zum Center schick ich euch auf Anfrage (geht hier nicht, da vertrauliche Aufgaben).

**Comment by helfjama** [comment]
Müssen wir nochmal mit euch genauer besprechen (hat mit magnetischem Scrollen und einseitigen Units zu tun)

**Comment by helfjama** [comment]
[Uploading... scrollen.gif]

**Comment by helfjama** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTdLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b7e7cb8a67c4e852d3f48cee3e5dbc0d8997fc8/scrollen.gif)

**Comment by jojohoch** [comment]
Welche Aufgabe ist das?

**Comment by helfjama** [comment]
Diese hier aus dem interaktiven Übungsmodul: https://www.iqb-studio.de/#/a/151/36523/preview - das Verhalten sollte aber so bei allen einseitigen Aufgaben auftreten, wenn magnetisches Scrollen eingestellt ist.

**Comment by jojohoch** [comment]
Endlich geschafft das Problem nachzustellen: Die Angabe des Browsers bei entdecktem Fehlverhalten ist absolut notwendig!!!
