### ISSUE TITLE
Position der Toggle-Buttons befindet sich nicht auf der Linie des Lückentextes 

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#499]
Bei Toggle-Buttons im Lückentext kann man Gewähltes oder nicht Gewähltes durchstreichen lassen. Die waagerechte Linie dafür ist mometan recht dünn und nur schlecht sichtbar. Wir hätten daher gerne eine dickere Linie.

**Comment by jojohoch** [comment]
Fehler exitiert bereits in Beta.2
