### ISSUE TITLE
Drag and Drop reagiert zu spät

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#503]
1.38/1.31

https://www.iqb-studio.de/#/a/102/6211/preview

Drag and Drop reagiert zu spät. Problem ist etwas ähnlich zu #440, aber doch ein bisschen anders, weil es bei #440 gar nicht funktioniert und hier nur zu spät.

Ich habe zur Veranschaulichung ein Video gemacht. Der Sommer lässt sich normal bei 2) ablegen. Beim Winter ist es dann so, dass zuerst das Feld 2) hervorgehoben wird, was ja logisch ist, weil ich mit der Maus darüberfahre. Wenn ich dann aber zu Feld 3) weitergehe, reagiert dieses Feld deutlich zu spät, also nicht auf meinen Mauszeiger und noch nicht mal, wenn das ganze Winter-Element schon in das Feld reingezogen ist. Erst wenn ich noch weiter runtergehe, merkt das Feld 3), dass es gemeint ist.

Dieses Verhalten hat bei den Cognitive Labs so gut wie allen Schüler*innen Probleme gemacht.

![DnD-Bug.gif](https://images.zenhubusercontent.com/62165b91a53e2050d3b24aec/a6d659c2-bcc4-4849-a4be-f38d4f6399d0)

**Comment by rhenck** [comment]
Wird gelöst in #567
