### ISSUE TITLE
Einzelne Elemente müssen für die Erreichung Presentation-Complete ausgenommen werden können

### ISSUE THREAD

**Issue by jojohoch** [iqb-berlin/verona-modules-aspect#506]
Elemente in ausgeblendeten Abschnitten, die nicht unbedingt vom User geöffnet werden müssen

**Comment by jkoelm** [comment]
Beta 2.0
Man kann das Häkchen bei "relevant für Presentation complete" rausnehmen, aber wenn man dann auf die Vorschau geht, hat das keinen Einfluss (Elemente werden für presentation complete trotzdem berücksichtigt) und zurück im Editor ist das Häkchen dann auch wieder da.

**Comment by jkoelm** [comment]
Beta 2.3
Häkchen wird gespeichert, aber für presentation complete werden auch Elemente ohne das 'Häkchen berücksichtigt

**Comment by jojohoch** [comment]
compoundelements checken
