### ISSUE TITLE
Standardeinstellung "Bearbeitung anderer Zeichen verhindern"

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#508]

**Comment by helfjama** [comment]
Beim Hinzufügen von Eingabehilfen bei Textfeldern wird als Standardeinstellung der Haken bei "Bearbeitung anderer Zeichen verhindern" gesetzt. Dadurch vergessen viele Aufgabenentwickler bei normalen Aufgaben diesen Haken zu entfernen und es können nur z.B. französische Sonderzeichen eingetippt werden. 
Bitte die Voreinstellung also so ändern, dass der Haken standardmäßig nicht gesetzt ist.

**Comment by jojohoch** [comment]
Bei allen anderen Eingabehilfen war aber genau diese Standardeinstellung gewollt

**Comment by jojohoch** [comment]
Standard ändern
