### ISSUE TITLE
GeoGebra Loading Fehler

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#511]
GeoGebra-Dateien ohne Werkzeuge werden nicht geladen. 
Siehe z.B. Datei im Anhang.
https://www.iqb-studio.de/#/a/183/24893/preview  [https://app.zenhub.com/files/358306669/a16103a4-6fa8-4923-95e9-668a89d93028/download](https://app.zenhub.com/files/358306669/a16103a4-6fa8-4923-95e9-668a89d93028/download)

**Comment by jojohoch** [comment]
Die Option Werkzeugliste einblenden darf(!) nur gewählt werden, wenn die Geogebra-Datei über eine Werkzeugleiste verfügt. Also beim Anlegen daran denken, wenn ihr eine wollt. 
Ich habe die Option jetzt standardäßig abgestellt und mit einem Hinweis versehen, damit auch GGB-Dateien  ohne Toolbar geladen werden können.
