### ISSUE TITLE
Elementinteraktion möglich trotz nicht erlaubter Elementinteraktion

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#524]
Beta 2.0

Kleinigkeit: Audioelemente lassen sich im Editor nicht auswählen, wenn ich in den Bereich des Fortschrittsbalkens klicke. Klicke ich irgendwo anders, geht es aber.

**Comment by rhenck** [comment]
"Pointer-events: none" wird nicht an Kindeskinder vererbt.

Vermutlich am besten via CSS zu lösen: In etwa:
. draggable-element * {pointer-events: none}

**Comment by rhenck** [comment]
Bei der Gelegenheit auch mal den Schalter "Elementinteraktion erlauben" überprüfen. Der scheint nicht ordentlich abzuschalten, wenn wieder abgewählt.

**Comment by rhenck** [comment]
Scheint erst mit dem Angular-Update passiert zu sein -> Nachgehen
