### ISSUE TITLE
Default-Mindesthöhe bei Ablegeliste ändern 

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#525]
Beta 2.0

Wenn ich einer Ablegeliste eine Mindesthöhe gebe, reagiert sie zwar im Editor darauf, in der Vorschau verhält sie sich aber, als wäre keine Mindesthöhe gesetzt (wird kleiner, wenn man Elemente rausnimmt). https://www.iqb-studio.de/#/a/68/27074/editor

**Comment by rhenck** [comment]
Mindesthöhe auf eine Zeile setzen

**Comment by jkoelm** [comment]
in Aspect 2.0 sind das 58 px für eine Zeile
