### ISSUE TITLE
Knopf reagiert nicht auf Radiuseinstellung

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#536]
Aspect 2.0 Beta 5

Der Knopf interessiert sich nicht für die Einstellungen des Radius und merkt sie sich auch nicht.

**Comment by rhenck** [comment]
Gerne mal F12 drücken, wenn was nicht geht. Und entsprechend ins Ticket mit reinpacken,wenn "rotes Zeug" zu sehen ist.
