### ISSUE TITLE
Formatierung CMC-Elemente

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#540]
Wir haben einen Bug entdeckt wenn man aus manchen PDF-Dateien mehrzeiligen Text in CMC-Optionen kopiert. Diese versuchen anscheinen die Absätze aus dem PDF zu übernehmen, aber anstatt dann mehrere Zeilen in der CMC-Option zu haben baut Aspect dann mehrere Spalten ein - jeder Absatz im PDF wird dann zu einer eigenen Spalte im Editor. Das Problem lässt sich umgehen, wenn man den Kopier-Umweg über eine Word-Datei geht, aber nicht wenn man im Editor "Text ohne Formatierung" einfügt, die Absätze behält er anscheinend trotzdem und "übersetzt" sie falsch.
Die **Priorität dieses Issues ist allerding sehr niedrig**, da wir einen workaround haben und Aufgabenentwickler selten oder nie aus PDFs in CMCs kopieren sollten. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkRRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--02d440d9a56f58092f966d942e0110f24d667ec3/grafik.png)

**Comment by rhenck** [comment]
Müssen wir mal besprechen, ob das überhaupt ein relevanter Bug ist.
