### ISSUE TITLE
Abstand zwischen Optionen bei mehrzeiligen MCs

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#541]
Bei mehrzeiligen MC gibt es keinen Abstand mehr zwischen den Optionen. Sobald die Optionen 2 oder 3 Zeilen erreichen verschwindet der Abstand dazwischen und das ganze sieht aus wie ein Fließtext.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0xSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7695f5523eb50745abf4421da9b8f00cdcd33df4/grafik.png)

**Comment by rhenck** [comment]
Nicht mehr zentriert, sondern auf Höhe der ersten Zeile

**Comment by rhenck** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWsrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd39d1f757953167448201cb1e916a5a79aa14d1/var1.png)

**Comment by rhenck** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW8rQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--937f665d1689f810156b8b0a3492b84e231f843e/var2.png)
