### ISSUE TITLE
Regler für Lautstärkeinstellung am Audioelement zeigt unerwartetes Verhalten

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#542]
2.0.1/2.0.0

Niedrige Priorität, aber der Schieberegler für die Lautstärke an Audioelementen zeigt ein unerwartetes Verhalten. Wir haben eine Mindestlautstärke von 0.2 eingestellt. Wenn ich den Regler das erste Mal ganz nach links schiebe, stoppt er, bevor er ganz links an den Rand stößt. So würde ich es erwarten. Beim zweiten Mal lässt er sich aber ganz nach links ziehen (beim dritten Mal nicht, beim vierten Mal wieder :D). An der Lautstärke ändert das dann aber glücklicherweise nichts.

zum Ausprobieren:
https://www.iqb-studio.de/#/a/156/33037/preview

**Comment by rhenck** [comment]
https://github.com/iqb-berlin/verona-modules-aspect/commit/d40ab326fd86e36bef341263d58156746b58ce98

Der Commit ist bereits im Master. Falls hierfür eine bessere Lösung gefunden wird, bitte reverten.
