### ISSUE TITLE
Abschnitte ausschneiden

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/verona-modules-aspect#543]
Diese Funktion hätten wir gerne zusätzlich zum Kopieren von Abschnitten, damit optional ID und Kodierung erhalten bleiben, wenn man einen Abschnitt auf eine andere Seite verschieben will.

**Comment by rhenck** [comment]
Warum nicht Kopieren und anschließend Löschen?

**Comment by jkoelm** [comment]
Wegen der IDs + Kodierung, die dann nicht mit übernommen werden

**Comment by helfjama** [comment]
Kopieren, löschen, einfügen
