### ISSUE TITLE
Safari Farbauswahl

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#556]
Bei der Aufgabenentwickler-Tagung Englisch ist einer Aufgabenentwicklerin ein Bug aufgefallen:
Auf ihrem Macbook in Safari funktioniert die Farbauswahl im Texteditor nicht, die Farbenauswahl öffnete sich nicht. Ich war in Präsenz dabei und habe es im Safari-Browser dann auch nicht geschafft die Farbe von Text im Texteditor umzustellen.
Leider habe ich kein Apple-Gerät und kann den Bug daher nicht reproduzieren - könnt ihr mit der Beschreibung so etwas anfangen und könnt das möglicherweise auch reproduzieren?
Ansonsten stehe ich gerne für Nachfragen zur Verfügung.

**Comment by jojohoch** [comment]
Prüfen ob Crome oder FF auf Mac funktionieren

**Comment by helfjama** [comment]
@jojohoch Der Release gilt nur für die Recherche, das Problem selbst müssen wir danach nochmal besprechen

**Comment by rhenck** [comment]
Also ich kann es reproduzieren. Farbauswahl-Eingaben scheinen generell nicht zu funktionieren mit Safari. Habe dafür auch auf die schnelle keine Lösung gefunden. Ist die Frage, wie wichtig das ist und wieviel Zeit da reingesteckt werden soll.

**Comment by rhenck** [comment]
Beschluss: Safari wird im Editor nicht unterstützt.
