### ISSUE TITLE
Audios teilweise ausgegraut und nicht abspielbar

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#563]
Sowohl im Teststudio als auch im Testcenter sind Audios manchmal aus unerklärlichen Gründen ausgegraut und nicht abspielbar. Neu laden der Seite oder im Testcenter hin und herwechseln zwischen Aufgaben sorgt dann dafür, dass die Audios sich wieder abspielen lassen. 
Wir haben keine Gemeinsamkeiten zwischen den Audios gefunden, es scheint alle manchmal zu betreffen.
PS: Auf dem Tablet scheint es gut zu funktionieren, betrifft wahrscheinlich nur PC-Browser.

**Comment by jojohoch** [comment]
Das Problem besteht darin, dass der Browser (insbesondere Firefox) nicht in der Lage ist die Dauer des Audios zu ermitteln. Dies beruht wiederum darauf, dass die betreffenden Audios in "Mono" kodiert sind. Die Audios müssen daher konvertiert werden und leider ausgetauscht werden.
