### ISSUE TITLE
Formeleditor manche Zeichen nicht angezeigt

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#565]
Der Formeleditor zeigt manche Zeichen im Eingabefeld nicht richtig an: Ungleich und beide eckigen Klammern.

**Comment by rhenck** [comment]
Das mit den eckigen Klammern wird schwierig. Klammern verhalten sich bei dem normalen Formelelement auch komisch. Benutzt ihr das eigentlich?
Ich denke man müsste hier als erstes mal die Formeleditor-Bibliothek aktualisieren. Die haben allerdings breaking changes, sodass wir einiges anpassen müssen. Also eine größere Sache und damit unklar, wann wir da Abhilfe schaffen können. Am besten mal priorisieren.

Ungleich-Zeichen habe ich repariert.

**Comment by rhenck** [comment]
Hab die Update-Variante ausprobiert. Das löst die Sache. Leider geht mit dem Update die Tastatur kaputt und ich finde keinen Weg das zu beheben.

**Comment by helfjama** [comment]
Da müsstest du mir im FF erklären was du meinst, für mich scheint es gut zu funktionieren

**Comment by rhenck** [comment]
Achso ja, das hätte ich erklären sollen. Also die Sache ist nun so gelöst, dass der MatheEditor die Klammern nicht mehr automatisch schließt. Das löst zum einen das Problem, dass der Player immer nach nur 1 Zeichen aus der Klammer springt (beim Formelfeld festgestellt) , als auch das Problem, dass nach dem Bestätigen (im Formelbereich) so komische Sachen wie "?" oder "lbrak" erscheinen.
