### ISSUE TITLE
Ablegelisten: Generalüberholung

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/verona-modules-aspect#567]
Beispielaufgabe:
https://www.iqb-studio.de/#/a/102/6211/preview

**Comment by helfjama** [comment]
Sortierliste: Name im Menü noch anpassen
Optionsfelder/Optionstabellen mit Bild, Ausrichtung: Keine Auffälligkeiten bemerkt
Sortieren fühlt sich cleaner an +
Lückentext: neu: https://www.iqb-studio.de/#/a/212/42495/preview TA 12: DaD Elemente plötzlich höher als vorher: alt: https://www.iqb-studio.de/#/a/156/38135/preview
https://www.iqb-studio.de/#/a/212/42495/preview TA 24: ursprüngliche Ablage bleibt auch nach Ablegen in neuem Feld teilweise grau hervorgehoben
https://www.iqb-studio.de/#/a/212/42495/preview TA 9: Elemente verschwinden erstmal beim Verdrängen und tauchen in Ursprungsliste erst wieder auf, wenn die refreshed wird (z.B. durch verschieben eines Items aus dieser Liste woanders hin)
Ich finde die Idee mit der Hintergrundfarbe der Elemente eigentlich gut, aber wir müssen darüber auf jeden Fall nochmal reden (und wahrscheinlich die Einstellung wenn dann als Alternative mit Häkchen setzen anbieten). Weißt du vielleicht, wie viel mehr Platz die Bilder dadurch einnehmen? Vielleicht ist mehr Abstand zwischen Bildern in einer Liste? https://www.iqb-studio.de/#/a/212/42496/preview vs https://www.iqb-studio.de/#/a/156/38140/preview. Wenn ich das richtig sehe, müsste man dann die Einstellungen bei allen vorher angelegten DnD anpassen (das wäre sehr schlecht)? (Sehr komisch: Links passt es anscheinend, aber rechts nicht)? Erstmal rausnehmen
Audiobuttons ziehen schauen wir uns noch an
Sortierliste standardmäßig aus, schauen wir uns an bei den Aufgaben

**Comment by rhenck** [comment]
"ursprüngliche Ablage bleibt auch nach Ablegen in neuem Feld teilweise grau hervorgehoben"

Das passierte bei nur-ein-Element-Listen. -> Behoben

**Comment by rhenck** [comment]
"Lückentext: neu: https://www.iqb-studio.de/#/a/212/42495/preview TA 12: DaD Elemente plötzlich höher als vorher: alt: https://www.iqb-studio.de/#/a/156/38135/preview"

Mal Kritik am Rande: In TA 12 sind die Startlisten (mit "Lücken" und "Antworten") als Lückentext angelegt. Es gibt aber keinen Text drumherum oder andere ersichtliche Gründe, warum das ein Lückentext ist. Das ist Missbrauch und ich rate ab. Benutzt die Elemente, wie sie gedacht sind, oder legt Tickets an, wenn euch Features fehlen.

**Comment by helfjama** [comment]
Hier die Ergebnisse meines Tests der Beta 2, können wir dann ja gerne mal durchsprechen:

- [ ] Sortierliste: Name im Menü noch anpassen - ist gemacht
- [ ] TA 12: DaD Elemente plötzlich höher als vorher - In Beta 2 nicht mehr höher, aber beim Ziehen der Optionen werde sie sehr klein beschnitten (https://www.iqb-studio.de/#/a/212/46131/preview) TA 12#
- [ ] TA 24: ursprüngliche Ablage bleibt auch nach Ablegen in neuem Feld teilweise grau hervorgehoben) - Jetzt nicht mehr, gibt nur noch kurzen fadeout (Absicht?)
- [ ] TA 9: Elemente verschwinden erstmal beim Verdrängen und tauchen in Ursprungsliste erst wieder auf, wenn die refreshed wird (z.B. durch verschieben eines Items aus dieser Liste woanders hin) - behoben
- [ ] Ich finde die Idee mit der Hintergrundfarbe der Elemente eigentlich gut, aber wir müssen darüber auf jeden Fall nochmal reden (und wahrscheinlich die Einstellung wenn dann als Alternative mit Häkchen setzen anbieten). Weißt du vielleicht, wie viel mehr Platz die Bilder dadurch einnehmen? Vielleicht ist mehr Abstand zwischen Bildern in einer Liste? https://www.iqb-studio.de/#/a/212/42496/preview vs https://www.iqb-studio.de/#/a/156/44426/preview. Wenn ich das richtig sehe, müsste man dann die Einstellungen bei allen vorher angelegten DnD anpassen (das wäre sehr schlecht)? (Sehr komisch: Links passt es anscheinend, aber rechts nicht)? Erstmal rausnehmen - ist raus
- [ ] Sortierliste standardmäßig aus, schauen wir uns an bei den Aufgaben - sieht auf den ersten Blick sehr gut aus
- [ ] Audiobuttons ziehen schauen wir uns noch an - das Verschieben damit funktioniert sehr gut, der Audiobutton ist auch normal anklickbar - aber irgendwie spielt kein Audio ab?
- [ ] https://www.iqb-studio.de/#/a/212/46131/preview - TA9: Ich habe die Liste bei Zuordnung 2 mal spaßeshalber schreibgeschützt gestellt, kann sie aber weiterhin ganz normal nutzen
- [ ] https://www.iqb-studio.de/#/a/212/46131/preview - TA25: Bilder haben hier irgendwie noch Hintergrundfärbung?
- [ ] Text und Bild gleichzeitig: Ist es Absicht, dass der Text immer nur rechts daneben stehen kann und lückenlos angeschlossen ist?
- [ ] Drag and Drop springt minimal - das hat sich mit der neuen Version erledigt, richtig? Mir ist nichts mehr aufgefallen
- [ ] DnD - woanders ablegen nach überfliegen einer Liste nicht möglich - funktioniert jetzt super
- [ ] DnD: Rekursives Verdrängen funktioniert nicht#438 - Verstehe ich nicht ganz?

**Comment by rhenck** [comment]
Zu "TA 12: DaD Elemente plötzlich höher als vorher - In Beta 2 nicht mehr höher, aber beim Ziehen der Optionen werde sie sehr klein beschnitten (https://www.iqb-studio.de/#/a/212/46131/preview) TA 12#"

Also hier sehe ich das Problem in der bereits angelegten Aufgabe, ich bekomme es aber nicht das nachzubauen. Wenn ich mir einen Lückentext anlege und da Ablegelisten reinlege, besteht das Problem nicht. Hast du einen Tipp für mich?

**Comment by helfjama** [comment]
Lieber Richard,
das hier ist neu angelegt und danach mit denselben Einstellungen versehen: https://www.iqb-studio.de/#/a/212/46204/preview
Hier ist es auch wieder kaputt. Ich kann dir aber leider nicht beantworten was es genau kaputt macht. Es ist aber sehr sicher eine der Einstellungen, wenn man es mit Standardeinstellungen anlegt funktioniert es. Vielleicht "nur ein Element" oder "potenzielle Ablagen hervorheben"? Ungefähr da scheint es kaputt gegangen zu sein

**Comment by rhenck** [comment]
> Lieber Richard, das hier ist neu angelegt und danach mit denselben Einstellungen versehen: https://www.iqb-studio.de/#/a/212/46204/preview Hier ist es auch wieder kaputt. Ich kann dir aber leider nicht beantworten was es genau kaputt macht. Es ist aber sehr sicher eine der Einstellungen, wenn man es mit Standardeinstellungen anlegt funktioniert es. Vielleicht "nur ein Element" oder "potenzielle Ablagen hervorheben"? Ungefähr da scheint es kaputt gegangen zu sein

Es liegt an "potenzielle Ablagen hervorheben", wie wir inzwischen herausgefunden haben. hat eine Weile gedauert. :) Danke
