### ISSUE TITLE
Formeleditor update

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#570]
Auf neuste Version umstellen und Probleme damit dann beheben
(auch den Klammer-Hack herausnehmen)

**Comment by rhenck** [comment]
Update geht grundsätzlich und scheint auch die Klammerprobleme zu lösen. Die Tastatur geht dann aber nicht mehr.
Siehe: https://github.com/arnog/mathlive/issues/1935
