### ISSUE TITLE
Lückentext falsche Schriftart

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#574]
In Lückentexten ist nicht dieselbe Schriftart wie in den anderen Elementen.

**Comment by rhenck** [comment]
Wie kommst du zu dieser Behauptung? Kann ich nicht nachvollziehen/reproduzieren.

**Comment by helfjama** [comment]
Die Schrift in Eingabefelder im Lückentext sieht anders aus als sonst - entschuldige bitte, das hätte ich präzisieren müssen!

**Comment by rhenck** [comment]
Entschuldigung ist nicht nötig. Stattdessen bitte Beweisfotos, verlinkte Units etc.

**Comment by helfjama** [comment]
Bei neuen Lückentexten funktioniert das, bei Lückentexten aus der vorherigen Version anscheinen nicht - siehe https://www.iqb-studio.de/#/a/212/41093/preview TA11 für einen Lückentext aus der alten Version und ganz unten einen neu angelegten. Kann man da noch was dran machen?
