### ISSUE TITLE
Lückentext verrutscht am Tablet

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#575]
Eingabefelder in Lückentexten verrutschen am Tablet (ipad pro mpdy2fd/a) nach unten. Nach dem Eingeben zweier Zeichen "rutscht" alles wieder wie gewollt an Ort und Stelle.

**Comment by jojohoch** [comment]
Könnte ich bitte einen Link zur Aufgabe haben?
