### ISSUE TITLE
Schriftart IQB-Tastatur

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#581]
Wäe es möglich die Schriftart der IQB-Tastatur noch auf unsere jetzige Standardschriftart umzustellen?

**Comment by rhenck** [comment]
Haben wir überprüft und wir stellen die korrekte Schriftart fest. Der Browser auch:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWtTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c2af20cd82f6d223b9d82c89d5db719d54eee7a/nunito.png)

**Comment by helfjama** [comment]
Das war anscheinend noch ein altes Problem und ihr habt das schon angepasst.
