### ISSUE TITLE
Problem mit Presentation-Complete (negativer Abstand?)

### ISSUE THREAD

**Issue by franikowsp** [iqb-berlin/verona-modules-aspect#584]
Wie gestern besprochen, gibt es ein Problem mit "Presentation Complete", das mutmaßlich mit negativem Abstand zusammenhängen könnte.

Die Aufgabe liegt hier im Studio: 

https://www.iqb-studio.de/#/a/129/38152/editor

Das Element 04a (der Lesetext) hat einen negativen Abstand nach oben.

Bei der Aufgabe kam man einfach nicht weiter - es sei denn, man stellt alle _Relevant für "Presentation Complete"_-Buttons aus (wir haben dann nicht mehr systematisch geprüft, welches Element genau Verursacher ist).

Im Studio wird eigentlich ein Presentation Complete registriert, soweit ich das sehe (das P wird grün) - im Center geht es aber nicht weiter. Zugänge zu einem Dummy-Testheft, in welchem die Aufgaben verwendet werden, sende ich separat per Mail.

Getestet in Firefox und Edge auf Windows.

**Comment by jojohoch** [comment]
Problem lag in einem ausgeblendeten Abschnitt auf Seite 1, dessen Bedingung zur Sichtbarkeit niemals erfüllt wurde.
