### ISSUE TITLE
Editor: Kodierdetails CMC und DnD

### ISSUE THREAD

**Issue by franikowsp** [iqb-berlin/verona-modules-aspect#586]
Bei CMC-Aufgaben ist es umständlich, an die zu kodierenden Variablen zu gelangen und das ist auch abweichend von den anderen Aufgaben.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE1sQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0bf6feac45a2bf031ce60cf5e4cd54fc65e4c240/grafik.png)

Mindestens wäre es hilfreich, wenn neben der Variable die ID auftauchen würde, um schnell zu überblicken, ob sie bereits angepasst wurde, also vielleicht irgendwo hier (diese Lösung ginge aktuell aber nicht auf, da der default `likert-row-n` vermutlich zu lang wäre):

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHNsQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a91d45416c27ab20cdb3435e2b40c8116c7edfc/grafik.png)

**Comment by rhenck** [comment]
<img width="480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFpGQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5fb4b57a722744c47348ca2caa68a515d57f2d50/Unsaved%20Image%202.jpg" alt="Unsaved Image 2.jpg" />

**Comment by rhenck** [comment]
Welche Variante, wäre denn nun dein Favorit?

**Comment by franikowsp** [comment]
Unsere Präferenzen wären von oben nach unten:

1. Die Variante, die ich zuletzt vorgeschlagen hatte, sofern umsetzbar ("dritte Möglichkeit")
2. Deine erste Variante (kein Tooltip)
3. Deine zweite Variante (mit Tooltip - hätte aber dann nicht mehr so viel Mehrwert im Vergleich zum Extra-Klick auf den Schlüssel)

Falls 1. nicht umsetzbar, wäre 2. für uns aktuell eine große Hilfe.

**Comment by rhenck** [comment]
Wie ist denn "dritte Möglichkeit" entstanden? Hast du das via Bildbearbeitung gemacht oder hast du dafür Stylings?

Außerdem: Soll die Variante zusätzlich Tooltips haben, wie auf deinem Screenshot?

**Comment by franikowsp** [comment]
Ja, die ist leider auf die Schnelle mit Bildbearbeitung in PowerPoint entstanden (daher auch der Tooltip - der soll nicht dabei sein) - ist vermutlich aufwendiger zu implementieren (und würde sich vielleicht auch nicht gut in das sonstige UI einfügen). 

Gern also die erste Variante, wenn möglich!

**Comment by rhenck** [comment]
Wie wärs hiermit?

<img width="380" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3VmQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--05599a73b415cf80b33b0737b4034f95d8b43ca0/image.png" alt="image.png" />

**Comment by franikowsp** [comment]
Das gefällt uns sehr, sehr gut!! (Für mich persönlich müsste das Label nicht unbedingt kursiv sein, aber ich könnte damit leben).

**Comment by franikowsp** [comment]
Für DnD ist das bereits sehr hilfreich! Ebenfalls wäre diese Neuerung noch Wünschenswert für die **Zeilen** von CMC-Elementen (Optionstabelle), da diese ebenfalls Basisvariablen verbergen.
