### ISSUE TITLE
Editor: Verbundene Ablegelisten

### ISSUE THREAD

**Issue by franikowsp** [iqb-berlin/verona-modules-aspect#587]
Wenn man Ablegelisten erstellt oder (was häufiger vorkommt) bearbeitet, muss man oft sehr viele Elemente zusammenklicken. Beim Ändern des Namens (für Kodierung notwendig!) ist das auch immer erforderlich und birgt ein großes Fehlerpotential.

Es wäre in vielen Fällen hilfreich, wenn unter „Verbundene Ablegelisten“ alle Elemente auf einmal ausgewählt werden könnten.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzBsQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--88da2a1df8eec8692e1d62e8dd71180b72d7f778/grafik.png)

Das Problem würde sich weniger stark ergeben, wenn sich ID-Änderungen im Editor (und im Kodierungs- sowie dem Metadaten-Fenster durchschlagen würden). Dadurch, dass aber die Kodierung die Verbindung zwischen den Ablegelisten löst, ist das Wiederherstellen sehr zeitaufwendig.

**Comment by rhenck** [comment]
Meinem Verständnis nach ist hier die gewünschte Lösung, dass bei Umbenennung (ID) von Ablegelisten sich die Referenzen, die wonaders angelegt sind mitaktualisieren. Korrekt? Die Idee mit der Auswahl aller Elemente ist damit hinfällig oder wollt ihr das trotzdem?

**Comment by franikowsp** [comment]
Genau, wenn die ID-Umbenennung ohne Konsequenzen für das Funktionieren der Aufgabe sind (inbesondere hier: Verbindungen aufgelöst), wäre dieses Feature (für uns in der Kodierung - ob es nicht bei der Anlage zumindest noch praktisch wäre, weiß ich nicht genau) überhaupt nicht mehr akut.

**Comment by rhenck** [comment]
Also die Sache mit dem Auswählen aller Elemente auf einmal ist umgesetzt. Das war ohne großen Aufwand machbar.
Das ändern, der IDs ist deutlich aufwändiger. Außerdem müsste man das dann auch für die Sichtbarkeitsregeln machen. Hier bin ich etwas zögerlich mich dadran zu machen und da relativ viel Zeit reinzustecken. Also priorisiert das mal bitte.
