### ISSUE TITLE
Hintergrundfärbung Eingabefeld

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#592]
Mir ist beim Testen der Aspect-Version 2.2 noch etwas aufgefallen:
in Aspect 2.1.2 sieht die Hintergrundfarbe für ein Eingabefeld so aus:

<img width="762" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTQzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99e3d8de5247fbc2baec4a91ae35e414854d4f89/Feldalt.png" alt="Feldalt.png" />

in Aspect 2.2.1/2.2.2 hingegen so:

<img width="761" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTgzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b7317a62ed339b8d23a1a768356289f89f1bdd0/Feldneu.png" alt="Feldneu.png" />

Da ist wahrscheinlich irgendwas beim Bugfix des augefüllten Eingabefelds für das umrandete Eingabefeld schiefgelaufen?

**Comment by rhenck** [comment]
Entscheidener Hinweis: nur bei fehlender Beschriftung

**Comment by rhenck** [comment]
Das geht nur mit sehr tiefem Eingreifen in das Funktionieren des Eingabefeldes. Hintergrundfarbe ändern ist bei dem Framework nicht vorgesehen. Sowas sollten wir eigentlich unterlassen und wenns nach mir ginge, würde das Feature rausfliegen. Aber ich vermute, das wäre inakzeptabel. :)

**Comment by helfjama** [comment]
Müssten wir nochmal besprechen, mir ist nicht ganz klar ob das jetzt gemacht wurde oder als zu kompliziert abgehakt wurde.

**Comment by rhenck** [comment]
Das müsste erledigt sein. Hier der Commit:
https://github.com/iqb-berlin/verona-modules-aspect/commit/3604215901bfdcfec4b22bc7737b2558db6b7cd2
Keine Ahnung warum der nicht automatisch hier erscheint.
