### ISSUE TITLE
Rechenkästchen untere Hilfszeile durch uns bearbeitbar

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#599]
Die untere Hilfszeile müsste auch noch durch uns bearbeitbar gemacht werden. Die Funktionsweise könnte dafür genau sein wie bei der Ergebniszeile (Standard: Alles von SuS bearbeitbar, wird im variablen Format ausgegraut wenn nicht angezeigt).
Im UI wäre der beste Platz dafür wahrscheinlich direkt über der Ergebniszeile.

**Comment by jojohoch** [comment]
Das  heißt, dass das Verhalten genauso ist, wie bei anderen Zellen bzw. Zeilen mit Vorbelegung:

Ist KEIN Eintag vorhanden, können (weiterhin) alle Zellen bearbeitet werden.
Ist ein Eintrag vorhanden, müssen bearbeitbare Zellen durch Leer- bzw. Unterstrich gekennzeichnet werden

**Comment by helfjama** [comment]
Ja, genauso wäre das erwartete Verhalten!
