### ISSUE TITLE
Rechenkästchen Eintippen überscheibt eigene Eingabe

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#600]
Wäre es möglich bei den Rechenkästchen einzustellen, dass man nach dem Eingeben einer Zahl automatisch ins nächste Feld springt?
Das wäre für die Helferzeilen nicht notwendig, aber für die normalen Zeilen sehr wichtig! Der Schreibfluss soll eigentlich nicht unterbrochen werden.

**Comment by rhenck** [comment]
Ja das ginge, ist aber nicht so einfach. Es gibt ja auch das Ticket, dass man mit Cursortasten navigieren kann. Ich habe das mal angeschaut, aber dann die Arbeit daran wieder eingestellt, weil mir der Aufwand nicht vor dem Ertrag zu stehen schien.
Zum technischen Hintergrund: Das sind ja im Prinzip alles Eingabefelder und die sehen sowas nicht vor. Man müsste also vermutlich das technische Gerüst komplett neu machen, sodass das keine echten Eingabefelder sind. Was allerdings auch wieder bzgl. der Barrierefreiheit bedenklich ist. Also vermeintlich einfaches Ticket, dass sich als ziemlich kompliziert herausstellt, wenn man länger drüber nachdenkt.

**Comment by helfjama** [comment]
Bitte noch nicht angehen, sondern bis zum FF warten, gibt noch paar Dinge zu besprechen

**Comment by helfjama** [comment]
Schreibrichtung bei Rechenverfahren nicht konstant, deshalb können wir das doch leider nicht.
