### ISSUE TITLE
Verzögerung Einblendung Sichtbarkeitseinstellungen

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#615]
Browserübergreifend (mindestens Firefox und Edge) funktionieren die Sichtbarkeitseinstellungen häufig nur zeitverzögert.
Wenn ich also z.B. die Bedingung "Audio>0" vergebe, dauert es nach dem Start des Audios häufig noch mehrere Sekunden, bevor der jeweilige Abschnitt eingeblendet wird. Diese Zeit verkürzt sich (teilweise auch auf die gewünschten 0 Sekunden), wenn man vorher schon länger auf der Seite wartet.
Ich habe euch hier ein Beispiel verlinkt, aber es tritt eigentlich immer auf, wenn wir Sichtbarkeitseinstellungen so verwenden: https://www.iqb-studio.de/#/a/151/34860/preview

**Comment by jojohoch** [comment]
Um den Server nicht mit zuvielen Requests zu überlasten senden Audios/Videos anders als zunächst vermutet nur alle 5 Sekunden ihre Zustandsänderungen. 
Audios/Videos informieren nun unmittelbar nach dem Starten zusätzlich über ihre Statusänderung
