### ISSUE TITLE
Formel: Zeichenhöhen Formeleingabe

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/verona-modules-aspect#629]
## Editor: 2.4.1

Hier scheinen nicht alle Zeichen auf einer Höhe zu sein. Die gelb markierten scheinen auf einer anderen Höhe zu liegen als die nicht markierten Zeichen. 

<img width="480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNitFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--460f0d748b84d2d61381befe5cfc96c67db78e64/Screenshot%20from%202024-02-23%2011-03-17.png" alt="Screenshot from 2024-02-23 11-03-17.png" />

Es müssten noch einmal alle Zeichen kontrolliert werden, denn einzelne Zeichen scheinen weder auf der Höhe der gelb markierten, noch auf der Höhe der nicht markierten Zeichen zu liegen.

**Comment by rhenck** [comment]
Das Mathefeld ist eine Fremdprogrammierung, in der ich ungerne rumpfuschen möchte. Und da die Verschiebung meiner Ansicht nach, wenn überhaupt, minimal ist, würde ich das gerne unbearbeitet lassen. Einverstanden?

**Comment by rhenck** [comment]
Kann es sein, dass es an der gelben Hintergrundfarbe liegt und nicht an den Zeichen selbst? Vorschlag zuzmachen bleibt aber bestehen. ;)
