### ISSUE TITLE
Markierung und Hervorhebung Interaktion

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#633]
Wie im FF besprochen:
Markierung und Hervorhebung Interaktion: Hervorhebungen verdecken Markierungen - die Interaktion sollte anders sein, Markierungen müssen auch unter Hervorhebungen zu sehen sein. 
Vorschlag FF: Transparenzwert Hervorhebung herunterstellen
Farbe Hervorhebung: #dccce6; RGB 220, 204, 230 (neue Standardfarbe)

**Comment by jojohoch** [comment]
Die vorgeschlagene Lösung ist technisch nicht machbar. Es gibt keine unterschiedlichen Layer mit jeweiligen Farben, sondern es gibt HTML-Elemente mit Texten deren Hintergrundfarbe unter bestimmten Bedingungen gesetzt, bzw. Überschrieben wird.
Es ist daher aber möglich eine weitere, neutrale, Farbe einzuführen, um deutlich zu machen, dass in einem hervorgehobenen Textstellen markiert sind. Es könnten sogar  für alle drei Markierfarben unterschiedliche  weitere Farben definiert  werden.
