### ISSUE TITLE
IQB-Tastatur wird neuerdings im Vollbildmodus als Sicherheitsrisiko eingestuft

### ISSUE THREAD

**Issue by franikowsp** [iqb-berlin/verona-modules-aspect#639]
# Fehlerbeschreibung

Die IQB-Tastatur wurde in der letzten Review-Runde ([https://testcenter.iqb.hu-berlin.de/](https://testcenter.iqb.hu-berlin.de/) auf dem iPad im Vollbildmodus als Sicherheitsbedrohung eingestuft und ist daher nicht verfügbar (wir müssen nochmal in Erfahrung bringen, ob es nur Review-Kommentare betraf oder auch Eingaben im Test selbst).

![Image20240408104257](https://github.com/iqb-berlin/testcenter/assets/60889089/e8f12b4a-d517-44fe-bef4-2978444f3818)

# Kontext
**Server**: Test-Server 15.0.0
**Modus**: run-review (vermutlich aber auch flächendeckender?)0
**Browser**: Safari 16.2, 17.3.1

**Comment by jojohoch** [comment]
Was sind Kommentarfelder und im Gegensatz dazu Antwortfelder?

**Comment by franikowsp** [comment]
Kommentarfelder sind Review-Felder im Testcenter (diese sind jedoch nicht betroffen - das kann ignoriert werden).

**Comment by jojohoch** [comment]
Die letzte Änderung an der IQB-Tastatur  ist vom 23 Februar:
"Eingabefeld im Lückentext: Eingestellte Zeichenbegrenzung wird von IQB-Tastatur berücksichtigt"

**Comment by jojohoch** [comment]
https://www.mobiflip.de/shortnews/ios-12-schutz-gegen-boesartige-web-tastaturen/

**Comment by franikowsp** [comment]
Das merkwürdige ist, dass es bei CMC-Kästen (also MC-Tabellen) sporadisch auftaucht (siehe Zugänge, die ich per Mail gesandt hatte). Das war wohl bis vor Kurzem nicht der Fall 🤔

**Comment by jojohoch** [comment]
Aus dem Link s.o. geht hervor, dass dieses Sicherheitsfeature seit iOS 12 existiert. Das Auftreten wirkt vermutlich deshalb sporadisch: "Befindet sich der Nutzer im Browser im Vollbildmodus und fängt im unteren Bildschirmbereich an zu tippen, erscheint eine entsprechende Warnung"

**Comment by rhenck** [comment]
Auf Achims Anweisung: Können wir nix machen - > zu
