### ISSUE TITLE
Neuentwurf Vorlagen

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#641]
Wir haben ja schon länger drüber geredet: Wir brauchen für die AEs eine neue Möglichkeit Items im Editor zu generieren.
Wenn ich es richtig im Kopf habe, waren die beiden bisher präferierten Optionen:

1. Ein "Vorlagenrepositorium", an dem man sich dann über irgendeine Art von Pfadsystem die richtige Vorlage aussuchen kann (+ möglicherweise Suchfunktion). Die Vorlage wird dann aus dem Vorlagenrepositorium automatisch in den Abschnitt im Editor eingefügt.

2. Ein "Assistent" im Editor, in dem man Informationen über Dropdown-Elemente auswählt und der dann die jeweiligen Items erzeugt - z.B. MC, 3 Optionen, Audios davor, Aufgabennummer, ...

Das ganze müssten wir dann zeitnah weiter besprechen, eigentlich bräuchten wir noch im (Spät-)Sommer eine halbwegs funktionierende Lösung.

Habe ich sonst noch etwas wichtiges aus der Diskussion vergessen? Ergänzt sehr gerne!

**Comment by rhenck** [comment]
Kann das zu?

**Comment by helfjama** [comment]
Ja, ist ja passiert :)
