### ISSUE TITLE
Tabellenfeature

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#642]
Idee aus Besprechung: pinker Abschnittsböppel der Tabellenspalten und Zeilen im Abschnitt festlegt. Dieser soll dann Linien im Grid ziehen und auch Einstellungen der Elemente darin beeinflussen (Abstände, Ausrichtung, Rahmen, ... - wie genau muss noch besprochen werden - relevante Elemente: Textfelder, Eingabefeldern, DnD, ...)
Außerdem: Einfärben einzelner Felder dieses Tabellengrids möglich machen?

**Comment by rhenck** [comment]
"Einfärben einzelner Felder dieses Tabellengrids möglich machen?"
An wen richtet sich die Frage?

**Comment by rhenck** [comment]
Abschnittseigenschaften:
Variante A (schlechter)
- von wo ('links'/'rechts'; oben/unten)
- Anzahl Spalten
- Anzahl zeilen

Variante B
- Punkt A (mit x/y)
- Punkt B (mit x/y)
-> aufgespanntes Rechteck (das auch innenliegende Fläche darstelllen kann)

- (Rahmeneigenschaften)
Zusatz (schön): Tabellenbereich via in LIbreOffice-Writer definieren

- Kontextinfo (ist Teil einer Tablle oder nicht) wird an Kinderelemente übergeben und die passen ihre Darstellung an

**Comment by rhenck** [comment]
> Einfärben einzelner Felder dieses Tabellengrids möglich machen

Das ist in unserem momentanen Modell nicht möglich. Da müsste man sich manuelle ein Rahmen in die Zelle legen und stylen.

**Comment by helfjama** [comment]
> > Einfärben einzelner Felder dieses Tabellengrids möglich machen
> 
> Das ist in unserem momentanen Modell nicht möglich. Da müsste man sich manuell ein Rahmen in die Zelle legen und stylen.

Damit sollten wir denke ich zurechtkommen, können wir aber gerne im FF oder nach der Beta des features noch besprechen.
