### ISSUE TITLE
Hochstellen von Zahlen und Buchstaben: Zeilenabstand darunter zu groß

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#643]
Hochstellen von Zahlen oder Buchstaben in anderer Schriftgröße sorgt für größeren Zeilenabstand zur Zeile darunter. Beim Hochstellen dieselbe Schriftgröße zu verwenden sieht aber bei m2; 1e oder ähnlichem nicht gut aus

**Comment by rhenck** [comment]
Was heisst "m2; 1e"? Kannst vllt nochn Screenshot eine Beispielaufgabe dazupacken?

**Comment by helfjama** [comment]
Hier noch ein Screenshot: je kleiner man die Schriftgröße des hochgestellten Zeichen macht, desto größer wird der Zeilenabstand zu Zeile darunter:

![grafik](https://github.com/iqb-berlin/verona-modules-aspect/assets/78479216/b2f4d141-4f26-4c54-acd5-7497967692c0)
