### ISSUE TITLE
Presentation complete erst, wenn gewisser Prozentsatz gesehen wurde

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#644]
Presenation Complete greift (als komplett gezeigt gewertet ) derzeit sobald ein Pixel des Elements ”da ist”, also auch bei einem Abstandpixel, ggf. ändern zu z.B. 50% des Elementes soll da sein, bis es als komplett gezeigt gewertet wird und man weiter kann (müssen uns noch auf Prozentsatz einigen)

**Comment by jojohoch** [comment]
bei 100%
