### ISSUE TITLE
mehrere Hervorhebungen gleichzeitig

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#645]
Wäre es möglich bei Triggern und normalen Hervorhebungen die Möglichkeit zu geben, mehrere Hervorhebungen gleichzeitig zu aktivieren?

**Comment by jojohoch** [comment]
In Player 1.28.3 habe ich den gegenteiligen Wunsch implementiert!
Seid ihr sicher, dass ihr wieder zurück wollt?

**Comment by helfjama** [comment]
Jein - also ja, wir sind uns sicher, dass wir es wollen, aber nur wenn wir weiterhin eine Funktionalität haben auch mit Triggern Hervorhebungen zu überschreiben / auszuschalten (siehe https://github.com/iqb-berlin/verona-modules-aspect/issues/646).
