### ISSUE TITLE
Hervorhebungen ausschalten

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#646]
Wir bräuchten für die Hervorhebungen eine "Ausschalten"-Möglichkeit. Unsere Idee ist es, beim Auswählen der zu hervohebenden Stelle (z.B: beim Trigger) im Dropdown-Menü noch eine "Hervorhebungen ausschalten"-Option hinzuzufügen.

**Comment by rhenck** [comment]
Ich habe ein älteres Ticket gefunden, dass sehr ähnlich klingt: #516
Kann eins davon zu?

**Comment by helfjama** [comment]
Ja, ich habe das alte Ticket geschlossen. Dieses Ticket hier hängt aber auch mit https://github.com/iqb-berlin/verona-modules-aspect/issues/645 zusammen - beide Tickets sollten am besten zusammen bearbeitet werden.

**Comment by helfjama** [comment]
Wir können gerne im FF kurz über beides reden
