### ISSUE TITLE
Pflichtaudios/optionale Audios

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#660]
Wir wissen, dass es diese Unterscheidung nicht gibt, hätten aber gerne eine Möglichkeit das visuell selbst zu machen - gäbe es bei Audioelementen die Möglichkeit z.B. die Farbe frei einstellen zu können?

**Comment by rhenck** [comment]
Welche Farbe ist hier gemeint? Hintergrundfarbe des Player-Elements?

**Comment by helfjama** [comment]
Ja, genau

**Comment by helfjama** [comment]
Geht nur um Hintergrundfarbe, genau
