### ISSUE TITLE
Navigationspfeile Eingabehilfe

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#663]
Die Navigationspfeile oben/unten führen an den Anfang/das Ende des Textes. Die war für die SuS anscheinend sehr verwirrend - wäre es möglich, dass die Pfeile wie in einem normalen Texteditor eine Zeile höher oder niedriger bringen?

**Comment by jojohoch** [comment]
nee. geht nicht, da wir nicht in Zeilen navigieren können. Das element kennt lediglich seinen text und weiß nicht auf wieviel Zeilen dieser aktuell fargestellt wird

**Comment by helfjama** [comment]
Dann lassen wir es so
