### ISSUE TITLE
validPages hat ein falsches Format

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/verona-modules-aspect#666]
**validPages Format von Verona 2 - 5** 
```
This data is structured as "page key" => "page label", so we have (1) keys for navigation commands or state notifications and (2) strings as labels of navigation buttons if needed.
```
wird z. B. vom Simple 4, Aspect 1.9, Dan 3.0 so interpretiert:

```lang-ts
export interface Verona5ValidPages {
  [id: string]: string
}
# also so
{
    "0": "Seite 1",
    "1": "Seite 2",
    "2": "Seite 3"
}

```
**validPages Format Verona 6**

```lang-ts
export interface Verona6ValidPage {
  id: string;
  label?: string;
}

[
  {
    "id": "1" ,
    "label": "seite1"
  },
  {
    "id": "2" ,
    "label": "seite2"
  },
]
export type Verona6ValidPages = Array<Verona6ValidPage>;
```

**Format von Aspect Player 2.4.11**

```
[
  {
    "0": "Seite 1"
  },
  {
    "1": "Seite 2"
  },
  {
    "2": "Seite 3"
  }
]

```

Entspricht also keiner Version des Verona-Standards. Führt in der aktuellen Version nur dazu, dass Page-Labels im Testcenter nicht korrekt angezeigt werden.

Dieses Format taucht schon mal in Aspect 1.2.4 auf, während in 1.9.0 das richtige Format ausgegeben wird. Dieser liefert allerdings dafür einen falschen Wert für `currentPage`, nämlich, wie alle getesteten Versionen von Aspect einen stringifizierten Index ab 0 zurück, also z. B. "0". Als Seiten-Ids liefert er jedoch "page1", "page2" usw. Beides ist nicht zusammenzubringen, daher funktioniert in dieser Version  das Anzeigen und Wiederherstellen der aktuellen Seite und die Navigation allgemein nicht.

**Comment by paflov** [comment]
[aspect-1.2.4.unit.json](https://github.com/user-attachments/files/15838780/aspect-1.2.4.unit.json)
[aspect-1.9.0.unit.json](https://github.com/user-attachments/files/15838781/aspect-1.9.0.unit.json)
[aspect-2.4.11.unit.json](https://github.com/user-attachments/files/15838782/aspect-2.4.11.unit.json)

**Comment by jojohoch** [comment]
Kann ich nicht bestätigen. Player 2.4.11 schickt diese Object:
{
    "0": "Seite 1",
    "1": "Seite 2",
    "2": "Seite 3"
}
