### ISSUE TITLE
zuletzt geöffnete Seite kann nicht wieder hergestellt werden

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/verona-modules-aspect#667]
Wenn ich eine `pageId` mit `playerConfig.startPage` im `vopStartCommand` übergebe, wird die Seite nicht wieder hergestellt.
Betrifft: Aspect Player 2.4.11

Habe es mt `2`, `"2"` und `page2` als pageId versucht, der Player startet immer mit Seite 1.

Hängt sicher damit zusammen: https://github.com/iqb-berlin/verona-modules-aspect/issues/666

**Comment by paflov** [comment]
[aspect-2.4.11.unit.json](https://github.com/user-attachments/files/15838773/aspect-2.4.11.unit.json)

**Comment by jojohoch** [comment]
Nee ist unabhängig: pageId ist nicht implementiert
