### ISSUE TITLE
erster Betatest 2.5.0

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#672]
https://www.iqb-studio.de/#/a/438/58833/preview

Tabellenfeature:

- [x] Knopf zum Anwählen der Tabelle wäre praktisch
- [ ] DnD Text, Eingabefeld Text und Audiobutton sind auf der "richtigen" Höhe, bitte Text in Textfeldern noch auf dieselbe Starthöhe bringen. Außerdem hat das Eingabefeld keinen Innenabstand zu den Rändern
- [x] Elemente in Tabelle haben Raster- und Abstandseinstellungen. Diese funktionieren aber nicht und können bei Benutzung die Tabelle zerstören. Einfach weglassen hier? - Genauso auch die Dimensionseinstellungen darunter: der ganze zweite Tab macht nichts?
- [x] Audioelement: Ich glaube hier hatten wir abgesprochen, dass das Audioelement zwei verschiedene Hintergrundfarben haben müsste: Einmal die des Audioelements selbst (Standardfarbe wie bisher) und dann die des Rests der Zelle (sollte standardmäßig transparent sein, ist im Moment grau)
- [x] Kontrollkästchen: Orientiert sich im Moment an der längeren Seite und passt dann die Tabelle auf die jeweilige Höhe/Breite an (vergrößert sie). Sollte sich aber von der Größe an die kleiner Seite anpassen und sich dann zentriert in die Mitte der Zelle legen. Ergibt das Sinn so, oder haben wir irgendwas nicht bedacht?
- [x] Eingabefeld: Beschriftugn funktioniert nicht - weglassen? Genauso auch Auswahl umrandet/ausgefüllt
- [x] Höhe und Breite: Keine dynamische Einstellung möglich?

Studio: Elementliste leicht zu schmal (wenn Scrollbalken da) -> führt zu komischen Umbrüchen?

Alles andere sah sehr gut aus! Bisher habe aber auch nur ich getestet, vor dem Release würden wir nochmal eine größere Runde machen.

**Comment by rhenck** [comment]
> Knopf zum Anwählen der Tabelle wäre praktisch
habe ich auch schon festgestellt, wusste aber nicht wohin damit. Also müsste man über die Elementliste gehen. Bin aber für Vorschläge offen.

**Comment by rhenck** [comment]
> bitte Text in Textfeldern noch auf dieselbe Starthöhe bringen

Welche wäre das?

**Comment by rhenck** [comment]
> Außerdem hat das Eingabefeld keinen Innenabstand zu den Rändern

Kann ich nicht reproduzieren.

**Comment by rhenck** [comment]
> Audioelement: Ich glaube hier hatten wir abgesprochen, dass das Audioelement zwei verschiedene Hintergrundfarben haben müsste: Einmal die des Audioelements selbst (Standardfarbe wie bisher) und dann die des Rests der Zelle (sollte standardmäßig transparent sein, ist im Moment grau)

Also dass wir besprochen haben, mehrere Hintergrundfarben für die Audios mitzuführen, ist mir neu. Das müssen wir nochmal genauer überlegen. Hier mache ich erstmal nix.

**Comment by rhenck** [comment]
> Kontrollkästchen: Orientiert sich im Moment an der längeren Seite und passt dann die Tabelle auf die jeweilige Höhe/Breite an (vergrößert sie). Sollte sich aber von der Größe an die kleiner Seite anpassen und sich dann zentriert in die Mitte der Zelle legen. Ergibt das Sinn so, oder haben wir irgendwas nicht bedacht?

Das hat sich erledigt oder?

**Comment by rhenck** [comment]
> Höhe und Breite: Keine dynamische Einstellung möglich?

Ist mir noch nicht klar, wie das funktionieren sollte. Müssen wir genauer besprechen. Mache erstmal nix.

**Comment by rhenck** [comment]
> Studio: Elementliste leicht zu schmal (wenn Scrollbalken da) -> führt zu komischen Umbrüchen?

Kann ich nicht reproduzieren. Haste mal ein Beispiel? vllt nen Screenshot?

**Comment by helfjama** [comment]
> > bitte Text in Textfeldern noch auf dieselbe Starthöhe bringen
> 
> Welche wäre das?

-> Ich glaube 16 px, aber ich weiß nicht ganz, wie das min den Tabellen funktioniert. Es soll genauso wie Eingabefelder und DaDs einfach auf der selben Höhe beginnen.



> > Außerdem hat das Eingabefeld keinen Innenabstand zu den Rändern
> 
> Kann ich nicht reproduzieren.

->My bad, das Eingabefeld stimmt. Ich meinte das Textfeld, dort klebt der Text direkt am Rand und oben (hängt auch mit dem vorherigen Punkt zusammen).




> > Audioelement: Ich glaube hier hatten wir abgesprochen, dass das Audioelement zwei verschiedene Hintergrundfarben haben müsste: Einmal die des Audioelements selbst (Standardfarbe wie bisher) und dann die des Rests der Zelle (sollte standardmäßig transparent sein, ist im Moment grau)
> 
> Also dass wir besprochen haben, mehrere Hintergrundfarben für die Audios mitzuführen, ist mir neu. Das müssen wir nochmal genauer überlegen. Hier mache ich erstmal nix.

-> Könntest du den normalen Hintergrund dann vielleicht erstmal transparent machen und nur den Audioböppel grau (Größe wie er im Moment beim hovern Hervorgehoben wird)




> > Kontrollkästchen: Orientiert sich im Moment an der längeren Seite und passt dann die Tabelle auf die jeweilige Höhe/Breite an (vergrößert sie). Sollte sich aber von der Größe an die kleiner Seite anpassen und sich dann zentriert in die Mitte der Zelle legen. Ergibt das Sinn so, oder haben wir irgendwas nicht bedacht?
> 
> Das hat sich erledigt oder?

-> Denke ja

**Comment by helfjama** [comment]
> > Studio: Elementliste leicht zu schmal (wenn Scrollbalken da) -> führt zu komischen Umbrüchen?
> 
> Kann ich nicht reproduzieren. Haste mal ein Beispiel? vllt nen Screenshot?

Ich auch nicht mehr, hängt vielleicht vom Bildschirm ab - ignorieren?

**Comment by rhenck** [comment]
> Eingabefeld: Beschriftugn funktioniert nicht - weglassen? Genauso auch Auswahl umrandet/ausgefüllt

umrandet/ausgefüllt habe ich weggemacht. Beschriftung erfordert größere Umbauten.

**Comment by rhenck** [comment]
bitte Text in Textfeldern noch auf dieselbe Starthöhe bringen

    Welche wäre das?

-> Ich glaube 16 px, aber ich weiß nicht ganz, wie das min den Tabellen funktioniert. Es soll genauso wie Eingabefelder und DaDs einfach auf der selben Höhe beginnen.

Okay also erstmal sollten wir den Begriff Textfelder nie mehr benutzen. Der verwirrt immer wieder, hier auch. Gemeint ist Textelement.

Vermutlich stehe ich gerade auf dem Schlauch (sorry), aber ich raffe nicht, was hier getan werden soll. Was ist eine "Starthöhe"? Heisst das, dass der Text zentriert werden soll, wie in Eingabefeldern und DaDs?

**Comment by helfjama** [comment]
> ```
>     bitte Text in Textfeldern noch auf dieselbe Starthöhe bringen
> 
> Welche wäre das?
> ```
> 
> -> Ich glaube 16 px, aber ich weiß nicht ganz, wie das min den Tabellen funktioniert. Es soll genauso wie Eingabefelder und DaDs einfach auf der selben Höhe beginnen.
> 
> Okay also erstmal sollten wir den Begriff Textfelder nie mehr benutzen. Der verwirrt immer wieder, hier auch. Gemeint ist Textelement.
> 
> Vermutlich stehe ich gerade auf dem Schlauch (sorry), aber ich raffe nicht, was hier getan werden soll. Was ist eine "Starthöhe"? Heisst das, dass der Text zentriert werden soll, wie in Eingabefeldern und DaDs?

Bei Textfeld bin ich bei dir, ist jetzt ein Textelement.
Und jein, es geht um Zentrierung, aber nicht horizontal sondern vertikal. Der Text soll auf der selben Höhe beginnen:

![grafik](https://github.com/iqb-berlin/verona-modules-aspect/assets/78479216/02671916-208f-41dc-b961-5aadeed16693)
