### ISSUE TITLE
2.5 erforderliche Bugfixes und kleinere Anpassungen

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#682]
- [x] CMC Standardmodus: "Kopfzeile fixieren" noch raus aus der Maske (Standardeinstellung ausgewählt passt aber)
- [ ] #720
- [x] Lückentext Zeilenhöhe 180px Voreinstellung
- [x] Lückentext Optionsfelder: Farbe wechselt nicht mehr zurück auf Standard wenn man Haken bei Durchstreichen wieder entfernt, sondern bleibt transparent
- [ ] #721
- [x] "Schreibgeschützt" ist ein Adjektiv und müsste klein geschrieben werden (oder es steht "Schreibschutz" da, ginge auch)
- [x] Nummerierung wird nach Wechsel in die Vorschau im Editor nicht mehr angezeigt
- [ ] #722
- [ ] #723
- [ ] #724
- [ ] #725
- [ ] #726
- [x] Assistent Stimulus Audio: Wie bei Stimulus Text darunter noch ein Textfeld für die Quellenangabe hinzufügen!
- [ ] #727
- [x] MC: Beim Einfügen bleibt das Feld "Beschriftung" nicht leer, auch wenn nichts in der Maske eingetragen wurde.
- [x] Tabellen: kleinere Spalten (<50px) funktionieren nicht richtig, Textfelder stehen über
- [x] Tabellen: Textfelder Ausrichtung (z.B. rechtsbündig) funktioniert nicht)
- [x] Tabellen: Eingabebereiche bitte auch noch in Tabellen
- [x] Tabellen: Wenn möglich Buttons auch noch in Tabellen - bzw. noch besser: Lückentexte in Tabellen? Damit decken wir doch Buttons und weitere Funktionalitäten ab?
- [x] mit Adminrechten erscheint der Haken bei "erweiterter Modus" immer wieder (z.B. beim Anlegen eines neuen Abschnitts)
- [x] Tabellen: die farbliche Markierung bei Textfeldern sollte nicht nur hinter dem Text sein, sondern hinter dem ganzen Feld
- [x] Assistent Audio: Apostroph bei Französisch "l’instruction" falsch - ist ein Hochkomma, soll Apostroph sein
- [x] Assistent Audio: Das mit 2 Audios: 2. Audio soll erst abspielbar sein, wenn erstes mind. 1 Mal abgespielt wurde

**Comment by rhenck** [comment]
"Kopfzeile fixieren" gibt es nicht.

**Comment by rhenck** [comment]
"Lückentext Optionsfelder: Farbe wechselt nicht mehr zurück auf Standard wenn man Haken bei Durchstreichen wieder entfernt, sondern bleibt transparent"

Ich glaube darüber hatten wir gesprochen und das war okay für euch. Jetzt nicht mehr?

**Comment by rhenck** [comment]
"Rechenkästchen Eingabefelder sehr weit weg, außer man benutzt Maximalbreite. Geht das auch ohne Maximalbreite vielleicht?"

Was für Eingabefelder? Weit weg wovon?

**Comment by rhenck** [comment]
"Rechenkästchen: In der Eingabehilfe funktioniert das "=" nicht"

Hierfür gibt es unseres Wissen nach keinen sinnvollen Anwendungsfall. Stimmt das? Falls ja, müssten wir eigentlich nur die Möglichkeit entfernen, die Eingabehilfe mit Rechenzeichen überhaupt dafür einstellbar zu haben.

**Comment by rhenck** [comment]
"Assistent Stimulus Audio: Wie bei Stimulus Text darunter noch ein Textfeld für die Quellenangabe hinzufügen!"

Ist das nicht mit dem Feld "Situierung, Frage, Operator, Hinweise, o.Ä." erledigt?

**Comment by rhenck** [comment]
"Tabellen: kleinere Spalten (<50px) funktionieren nicht richtig, Textfelder stehen über"

Was soll denn mit dem überstehenden Text passieren?

**Comment by rhenck** [comment]
"Tabellen: Textfelder Ausrichtung (z.B. rechtsbündig) funktioniert nicht)"

Der Text ist, wie abgesprochen, zentriert. Ich könnte die horizontale Zentrierung wegmachen, wenn das hier gewünscht wird. Und nicht in ein paar Wochen, es wieder anders werden soll...

**Comment by rhenck** [comment]
"mit Adminrechten erscheint der Haken bei "erweiterter Modus" immer wieder (z.B. beim Anlegen eines neuen Abschnitts)"

Verstehe ich nicht bzw nicht reproduzierbar.

**Comment by rhenck** [comment]
"Tabellen: die farbliche Markierung bei Textfeldern sollte nicht nur hinter dem Text sein, sondern hinter dem ganzen Feld"

Das hängt von der Entscheidung zur der Frage ""Tabellen: Textfelder Ausrichtung (z.B. rechtsbündig) funktioniert nicht)"" ab. Diese ist zuerst zu klären.

**Comment by rhenck** [comment]
"Assistent Audio: Apostroph bei Französisch "l’instruction" falsch - ist ein Hochkomma, soll Apostroph sein"

Habe gerade mal ein speziellen Character ausprobiert, der eni Apostroph sein soll. Erkenne keinen Unterschied. Woran erkenne ich den?

**Comment by helfjama** [comment]
> "Kopfzeile fixieren" gibt es nicht. Ist "Haftende Kopfzeile" gemeint?

Ja, genau.



> "Lückentext Optionsfelder: Farbe wechselt nicht mehr zurück auf Standard wenn man Haken bei Durchstreichen wieder entfernt, sondern bleibt transparent"
> 
> Ich glaube darüber hatten wir gesprochen und das war okay für euch. Jetzt nicht mehr?

Wir haben damit im Standardmodus leider Probleme, da man dort ja absichtlich nicht an die Farbe rankommt - man macht sich damit also die Aufgabe unbearbeitbar dann. Ist es sehr aufwendig?




> "Rechenkästchen Eingabefelder sehr weit weg, außer man benutzt Maximalbreite. Geht das auch ohne Maximalbreite vielleicht?"
> 
> Was für Eingabefelder? Weit weg wovon?

Entschuldigung, da habe ich mich ungenau ausgedrückt: Es geht hier um die Eingabehilfen bei Rechenkästchen. Ohne Maximalbreite tauchen die ganz rechts auf der Seite auf, statt möglichst nah rechts neben den Rechenkästchen. Glaubst du da ist was zu machen, ohne dass man jedes Mal die Maximalbreite einstellen muss?



> "Einfügen in Textelemente ins Studio: Können Formatierung unterdrückt werden? (Standardmäßig ohne Formatierung einfügen)?"
> 
> Dafür müssten wir wahrscheinlich das Pasten unterbinden und selbst den Inhalt der Zwischenablage parsen. Könnt ihr nicht einfach Shift drücken beim Einfügen oder ist das nicht zumutbar?

Für uns auf jeden Fall zumutbar, das Problem ist eher, dass es die AEs jedes Mal falsch machen und wir teilweise sehr komisch formatierte Texte bekommen. Was ist deine Kosten-Nutzen-Einschätzung?



> "Tabellen: kleinere Spalten (<50px) funktionieren nicht richtig, Textfelder stehen über"
> 
> Was soll denn mit dem überstehenden Text passieren?

Da habe ich mich wieder ungenau ausgedrückt: siehe hier: https://www.iqb-studio.de/#/a/68/65365/preview . Wenn der Text übersteht ist das ja erwartet. Was nicht erwartet ist, ist, dass der Text aus dem nächsten Textfeld in das kurze Feld reinwächst.



> "mit Adminrechten erscheint der Haken bei "erweiterter Modus" immer wieder (z.B. beim Anlegen eines neuen Abschnitts)"
> 
> Verstehe ich nicht bzw nicht reproduzierbar.

Wenn man während des Arbeitens sich selbst die Rechte für den erweiterten Modus wegnimmt (oben rechts), bekommt man sie teilweise unberechenbar wieder. Ich habe es nur beim Wechsel zwischen Vorschau und Editor wieder reproduziert bekommen, es soll aber noch häufiger auftreten. Falls einfach behebbar angehen, ansonsten zurückstellen?



> "Assistent Audio: Apostroph bei Französisch "l’instruction" falsch - ist ein Hochkomma, soll Apostroph sein"
> 
> Habe gerade mal ein speziellen Character ausprobiert, der eni Apostroph sein soll. Erkenne keinen Unterschied. Woran erkenne ich den?

Das Hochkomma geht einfach gerade nach unten, der Apostroph hat so ein Häkchen, siehe: https://www.iqb-studio.de/#/a/68/65365/preview

**Comment by helfjama** [comment]
> "Assistent Stimulus Audio: Wie bei Stimulus Text darunter noch ein Textfeld für die Quellenangabe hinzufügen!"
> 
> Ist das nicht mit dem Feld "Situierung, Frage, Operator, Hinweise, o.Ä." erledigt?



> "Tabellen: Textfelder Ausrichtung (z.B. rechtsbündig) funktioniert nicht)"
> 
> Der Text ist, wie abgesprochen, zentriert. Ich könnte die horizontale Zentrierung wegmachen, wenn das hier gewünscht wird. Und nicht in ein paar Wochen, es wieder anders werden soll...



> "Tabellen: die farbliche Markierung bei Textfeldern sollte nicht nur hinter dem Text sein, sondern hinter dem ganzen Feld"
> 
> Das hängt von der Entscheidung zur der Frage ""Tabellen: Textfelder Ausrichtung (z.B. rechtsbündig) funktioniert nicht)"" ab. Diese ist zuerst zu klären.


Können wir diese 3 Punkte im FF besprechen?

**Comment by helfjama** [comment]
> "Assistent Antwortfelder: Fragen (Textfelder) zwischen den Antwortfeldern sind notwendig - müssen auch irgendwie möglich gemacht werden"
> 
> Das ist sehr schwammig. Was soll ich damit machen? Mein erster Reflex ist, dass dann halt mehrfach der Assistent benutzt werden muss.

Es gibt anscheinend sehr regelmäßig Aufgaben mit mehreren Teilaufgaben mit Fragen und Antwortfelder. Die Antwortfelder sollen wie bisher halt eingerückt sein, aber statt nur einer Nummerierung sollen noch Fragen dazwischen stehen. Mit mehrmals dem Assistenten geht das mit dem Einrücken leider nicht. 
Auch hier nochmal im FF über Möglichkeiten sprechen

**Comment by rhenck** [comment]
Entschuldigung, da habe ich mich ungenau ausgedrückt: Es geht hier um die Eingabehilfen bei Rechenkästchen. Ohne Maximalbreite tauchen die ganz rechts auf der Seite auf, statt möglichst nah rechts neben den Rechenkästchen. Glaubst du da ist was zu machen, ohne dass man jedes Mal die Maximalbreite einstellen muss?

Also das kann ich trotzd Erklärung nicht reproduzieren. So sieht es bei mir aus:
<img width="428" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE5mQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8c64ec0978bfbc194c4908e9481e55356d185d9/image.png" alt="image.png" />

**Comment by rhenck** [comment]
"mit Adminrechten erscheint der Haken bei "erweiterter Modus" immer wieder (z.B. beim Anlegen eines neuen Abschnitts)"

Das ist kein Bug, sondern by design. Der Editor bekommt die Info, ob Expertenmodus vom Studio und kann daran außerhalb der jeweiligen Session nix ändern. Mit jedem neuen Öffnen des Editors, wird die Info also wieder geladen. Wenn das verwirrend ist, können wir das manuelle Umstellen gänzlich unterbinden, aber ich ich vermute, dass das nicht wirklich weiterhilft. Daher würde ich die Anforderunge streichen wollen.

**Comment by rhenck** [comment]
"Da habe ich mich wieder ungenau ausgedrückt: siehe hier: https://www.iqb-studio.de/#/a/68/65365/preview . Wenn der Text übersteht ist das ja erwartet. Was nicht erwartet ist, ist, dass der Text aus dem nächsten Textfeld in das kurze Feld reinwächst."

Okay da waren intern Mindestmaße von 50pxx50px für Tabellenzellen angegeben. Die waren für den Dialog gedacht, glaube ich. Da der Dialog jetzt eh mit festen Größen arbeitet, können die weg. Ich hau sie jetzt raus. Schau bitte beim Testen nochmal näher drauf, ob dadurch nicht doch noch was kaputtgegangen ist.

**Comment by rhenck** [comment]
Es nervt ungemein, dass wir hier verschiedene Dinge in einem Ticket behandeln...
Zur Sache: Ich sehe das Problem in deiner Aufgabe, kann es aber selber nicht reproduzieren. In meiner selbst angelegten Aufgabe, erscheint die Hilfe ordnungsgemäßg darunter. Hast ne Ahnung, woran das liegen könnte?

**Comment by helfjama** [comment]
> Es nervt ungemein, dass wir hier verschiedene Dinge in einem Ticket behandeln... Zur Sache: Ich sehe das Problem in deiner Aufgabe, kann es aber selber nicht reproduzieren. In meiner selbst angelegten Aufgabe, erscheint die Hilfe ordnungsgemäßg darunter. Hast ne Ahnung, woran das liegen könnte?

Ja, das werde ich nicht nochmal machen... - Wir benutzen die Einstellung "hinten" damit es nicht Teile der Rechenaufgabe verdeckt, du benutzt wahrscheinlich vorne (unterhalb)?

**Comment by rhenck** [comment]
Das Ticket hier sollten wir mal auseinandernehmen und aus den verbleibenden Sachen seprate Tickets machen. Oder?

**Comment by helfjama** [comment]
Können wir gerne machen

**Comment by rhenck** [comment]
Die übrigens Sachen wurden in separate Tickets überführt. Den Rest bitte dan testen und ggf. zu.
