### ISSUE TITLE
Fehlermeldung bei CMC & Lückentext

### ISSUE THREAD

**Issue by larapohle** [iqb-berlin/verona-modules-aspect#713]

**Comment by larapohle** [comment]
1. beim Öffnen des Editors von CMC- und Lückentext-Aufgaben erscheint folgende Fehlermeldung:

ID already registered: likert-row_4
registerID@about:srcdoc:392:2537679 register@about:srcdoc:392:2538524 registerIDs@about:srcdoc:392:2358373 86/Rr/<@about:srcdoc:392:2356838 935/Te/i</</M[0]@about:srcdoc:392:3286299 invokeTask@about:srcdoc:392:3294971 onInvokeTask@about:srcdoc:392:85353 invokeTask@about:srcdoc:392:3294892 runTask@about:srcdoc:392:3290302 invokeTask@about:srcdoc:392:3296023 935/_/this.invoke<@about:srcdoc:392:3295924 935/Te/E/T.args[0]@about:srcdoc:392:3286011

- Dabei scheint es egal zu sein, ob die Aufgaben bereits exisiterten und nur auf die neueste Version gebracht wurden oder ob es eine neu angelegte Aufgabe ist.

**Exemplarisch:** 
https://www.iqb-studio.de/#/a/482/66176/editor
https://www.iqb-studio.de/#/a/482/66171/editor
https://www.iqb-studio.de/#/a/482/66205/editor

2. beim Anlegen einer neuen CmC-Aufgabe (möglicherweise grundsätzlich bei Listen allgemein) erscheint eine Fehlermeldung, sobald man direkt nach dem Anlegen die IDs umbenennen möchte (s.u.). Man muss den Editor verlassen und anschließend neu laden, damit die Umbenennung der IDs erfolgen kann.

IDService not available
setProperty@about:srcdoc:392:2357564 86/updateElementsProperty/<@about:srcdoc:392:3041700 updateElementsProperty@about:srcdoc:392:3041572 86/editLikertRow/QPe</<@about:srcdoc:392:3217423 next@about:srcdoc:392:18106 _next@about:srcdoc:392:17786 next@about:srcdoc:392:17476 86/next/<@about:srcdoc:392:20650 Tb@about:srcdoc:392:17227 next@about:srcdoc:392:20489 close@about:srcdoc:392:1249145 _finishDialogClose@about:srcdoc:392:1271133 86/h_/<@about:srcdoc:392:1269814 next@about:srcdoc:392:18106 _next@about:srcdoc:392:17786 next@about:srcdoc:392:17476 86/next/<@about:srcdoc:392:20650 Tb@about:srcdoc:392:17227 next@about:srcdoc:392:20489 dispose@about:srcdoc:392:663252 close@about:srcdoc:392:1249133 _finishDialogClose@about:srcdoc:392:1271133 86/h_/<@about:srcdoc:392:1269676 next@about:srcdoc:392:18106 _next@about:srcdoc:392:17786 next@about:srcdoc:392:17476 86/Qi/</<@about:srcdoc:392:256692 86/yZ/this._next<@about:srcdoc:392:22887 next@about:srcdoc:392:17476 86/en/</<@about:srcdoc:392:567750 86/yZ/this._next<@about:srcdoc:392:22887

**Comment by rhenck** [comment]
Bitte nochmal in der Beta6 prüfen.

**Comment by larapohle** [comment]
Die Probleme bestehen weiterhin.

**Comment by rhenck** [comment]
"2. Fehlermeldung beim Umbennen von IDs neu angelegter Aufgaben"

Welche ID änderst du denn? Die vom CMC oder die einer Zeile? Ich kann das Problem nicht nachstellen.

**Comment by larapohle** [comment]
Die vom CMC:
<img width="352" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejZzQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ebde5034fbc44aed8207eb929ee875a796d13510/grafik.png" alt="grafik.png" />

**Comment by rhenck** [comment]
Wie gesagt: Funktioniert bei mir wunderbar. Du machst irgendwas anders als ich. Da brauche ich mehr Infos. . Bzw vorher gerne nochmal in der neuen Beta probieren.

**Comment by larapohle** [comment]
Hab ich gerade gemacht (in der Version 2.5.0) und es klappt einwandfrei. Genau dasselbe funzt in der beta6 nicht und likert_1 bleibt likert_1 
![Screenshot 2024-11-11 at 13-41-15 IQB-Studio BiSta DeS beta_test](https://github.com/user-attachments/assets/bcf073ae-258a-4ecb-b733-5c77ea23faa4)
