### ISSUE TITLE
Fehlerliste 2.6 Beta (TBA)

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#714]
- [x] MM: Manchmal lädt der DnD Assistent nicht
<img width="1134" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem1pQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5067fa0bb39f6761fdbb384fce252626ad70a83/image20241104095859.png" alt="image20241104095859.png" />

- [x] MM: Wenn ich einen Seiteumbruch bei einer Seite mache, dann in die Vorschau gehe und dann wieder in den Editor wird mir der neue Seitenumbruch (also die nun zwei Seiten) nicht mehr angezeigt. Dies klappt nur wenn man usdrücklich auf Sepichern drückt
- [x] MM: Wenn ich mehrere Seiten zu einer Seite zusammenfüge (durch Seitenumbruch entfernen), dann in die Vorschau gehe und dann wieder in den Editor, sind die zusammengefügen Seiten wieder verschwunden und es gibt wieder viele Seiten
- [x] MM: Das Aktualisieren von Aufgaben funktioniert nicht: Im Editior wird alles richtig angezeigt, aber in der Vorschau kann dann die Unit-Info nicht geladen werden. Das Problem lässt sich aber leicht beheben, indem man im Editor was verändert. Dann lädt auch alles in der vorschau (so wie früher beim aktualisieren auch) - JH: Hatten wir nicht mal besprochen, diesen Schritt abzuschaffen?
- [x] LG: (2.6.5): CMC mit mehr als 2 Optionen geben die Fehlermeldung "ID already registered: likert-row_3", obwohl einziges CMC und alles individuelle IDs MM: Bei mir nicht, allerdings wollte ich danach die ID der CMC ändern und dann krieg ich eine Fehlermeldung (siehe ANhang IDServide not available) - JH: Könnt ihr damit was anfangen?
- [x] LG: IDs in CMCs (außerdem DnD Listen und EGFs in Tabellen) nicht veränderbar ("bereits vergeben" obwohl völlig neue ID MM:  passiert noch in neuster Beta
- [x] LG: (2.6.5): IDs lassen sich in Eigenschaften verändern, aber das ändert nicht die ID in der Elementübersicht: Passiert immer noch
- [x] LG: (2.6.5): Assistent DnD: Länge der Ablagelisten wird nicht mehr beeinflusst durch die im Assistenten ausgewählte abgezielte Länge der Ziellisten
- [x] #717
- [x] MM: Wenn ich auf die neue Beta aktualisiere tritt im Editor direkt der unerwarteter Fehler Button auf (Siehe Screenshot im Anahng)
<img width="688" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeitpQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4582f861914ec8fca29e8aca887a589421e44a68/fehlermeldung-update-auf-neue-beta.png" alt="fehlermeldung-update-auf-neue-beta.png" />

- [x] MM: Diese Fehlermeldung (Update auf neue Beta) taucht auch auf als ich zwei Objekte gelöscht habe... oder bei jeglicher anderer Veränderung, die ich vorgenommen habe
- [x] MM: Wenn ich einen Abschnitt löschen will, bei welchem ich vorher die ID ändern wollte (vgl Kommentar #4244) funktioniert das nicht und es gibt eine Fehlermeldung. Wenn ich bei dieser auf "Details ansehen" klicken will, geht das auch nicht
<img width="336" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMENpQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0729b202b3a85ccef9d0125bf453e4c5825249c/screenshot-2024-11-07-at-13-02-58-iqb-studio-probierbereich-tba-team-probierbereich-mia-m.png" alt="screenshot-2024-11-07-at-13-02-58-iqb-studio-probierbereich-tba-team-probierbereich-mia-m.png" />
- [x] Mir ist noch ein Bug aufgefallen: Wenn ich aus einer duplizierten DnD (also der ganze Abschnitt ist dupliziert) ein Element löschen will, taucht ein unerwarteter Fehler auf (dessen Details sich nicht öffnen lassen) Ah jetzt lassen sich die Details öffnen: "IDService not available: text text_32unregisterIDs@about:srcdoc:392:2358500\n86/deleteElements/aa</<@about:srcdoc:392:3041090\n86/deleteElements/aa<@about:srcdoc:392:3041077\nes@about:srcdoc:392:13241\na@about:srcdoc:392:13446\ninvoke@about:srcdoc:392:3294353\nonInvoke@about:srcdoc:392:85537\ninvoke@about:srcdoc:392:3294293\nrun@about:srcdoc:392:3289686\n935/</o/<@about:srcdoc:392:3300727\ninvokeTask@about:srcdoc:392:3294971\nonInvokeTask@about:srcdoc:392:85353\ninvokeTask@about:srcdoc:392:3294892\nrunTask@about:srcdoc:392:3290302\nx@about:srcdoc:392:3296989\ninvokeTask@about:srcdoc:392:3296052\n935/_/this.invoke<@about:srcdoc:392:3295924\n935/Te/E/T.args[0]@about:srcdoc:392:3286011\n"

**Comment by rhenck** [comment]
"Das Aktualisieren von Aufgaben"
Was heisst das? Was sind die Schritte, die man machen muss, um das Problem nachzustellen?

**Comment by rhenck** [comment]
Die ganzen ID-Probleme schaue ich nicht genauer an - die sollten sich hoffentlich alle mit der nächsten Beta erledigt haben. Bitte nochmal testen und bescheid sagen, wenn das Problem weiterhin besteht.

**Comment by rhenck** [comment]
"die ID der Zustandsvariablen wird nicht übernommen, wenn bestehende Aufgaben kopiert und auf die Beta gebracht werden."

Hier bitte auch die Schritte aufschreiben, die ich unternehmen muss, um das Problem nachzustellen.

**Comment by rhenck** [comment]
@larapohle Liebe Lara, es ist leider in letzter Zeit eine Unsitte geworden, dass nur noch solche Sammeltickets gemacht werden. Jakob hat zwar versprochen das zu unterlassen, hält sich aber nicht dran. Fang du bitte nicht auch noch so an. Bitte gesonderte Tickets, außer es sind offensichtlich Dinge die zusammenhängen und leicht zu lösen sind (z.B. Vertipper, neue Standardwerte und sowas). Danke

**Comment by rhenck** [comment]
Der Rest der Tickets sind hoffentlich behobene ID-Probleme. Bitte nochmal testen und dann ggf. separates Ticket.
