### ISSUE TITLE
beta6: ID der Zustandsvariablen wird nicht übernommen 

### ISSUE THREAD

**Issue by larapohle** [iqb-berlin/verona-modules-aspect#718]

**Comment by larapohle** [comment]
- ID der Zustandsvariablen wird nicht übernommen

- Ich habe eine Aufgabe aus der 2.5.0 kopiert und auf die beta6 umgestellt. Die zuvor definierte ID für die Zustandsvariablen wird nicht übernommen (s. Screenshot: die Felder sind leer --> hier müsste eigentlich "Seite" bzw. "Knopf" auftauchen)

<img width="648" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzJuQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3502ec8e58d69bc0e1e6e1adaf362a2cf6590b2e/grafik.png" alt="grafik.png" />
eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2VuQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b21191d039f2a1feb48c7591314098b83557f40/grafik.png" alt="grafik.png" />

2.5.0: https://iqb-studio.de/#/a/482/66278/editor
umgestellt auf beta6: https://iqb-studio.de/#/a/482/66277/editor

**Comment by rhenck** [comment]
Danke für das separate Ticket.
Ich kann das gerade nicht testen, weil das Studio keine Aufgaben in der alten Version anlegen will. Sobald das wieder geht, kann ich mal genauer schauen.

**Comment by larapohle** [comment]
Das funktioniert nun auch! Danke!
