### ISSUE TITLE
[player] Dynamische Sektionen bekommen manchmal Scrollbalken

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/verona-modules-aspect#74]

**Comment by jojohoch** [comment]
vorläufiger hack: overflow: section.dynamicPositioning ? 'hidden' : 'auto',

muss weiter verbessert werden!

**Comment by jojohoch** [comment]
behoben: elementOverflow musste auf display block gesetzt werden!
hack wieder entfernt
