### ISSUE TITLE
Bug Abschnitt verschieben beta 9

### ISSUE THREAD

**Issue by helfjama** [iqb-berlin/verona-modules-aspect#743]
Adminmodus

1. Go to Editor
2. Zweite Seite anlegen (beide Seiten ohne Elemente)
3. Abschnitt in Seite 1 anwählen 
4. "nach unten verschieben" anklicken
5. Fehler

**Erwartetes Verhalten**
Ich würde erwarten, dass sich der Abschnitt selbst nach unten verschiebt. Stattdessen wird ein neuer Abschnitt auf Seite 2 über dem bereits vorhandenen erzeugt. Bug ist nicht aufgabengefährdend

**Screenshots, Links, erschienene Fehlermeldungen**
https://www.iqb-studio.de/#/a/484/68953/editor

**Versionen**
- Verwendete Player-  und Editorversion: 2.6.9
- Betriebssystem: Windows 11
- Browser Firefox [Version 133.00]

**Comment by rhenck** [comment]
Das ist kein Bug. Das angegebene erwartete Verhalten, wäre sehr problematisch, denn dann wäre die erste Seite leer (0 Abschnitte). Stattdessen wird der Abschnitt wie erwartet auf die nächste Seite verschoben und die jetzt eigentlich leere Seite bekommt einen neuen leeren Abschnitt.
