### ISSUE TITLE
[editor] Grid-Abstände in %

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/verona-modules-aspect#94]

**Comment by rhenck** [comment]
Auch für Seitenrand

**Comment by rhenck** [comment]
Dazu in den interfaces die margins auf string umstellen, damit da dann die einheit gleich mit drinsteht.

**Comment by PaulineKohrt** [comment]
wir brauchen auch die festen Abstände, also zusätzlich auch %, nicht stattdessen

**Comment by rhenck** [comment]
Gilt das wirklich auch für Seitenrand?
